### ISSUE TITLE
insert statement will hang with last version

### ISSUE THREAD

**Issue by jdj199222** [mymarilyn/clickhouse-driver#100]
![image](https://user-images.githubusercontent.com/40590418/62117817-3ce3ca00-b2ef-11e9-9759-c22d149d2293.png)
![image](https://user-images.githubusercontent.com/40590418/62118192-d4e1b380-b2ef-11e9-921d-0d58d5326421.png)

**Comment by xzkostyan** [comment]
Hi. Same issue: https://github.com/mymarilyn/clickhouse-driver/issues/83
