### ISSUE TITLE
Distribute the LICENSE file

### ISSUE THREAD

**Issue by kszucs** [mymarilyn/clickhouse-driver#101]
Both with the wheels and the source release. For the time being I've copied the LICENSE file to the conda-forge recipe, which we should remove once it is distributed with the source tarball.

**Comment by xzkostyan** [comment]
OK, next release will contain license.

**Comment by xzkostyan** [comment]
Well, there is license file in wheels. It's placed in `clickhouse_driver-0.1.0.dist-info/LICENSE`. But, it's missed in source distribution. You're right.

**Comment by xzkostyan** [comment]
Release 0.1.1 with license included was published. Should we close this issue?

**Comment by kszucs** [comment]
Yes, thanks @xzkostyan !
