### ISSUE TITLE
【DateTime】Column done_date: integer out of range for 'I' format code

### ISSUE THREAD

**Issue by wen08jie** [mymarilyn/clickhouse-driver#102]
dataJson = "{\"done_date\": \"9919-07-28 18:16:55\"}"

Exception:
Code: 53. Type mismatch in VALUES section. Repeat query with types_check=True for detailed info. Column done_date: integer out of range for 'I' format code

How should I remove the length limit .. when insert into DateTime ?

**Comment by xzkostyan** [comment]
Hi!

You should convert "9919-07-28 18:16:55" into python's datetime:

**Comment by wen08jie** [comment]
I did, but the same exception.
`integer out of range for 'I' format code`

my data:
`[[188808, '776553', datetime.datetime(9019, 7, 28, 18, 16, 55), datetime.datetime(2010, 1, 1, 12, 11, 56)]]`
and code:
`client.execute('INSERT INTO test (%s) VALUES' % 'id,uid,done_date,created_date', data_dict , types_check=True)`

Then i change DateTimeColumn.format = 'Q'
Hint another error：
Code: 62.
DB::Exception: Empty query. Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x7108056]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3536922]
2. clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0xac) [0x6d6563c]
3. clickhouse-server(DB::DataTypeFactory::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x73) [0x63bbed3]
4. clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x586) [0x638a4a6]
5. clickhouse-server(DB::IBlockInputStream::read()+0x262) [0x637f222]
6. clickhouse-server(DB::TCPHandler::receiveData()+0x7b) [0x354405b]
7. clickhouse-server(DB::TCPHandler::receivePacket()+0xcd) [0x35459ad]
8. clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x1cb) [0x3545e7b]
9. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x23b) [0x35463ab]
10. clickhouse-server(DB::TCPHandler::runImpl()+0x76c) [0x3546d3c]
11. clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3547ccb]
12. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x7232fff]
13. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0x72333da]
14. clickhouse-server(Poco::PooledThread::run()+0x77) [0x730f8e7]
15. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x730b7a8]
16. clickhouse-server() [0xb11577f]
17. /lib64/libpthread.so.0() [0x3a72a079d1]
18. /lib64/libc.so.6(clone+0x6d) [0x3a726e88fd]

**Comment by xzkostyan** [comment]
There are examples of inserts in [docs](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html?highlight=insert#inserting-data).

**Comment by wen08jie** [comment]
i know how to inserts data.

but i have a problem.
when i insert a **DateTime** , and the time is big long future time . eg : `**9919-07-28 18:16:55**`

> [https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/columns/datetimecolumn.py](url)
`
    def before_write_item(self, value):
        if isinstance(value, int):
            # support supplying raw integers to avoid
            # costly timezone conversions when using datetime
            return value

        if self.timezone:
            # Set server's timezone for offset-naive datetime.
            if value.tzinfo is None:
                value = self.timezone.localize(value)

            value = value.astimezone(utc)
            return int(timegm(value.timetuple()))

        else:
            # If datetime is offset-aware use it's timezone.
            if value.tzinfo is not None:
                value = value.astimezone(utc)
                return int(timegm(value.timetuple()))

            return int(mktime(value.timetuple()))
`

this function will return **Int number**
if the DateTime is the futrue time . **eg :  9019-08-14 19:02:42 == int(222464401362)** , this is a **long** type

[https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/columns/base.py](url)
'    def make_struct(self, n_items):
        return Struct('<{}{}'.format(n_items, self.format))

    def write_items(self, items, buf):
        s = self.make_struct(len(items))
        try:
            buf.write(s.pack(*items))

        except struct_error as e:
            raise exceptions.StructPackException(e)
'
and the long type will throw exception in this function
`
integer out of range for 'I' format code
`


so.  how should I do ?   Can let me inserts any time.

**Comment by xzkostyan** [comment]
Can you insert value "9919-07-28 18:16:55" with `clickhouse-client`? I've tried with no luck. It was truncated:

```sql
:) create table test (x datetime) engine = Memory;

CREATE TABLE test
(
    `x` datetime
)
ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.008 sec. 

:) insert into test VALUES ('9919-07-28 18:16:55');

INSERT INTO test VALUES

Ok.

1 rows in set. Elapsed: 0.005 sec. 

:) select * from test

SELECT *
FROM test

┌───────────────────x─┐
│ 1970-01-01 18:16:55 │
└─────────────────────┘

1 rows in set. Elapsed: 0.005 sec. 
```

There is a note in [docs](https://clickhouse.yandex/docs/en/single/#data_type-datetime) that DateTime type is limited by 4 bytes (`I` in python).

I think you can store datetime up to 2038 year now.

**Comment by wen08jie** [comment]
ok...
thanks. you are right...
