### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by ofek** [mymarilyn/clickhouse-driver#115]
Hello there! Any idea when binary wheels for Python 3.8 will be distributed on PyPI?

**Comment by xzkostyan** [comment]
Hi.

I'm waiting for python 3.8 support in cibuildwheel https://github.com/joerick/cibuildwheel/pull/172. I'll add binaries for 3.8 as soon as new version of the package with 3.8 support will be available.

**Comment by xzkostyan** [comment]
Hi.

Wheels are ready but I need so time to test them.

**Comment by ofek** [comment]
Yay!

**Comment by xzkostyan** [comment]
Wheels for latest version and python 3.8 are published on pypi.

**Comment by ofek** [comment]
Thank you!
