### ISSUE TITLE
INSERT documentation issues

### ISSUE THREAD

**Issue by nikoschatzis** [mymarilyn/clickhouse-driver#116]
the examples in [Inserting data](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#inserting-data) show the correct behavior of INSERT, i.e., on success, it returns the number of rows inserted -- `def send_data(...)` returns `inserted_rows`

in [API](https://clickhouse-driver.readthedocs.io/en/latest/api.html) in the section for `execute`, it is mentioned that `None` is returned for INSERT queries, which I believe needs to be corrected; also the INSERT examples under [Usage](https://github.com/mymarilyn/clickhouse-driver) can be updated to better show the correct behavior 

is there a section in the docs that documents the exceptions that are thrown on failure of the various methods? if not, would it make sense to include such a section or add in "API" what exceptions are thrown on failure?  

proposed changes:

* `clickhouse_driver/client.py`
  * (row 184) change `:return: * ``None`` for INSERT queries.` to `:return: * on success, number of rows inserted for INSERT queries.`
  * (for INSERT but perhaps for the other methods as well) add `:raises` with the exceptions thrown on failure, e.g., `clickhouse_driver.errors.TypeMismatchError` when INSERT fails because the types do not match
* README.rst update as shown below (or simply reuse the snippet from [Inserting data](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#inserting-data))
```python
>>> client.execute(
...     'INSERT INTO test (x) VALUES',
...      [{'x': 100}]
... )
1
>>> client.execute('INSERT INTO test (x) VALUES', [[200]])
1
```

**Comment by xzkostyan** [comment]
Documentation contains these changes now.
