### ISSUE TITLE
Doesn't work with ipv6-only hosts

### ISSUE THREAD

**Issue by vhaldemar** [mymarilyn/clickhouse-driver#12]
https://gist.github.com/vhaldemar/eb51f28207412ed6128d710a1704c064

**Comment by xzkostyan** [comment]
Hi.

It seems like you use port for HTTP interface (8123). You should use 9000 port for native interface.

**Comment by vhaldemar** [comment]
> It seems like you use port for HTTP interface (8123). You should use 9000 port for native interface.

Yeah, my bad.

But anyway, problem with ipv6-only hosts still exists.
Problem is in that line: https://github.com/mymarilyn/clickhouse-driver/blob/master/src/connection.py#L115
Example: https://gist.github.com/vhaldemar/cedb3c0a83ab0ee8f3a3d6e2a3661a2f

**Comment by xzkostyan** [comment]
Thanks for bug report!

**Comment by xzkostyan** [comment]
Fixed: https://github.com/mymarilyn/clickhouse-driver/commit/508f16fdb62e10f1b3ee477bee4df9fce2a54b60.

0.0.8 release is coming soon.

**Comment by xzkostyan** [comment]
0.0.8 version released.

**Comment by vhaldemar** [comment]
Thank you very much!
Now it works perfectly fine.
