### ISSUE TITLE
performance overhead

### ISSUE THREAD

**Issue by jangorecki** [mymarilyn/clickhouse-driver#120]
I am benchmarking clickhouse and currently using `clickhouse-client`. It is quite cumbersome. It would be much easier to use some scripting language for that. Thus I have question, does `clickhouse-driver` python module impose any overhead in processing queries? clickhouse-server and python sessions would sit on the same machine.

**Comment by xzkostyan** [comment]
Hi!

Yes, there is overhead (memory and CPU) in this package. This driver is written in Python while `clickhose-client` written in C++.

With more rows in response from server you get more overhead. You can see my [comment](https://github.com/mymarilyn/clickhouse-driver/issues/32#issuecomment-512516102) after some cythonization. `clickhouse-client` does the same within 2 seconds on my machine.

Overhead consists of two parts:
* (de)serialization of server response;
* results transposing (columns -> rows):

The second part can be eliminated by using `columnar=True` [parameter](https://clickhouse-driver.readthedocs.io/en/latest/features.html#retrieving-results-in-columnar-form).

**Comment by jangorecki** [comment]
Thanks for explanations
