### ISSUE TITLE
Query execution fails with error Unexpected EOF while reading bytes

### ISSUE THREAD

**Issue by sperez4mba** [mymarilyn/clickhouse-driver#121]
hi,

I've been facing a recurrent error in my application. In a nutshell what my application does is to generate a Clickhouse query statement based on certain input and then execute the query on a Clickhouse server. The queries are somewhat complex but they are only read queries. The Clickhouse client is instantiated with no specific settings.

You can see the complete error traceback I'm getting below:

`
Error on clickhouse-master.almostsavanamed.com:9000 ping: Unexpected EOF while reading bytes
`

`
ERROR:root:{'exception': {'message': 'Traceback (most recent call last):\n  File "./src/user_interface/src/api_action.py", line 25, in handle\n    return self.execution()\n  File "./src/user_interface/action/api/v3/searches/list_diagnostics_api_action.py", line 19, in execution\n    query_response = self._service.execute(query_diagnostics=query_list_diagnostics)\n  File "./src/application/service/list_diagnostics_app_service.py", line 64, in execute\n    diagnostic_view_object_list = self.__list_diagnostics(query_diagnostics)\n  File "./src/application/service/list_diagnostics_app_service.py", line 35, in __list_diagnostics\n    return self.__diagnostics_reader_repository.specify(specification=diagnostics_specification)\n  File "./src/infrastructure/persistence/clickhouse/repository/clickhouse_diagnostics_reader_repository.py", line 20, in specify\n    tuples = self.__session.execute(statement_string=specification)\n  File "./src/infrastructure/persistence/clickhouse/__init__.py", line 24, in execute\n    return self.session.execute(statement_string, with_column_types=with_column_types)\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 212, in execute\n    columnar=columnar\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 332, in process_ordinary_query\n    columnar=columnar)\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 81, in receive_result\n    return result.get_result()\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/result.py", line 48, in get_result\n    for packet in self.packet_generator:\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 93, in packet_generator\n    packet = self.receive_packet()\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 107, in receive_packet\n    packet = self.connection.receive_packet()\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 388, in receive_packet\n    packet.type = packet_type = read_varint(self.fin)\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/reader.py", line 30, in read_varint\n    i = f.read_one()\n  File "clickhouse_driver/bufferedreader.pyx", line 66, in clickhouse_driver.bufferedreader.BufferedReader.read_one\n  File "clickhouse_driver/bufferedreader.pyx", line 196, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer\nEOFError: Unexpected EOF while reading bytes\n', 'file': './src/user_interface/src/api_action.py', 'line': 25, 'name': 'EOFError'}, 'request': {'body': None, 'query': {'age_range_min': '0', 'age_range_max': '120', 'date_range_min': '2016-01-01', 'date_range_max': '2017-12-31', 'page': '1', 'per_page': '30', 'search_by': 'clinical_act'}}, 'message': 'Unexpected EOF while reading bytes'}
`

`
ERROR:root:{'exception': {'message': 'Traceback (most recent call last):\n  File "./src/user_interface/src/api_action.py", line 25, in handle\n    return self.execution()\n  File "./src/user_interface/action/api/v3/searches/list_diagnostics_api_action.py", line 19, in execution\n    query_response = self._service.execute(query_diagnostics=query_list_diagnostics)\n  File "./src/application/service/list_diagnostics_app_service.py", line 64, in execute\n    diagnostic_view_object_list = self.__list_diagnostics(query_diagnostics)\n  File "./src/application/service/list_diagnostics_app_service.py", line 35, in __list_diagnostics\n    return self.__diagnostics_reader_repository.specify(specification=diagnostics_specification)\n  File "./src/infrastructure/persistence/clickhouse/repository/clickhouse_diagnostics_reader_repository.py", line 20, in specify\n    tuples = self.__session.execute(statement_string=specification)\n  File "./src/infrastructure/persistence/clickhouse/__init__.py", line 24, in execute\n    return self.session.execute(statement_string, with_column_types=with_column_types)\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 194, in execute\n    self.connection.force_connect()\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 171, in force_connect\n    elif not self.ping():\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 381, in ping\n    return False\n  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__\n    next(self.gen)\n  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 530, in timeout_setter\n    self.socket.settimeout(old_timeout)\nOSError: [Errno 9] Bad file descriptor\n', 'file': './src/user_interface/src/api_action.py', 'line': 25, 'name': 'OSError'}, 'request': {'body': None, 'query': {'age_range_min': '0', 'age_range_max': '120', 'date_range_min': '2016-01-01', 'date_range_max': '2017-12-31', 'page': '1', 'per_page': '30', 'search_by': 'patient'}}, 'message': '[Errno 9] Bad file descriptor'}
`

In production the application is deployed using uwsgi with the config below:

```python
[uwsgi]
chdir = /manager-backend
master = true
module = wsgi:app
buffer-size = 65535
die-on-term = true
http = 0.0.0.0:80
vacuum = true
enable-threads = true
single-interpreter = true
processes = 2
threads = 2
```

Versions:

python 3.7.4
uWSGI: 2.0.18
os: alpine3.9
clickhouse driver: 0.1.0
clickhouse server: version 18.14.8 revision 54409

**Comment by xzkostyan** [comment]
I think the thing is in this line:

```
enable-threads = true
```

Client instance [is not thread-safe](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#async-and-multithreading).

**Comment by sperez4mba** [comment]
Thanks for your answer @xzkostyan 

Since I opened the issue I've been testing with no threads enabled in uwsgi and I haven't seen the `Unexpected EOF while reading bytes` error so far so it's possible that was the problem. I'll keep monitoring.

**Comment by xzkostyan** [comment]
Version 0.1.3 contains DB API 2.0 support. `Cursor` and `Connection` instances are thread-safe, so they can be used with this option.

But under the hood this thread-safety is implemented by using another instance of `Client` on each cursor. It's binary-protocol limitation: multiple queries can not be executed within one socket.
