### ISSUE TITLE
Question about output types

### ISSUE THREAD

**Issue by artbeglaryan** [mymarilyn/clickhouse-driver#124]
Is there a plan to have response on CSV/JSON/TSV format, without converting to python types?

I know that there are some workarounds right now by querying via requests and convert to whatever you need.

**Comment by xzkostyan** [comment]
Short answer is no.

Native protocol defines data transmission in binary form. When you query `SELECT * from system.numbers LIMIT 10 FORMAT CSV` from the server you have binary data on the wire between `clickhouse-client` and server. You can use tcpdump/wireshark to see this data. Actual data formatting takes place in client's side.

Client reads binary data, coverts it into C (in case of `clickhouse-client`) or Python (in case of `clickhouse-driver`) types and then formats data into CSV/JSON.

In case of HTTP protocol (when using `requests`/`curl`/etc.) ClickHouse server do corresponding serialization.

This can be done with post-procesing query results. There is example [in docs](https://clickhouse-driver.readthedocs.io/en/latest/misc.html#inserting-data-from-csv-file) with inserting data from csv file. You can use post-processor to convert data into appropriate output format.

**Comment by artbeglaryan** [comment]
That is what I'm doing now.

But in case if I need to convert  millions rows it takes bunch of time. CH binary->python objects->CSV/JSON/TSV. So maybe will be great to implement functionality to convert from binary to CSV/TSV/JSON without converting to python objects? Only for select. Will try to find time and implement by myself, if have free time and pull requests is appreciated :) Thanks

**Comment by xzkostyan** [comment]
You can take a look on [fork](https://github.com/Arturus/clickhouse-driver) with deserializing binary data direct into numpy/pandas dataframes. It's good for heavy data processing.

It will be good to have this feature with optional dependencies (numpy, pandas) in upstream project. 

I'd like to merge it, but this feature needs to be optional and well-tested.

**Comment by athre0z** [comment]
Merging numpy support in the main project would be beautiful!
