### ISSUE TITLE
Error on out file close: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#126]
I am trying to insert dataframe df_orig_del rows to the table with 
prod.execute("""insert into Cempresso.CempressoIssues values""", df_orig_del.values.tolist())
but after a while I get the error:

```
Error on out file close: [WinError 10053] An established connection was aborted by the software in your host machine
---------------------------------------------------------------------------
ConnectionAbortedError                    Traceback (most recent call last)
<ipython-input-15-69838faeba6a> in <module>
      1 # brisanje postojećih
----> 2 prod.execute("""insert into Cempresso.CempressoIssues values""", df_orig_del.values.tolist())

c:\users\zoran\dropbox\bulb\python\bulb\src\bulb\clickhouse.py in execute(self, sql, params, print_sql, report_time, head_tail_rows, rename_cols, execute_as_is, print_stats)
   1322         else:
   1323             self.last_insert_num_of_rows = self.__insert(sql, params=params, print_sql=print_sql,
-> 1324                                                          report_time=report_time)
   1325             self.last_sql = sql
   1326             return self.last_insert_num_of_rows

c:\users\zoran\dropbox\bulb\python\bulb\src\bulb\clickhouse.py in __insert(self, sql, params, print_sql, report_time)
   1487 
   1488         start_time = datetime.datetime.now()
-> 1489         self.__client.execute(sql, params=params)
   1490         end_time = datetime.datetime.now()
   1491 

~\Miniconda3\lib\site-packages\clickhouse_driver\client.py in execute(self, query, params, with_column_types, external_tables, query_id, settings, types_check, columnar)
    205                 rv = self.process_insert_query(
    206                     query, params, external_tables=external_tables,
--> 207                     query_id=query_id, types_check=types_check
    208                 )
    209             else:

~\Miniconda3\lib\site-packages\clickhouse_driver\client.py in process_insert_query(self, query_without_data, data, external_tables, query_id, types_check)
    356         sample_block = self.receive_sample_block()
    357         if sample_block:
--> 358             self.send_data(sample_block, data, types_check=types_check)
    359             packet = self.connection.receive_packet()
    360             if packet.exception:

~\Miniconda3\lib\site-packages\clickhouse_driver\client.py in send_data(self, sample_block, data, types_check)
    380             block = Block(sample_block.columns_with_types, chunk,
    381                           types_check=types_check)
--> 382             self.connection.send_data(block)
    383 
    384         # Empty block means end of data.

~\Miniconda3\lib\site-packages\clickhouse_driver\connection.py in send_data(self, block, table_name)
    479             write_binary_str(table_name, self.fout)
    480 
--> 481         self.block_out.write(block)
    482         self.block_out.reset()
    483         logger.debug('Block send time: %f', time() - start)

~\Miniconda3\lib\site-packages\clickhouse_driver\streams\native.py in write(self, block)
     41                              self.fout, types_check=block.types_check)
     42 
---> 43         self.finalize()
     44 
     45     def finalize(self):

~\Miniconda3\lib\site-packages\clickhouse_driver\streams\compressed.py in finalize(self)
     44         i = 0
     45         while i < compressed_size:
---> 46             self.raw_fout.write(compressed[i:i + block_size])
     47             i += block_size
     48 

~\Miniconda3\lib\socket.py in write(self, b)
    605         self._checkWritable()
    606         try:
--> 607             return self._sock.send(b)
    608         except error as e:
    609             # XXX what about EINTR?

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

**To Reproduce**
I can reproduce it at will. 
```
df_orig_del.shape
(768578, 43)
```

but I have noticed that if I am doing the same with less rows (let's say less than 10.000 rows), insert works.

**Expected behavior**

**Versions**

- clickhouse-driver         0.1.1            py37hfa6e2cd_0    conda-forge
- python                    3.7.4                h5263a28_0

**Comment by xzkostyan** [comment]
Can you provide code sample to reproduce the problem?

**Comment by ghuname** [comment]
There is nothing except insert statement I have described above.
I cannot provide data.

**Comment by Slach** [comment]
ghuname, could you dump sample of your data to CSV and provide it via clickhouse-obfuscator?
https://itnesweb.com/article/obfuscation-of-data-for-performance-tests

**Comment by ghuname** [comment]
I tried with:

`clickhouse-obfuscator --seed "$(head -c16 /dev/urandom | base64)" --input-format CSVWithNames --output-format CSVWithNames --structure 'session_id UInt32, session_start DateTime, session_end DateTime, session_duration_s UInt32, session_subject String, session_subject_info String, session_escalated String, session_timedout String, session_module String, session_principal String, session_principal_role String, domain_name String, domain_title String, agent_name String, agent_lname String, agent_fname String, stat_dimen_name String, stat_dimen_value String, issue_id UInt32, issue_severity UInt32, issue_status String, remedy_action_name String, issue_name String, issue_title String, issue_remedy_id UInt32, group_id UInt32, group_name String, group_title String, wf_detected_by_name String, wf_detected_by_title String, wf_resolved_by_name String, wf_resolved_by_title String, session_resolution String, issue_resolution String, technology String, issue_category String, issue_category2 String, longitude Float32, latitude Float32, inserted_on DateTime, inserted_on_day Date, session_start_day Date, Sign Int8' < df_orig_del.csv > df_orig_del_obfus.csv`

but the data in df_orig_del_obfus.csv is not obfuscated (enough).

**Comment by Slach** [comment]
@ghuname clickhouse-obfuscator required minimum 1000 rows in input file

**Comment by ghuname** [comment]
I gave to it 750k of rows.

**Comment by ghuname** [comment]
I cannot provide the data, because obfuscator is not doing good obfuscation.
I have exported data to csv and than used clickhouse-client to import it with no problems.

**Comment by xzkostyan** [comment]
@ghuname does turning off compression affects this issue?

**Comment by ghuname** [comment]
I don't have access to this server so I cannot confirm.
As i don't have access, I believe that we cannot progress this issue anymore.

**Comment by xzkostyan** [comment]
OK, I'm closing this issue.
