### ISSUE TITLE
Timezone is deleted from datetime instance.

### ISSUE THREAD

**Issue by konstantin-popov** [mymarilyn/clickhouse-driver#127]
When fetching values from column with type `DateTime`, the return `datetime` instance has no timezone (it is explicitly removed when the column type has no timezone set).
But it seems strange, because the integer returned from server is timestamp and represents particular epoch second, while the returned value actually depends on the server timezone setting in most cases. This was discussed in #98, but changed only for fields with timezone explicitly set. I may be missing something, but why are naive datetimes used?

**Comment by xzkostyan** [comment]
From ClickHouse docs https://clickhouse.yandex/docs/en/data_types/datetime/

> A moment of time is stored as Unix timestamp, independently of time zones and daylight savings. Additionally DateTime can store time zone, that affects how DateTime values are displayed in text format and how input strings are parsed for storage.

Why should we use timezone-aware datetime for DateTime columns with no timezone?

**Comment by konstantin-popov** [comment]
The point is that in CH DateTime column stores a certain moment of time (as stated in the docs in your citation). When the driver returns a naive datetime instance, there is now way to determine that actual moment stored in CH.
The timezone in column definition is only a hint for formatting values in clients, I suppose.

**Comment by xzkostyan** [comment]
Yes, you are right. But the same thing is applied to `clickhouse-client`. But responses from different tools should be predictable and consistent if tools share the same source. Are there another drivers that keep timezone in this case?

**Comment by konstantin-popov** [comment]
> But the same thing is applied to clickhouse-client
Do you mean the official cmd client? If so, it's output format is purely text-based AFAIK, and this is the case where column timezone should be respected.
Python driver returns python-objects which can be used in different ways, so losing data during deserialization is undesirable.

**Comment by xzkostyan** [comment]
> Do you mean the official cmd client? If so, it's output format is purely text-based AFAIK, and this is the case where column timezone should be respected.

Yes there is `use_client_time_zone` [setting](https://clickhouse.tech/docs/en/single/#usage-remarks) that allows use client's timezone instead of server.
