### ISSUE TITLE
Feature request: Extend columnar form to support NumPy / PyArrow arrays

### ISSUE THREAD

**Issue by healiseu** [mymarilyn/clickhouse-driver#128]
Hi Konstantin, I noticed that enabling the columnar parameter during query execution, clickhouse binary raw data are deserialized into python tuples. Wouldn't be great if you can **match numpy data types with ClickHouse data types and deserialize into numpy arrays** instead ?

As far as I understand there are two ways to do this, either turn python tuples into numpy arrays, if possible with zero copy, or do the transformation straight ahead on the binary data.

The bonus of this will be that another zero copy transformation of numpy arrays to pyarrow arrays can be easily done. This way we gain easily two significant advantages: 

* Use [pyarrow][1] for batch processing, table and pandas dataframe zero copy transformations, it's blazing fast and memory efficient.

*  it opens the sky for [arrow flight][2] protocol (gRPC based) which can be great for transferring data with high speed from remote servers.

I would also like to use columnar forms with numpy arrays for my project and I am offering testing.

[1]: https://arrow.apache.org/docs/python/index.html
[2]: https://arrow.apache.org/docs/format/Flight.html

**Comment by Slach** [comment]
also maybe https://github.com/Arturus/clickhouse-driver can be backported to official python driver?

**Comment by StashOfCode** [comment]
> also maybe https://github.com/Arturus/clickhouse-driver can be backported to official python driver?

Would be really awesome

**Comment by xzkostyan** [comment]
Yes, it will be good to have this feature with optional dependencies (numpy, pandas) in upstream project.

I'd like to merge it, but this feature needs to be optional and well-tested.

**Comment by StashOfCode** [comment]
@xzkostyan, maybe the author himself can help. Here's his telegram @asuilin i found on his website

**Comment by balaccord** [comment]
There's the somewhat tricky possibility here to use the Numpy fast reading feature just now and _almost_ in this module :)

I just described the one of the possible solutions as the issue for the another module and posted it to this repo by mistake, so closed it. The solution and the short test are in this closed issue: https://github.com/mymarilyn/clickhouse-driver/issues/132

Sure not the best but still usable workaround: use the two modules at once, this for all and outdated Artur's for the fast reading, but Artur's module should be patched then. Unfortunatelly, the both modules use the same naming logick. Or, probably, the module might be placed in some python's non-searchable path to be imported in nonstandard way, didn't test it. The patch works so why?

**Comment by healiseu** [comment]
@xzkostyan any plans to merge this numpy arrays feature in the near future? By the way a great alternative would be to support ClickHouse Arrow array columnar format. I made a cross-reference with a relevant issue I opened here at ClickHouse/ClickHouse#12284. That may also solve the problem of transferring fast large volume of structured data through the wire, i.e. ArrowStream format. I volunteer to test the new feature.

**Comment by xzkostyan** [comment]
NumPy support from https://github.com/Arturus/clickhouse-driver is ready for merging into master branch. This support will be optional and driver will work without `numpy` as usual.

```bash
pip install git+https://github.com/mymarilyn/clickhouse-driver@feature-numpy-support#egg=clickhouse-driver
```

Additional dependencies are `pandas` and `numpy`.

Supported types:

* Float32/64
* [U]Int8/16/32/64
* Date/DateTime(‘timezone’)/DateTime64(‘timezone’)
* String/FixedString(N)
* LowCardinality(T)

Numpy arrays are not used when reading nullable columns and columns of unsupported types.

Examples:

```python
client = Client('localhost', settings={'use_numpy': True}):
client.execute(
    'SELECT * FROM system.numbers LIMIT 10000',
    columnar=True
)
```

```python
client = Client('localhost', settings={'use_numpy': True}):
client.query_dataframe(' FROM table')
    'SELECT number AS x, (number + 100) AS y '
    'FROM system.numbers LIMIT 10000'
)
```

Looking for feedback.

**Comment by xzkostyan** [comment]
Branch feature-numpy-support was merged into master.

**Comment by xzkostyan** [comment]
Optional numpy arrays/pandas dataframes writing was also merged into master: https://github.com/mymarilyn/clickhouse-driver/commit/90a49c276d2134cdf886e106882cfe9f833ca9b5

**Comment by xzkostyan** [comment]
Should we close this issue since 0.2.0 version has numpy support?

**Comment by karatemir** [comment]
Does this mean that one can directly load data into a Cudf (Nvidia Rapids) dataframe on the GPU bypassing any intermediary pandas/numpy representation?

**Comment by xzkostyan** [comment]
I have no experience with Cudf. It's better just to give it a try.
