### ISSUE TITLE
SQL injections?

### ISSUE THREAD

**Issue by kdubovikov** [mymarilyn/clickhouse-driver#13]
Hi!

Thanks for this great library. I was thinking whether it has any protection against SQL injection? https://github.com/mymarilyn/clickhouse-driver/blob/master/src/util/escape.py does not seem to have any checks for injected queries.

**Comment by xzkostyan** [comment]
Hi!

Can you provide some query with parameters causing SQL injection?

**Comment by kdubovikov** [comment]
Thanks for the response. Will think on it.

**Comment by xzkostyan** [comment]
@kdubovikov

I've tried to make SQL injections but all my attempts are failed. It seem that `'` escaping with `%(x)s` substitution is good enough.

**Comment by kdubovikov** [comment]
Thanks! Hope so.
