### ISSUE TITLE
Are we tz aware or not?

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#134]
Please look at this example:

```
node = Client(host='localhost', port=8123, database='default', compression=True)

node.execute("create table dummy (dtime DateTime, val Int8) engine Memory")
node.execute('insert into dummy (dtime, val) values (now(), 1)')
node.execute('select * from dummy')
```

[(datetime.datetime(2020, 3, 26, 12, 42, 4), 1)]

`node.execute('select toStartOfMinute(dtime), val from dummy')`

[(datetime.datetime(2020, 3, 26, 12, 42, tzinfo=<DstTzInfo 'Europe/Rome' CET+1:00:00 STD>), 1)]

As you can see, default behavior is to get not tz aware datetime, but if we use toStartOf... functions, than result is tz aware.

Are we tz aware or not?
We should be consistent here.

**Versions**
clickhouse_driver 0.1.3
python 3.7.4 (windows 10 64)
ClickHouse server version 19.16.3 revision 54427

**Comment by xzkostyan** [comment]
There is DateTime type with timezone `DateTime(T)` and without `DateTime`.

DateTime with timezone `DateTime(T)` is aware (with timezone) datetime in python.
DateTime without timezone `DateTime` is naive (without timezone) datetime in python.

Let's take a look what DateTime we are dealing in `clickhouse-client`:

```sql
:) select * from dummy FORMAT TabSeparatedWithNamesAndTypes

SELECT *
FROM dummy
FORMAT TabSeparatedWithNamesAndTypes

dtime	val
DateTime	Int8
2020-03-26 20:57:16	1

1 rows in set. Elapsed: 0.087 sec. 
```

```sql
:) select toStartOfMinute(dtime), val from dummy FORMAT TabSeparatedWithNamesAndTypes

SELECT 
    toStartOfMinute(dtime), 
    val
FROM dummy
FORMAT TabSeparatedWithNamesAndTypes

toStartOfMinute(dtime)	val
DateTime(\'Europe/Moscow\')	Int8
2020-03-26 20:57:00	1

1 rows in set. Elapsed: 0.006 sec. 
```

That's it: `toStartOfMinute` function return DateTime with timezone `DateTime(T)`.

**Comment by ghuname** [comment]
You are right. I thought that the problem is on our side, but as you have proven it is on Clickhouse side.
I think it is not a good idea to mix data types. 
I will ask Clickhouse team about this subject.

Please keep this issue open for few days.

Regards.

**Comment by ghuname** [comment]
I have found a solution after I have read https://github.com/ClickHouse/ClickHouse/issues/505
Looks like toStartOf... functions have an undocumented parameter (on official pages https://clickhouse.tech/docs/en/query_language/functions/date_time_functions/#tostartofminute) "time zone". 

I played with this parameter, and I have found that if you set second parameter as empty string, we can get time with no time zone.

Clickhouse client:

```
:) select dtime, toStartOfMinute(dtime, 'UTC') from dummy

SELECT 
    dtime, 
    toStartOfMinute(dtime, 'UTC')
FROM dummy

┌───────────────dtime─┬─toStartOfMinute(dtime, 'UTC')─┐
│ 2020-03-27 08:48:43 │           2020-03-27 07:48:00 │
└─────────────────────┴───────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

 :)
```

clickhouse_driver:

`node.execute("""select dtime, toStartOfMinute(dtime, '') from dummy""")`

[(datetime.datetime(2020, 3, 27, 8, 58, 23),
  datetime.datetime(2020, 3, 27, 8, 58))]

So, the solution is to use empty string for second parameter if you want time with no time zone.

Thank you for pointing me in the right direction.
You can close this issue.

Best regards.

**Comment by ghuname** [comment]
It is good to know: https://github.com/ClickHouse/ClickHouse/issues/505#issuecomment-280681017
