### ISSUE TITLE
After install clickhouse-driver(0.1.3) from source code， import error

### ISSUE THREAD

**Issue by linzhi** [mymarilyn/clickhouse-driver#137]
**Describe the bug**
from clickhouse_driver import Client
ModuleNotFoundError: No module named 'clickhouse_driver.varint'

**To Reproduce**
Minimal piece of Python code that reproduces the problem.

**Expected behavior**

**Versions**

- Version of package with the problem.
- 3.7.0.

**Comment by t-tien** [comment]
@xzkostyan 
I'm facing with same problem when I upgrade clickhouse driver version from 0.0.20  to 0.2.0. 

My code: 
```
from variables import aws as config
from clickhouse_driver import Client

host = config["clickhouse"]["host"]
port = config["clickhouse"]["port"]
user = config["clickhouse"]["user"]
password = config["clickhouse"]["password"]
database = config["clickhouse"]["database"]

client = Client(host, port=port, database=database, user=user, password=password)


def execute(query):
    return client.execute(query)


if __name__ == '__main__':
    execute("SELECT * FROM my_table WHERE date = today()")

```

And when I run code above, i received this response without stack trace: 
```
"errorMessage": "Unable to import module 'main': No module named 'clickhouse_driver.varint'",
"errorType": "Runtime.ImportModuleError",
"stackTrace": []
```

If I downgrade version to 0.0.20, every thing working fine, but what happened to 0.2.0?

**Comment by xzkostyan** [comment]
@t-tien what OS do you use? Do you install from wheels/from source? Can you provide `pip install` log?

In 0.2.0 was added numpy support for example: https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md

You can also try install latest master https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github.
