### ISSUE TITLE
Possible to send custom headers with requests / queries?

### ISSUE THREAD

**Issue by pjatx** [mymarilyn/clickhouse-driver#143]
Is it possible to alter the code a bit to pass through a custom http header? I work in an environment where that's necessary to get through to our clickhouse instance. 

I've got it working via the Clickhouse CLI tool, but would love some direction on how I might be able to achieve the same in this tool as I'd like to script some queries. Any help / guidance would be really appreciated!

**Comment by xzkostyan** [comment]
Hi.

This package uses native (TCP) protocol for communication with server. You can [pass different settings](https://clickhouse-driver.readthedocs.io/en/latest/features.html#settings) with the query. For communication over HTTP you should use pure `requests` or another wrappers on top of it.

What the original problem you're dealing with?

**Comment by pjatx** [comment]
@xzkostyan 

Ah, that makes sense. I ended up just wrapping my calls in the requests library as you outlined above and seems to be working just fine : ) 

At work, we need to generate an authentication token and pass it through as a cookie header to access our clickhouse server. I'm needing to iterate through some things and call clickhouse as part of a script. Super new to working with clickhouse so it took me a minute to figure out how all of this worked. 

Thanks for the quick reply though!
