### ISSUE TITLE
Unquotting special characters

### ISSUE THREAD

**Issue by VorontsovAlex** [mymarilyn/clickhouse-driver#146]
Hi, 

Creating a Client object using the function is shown below produces an error when either username or password contains at least one of the following characters: 
`@/:`
https://github.com/mymarilyn/clickhouse-driver/blob/1069842d6fb16d7871f272214e1e4bc9384355ef/clickhouse_driver/client.py#L428
I suggest using unquote function for them.

**Comment by xzkostyan** [comment]
Hi.

Fixed in master: https://github.com/mymarilyn/clickhouse-driver/commit/d2be10d4dddc754d36ec1f5ac60614ca6870f93b.
