### ISSUE TITLE
IterQueryResult

### ISSUE THREAD

**Issue by burrito-dev** [mymarilyn/clickhouse-driver#147]
Hello there!

There is no way to get IterQueryResult object. I think it would be nice to get this object in client.execute_iter(proxy=False) or something like that to have an opportunity to iterate over rows. 

I have a lot of problems with that, because my app's logic connected with max_block_size, and i had to create cringe hacks over execute_iter

**Comment by xzkostyan** [comment]
Hi.

What's the use case for this feature? `IterQueryResult` just provides iteration over returned data by chunks.

**Comment by burrito-dev** [comment]
I have an app, that sends each query result row as single request to other service asynchronously, for saving memory purposes the code look like this
    tasks_to_resend = []
    data_to_send = []
    rows_num = 0
    query_result = await client.execute_iter(query, settings=query_settings)
    async for row in query_result:
        rows_num += 1
        data_to_send.append(DataToSend(*row))
        if rows_num // settings.CLICKHOUSE_MAX_BLOCK_SIZE == 0:
            async with aiohttp.ClientSession(connector=conn) as session:
                await asyncio.gather(*[send_data(session, row) for row in data_to_send])
            data_to_send.clear()

    if data_to_send:
        async with aiohttp.ClientSession(connector=conn) as session:
            await asyncio.gather(*[send_data(session, row) for row in data_to_send])
        data_to_send.clear()

**Comment by burrito-dev** [comment]
I have an app, that sends each row of query result asynchronous to other service.
The size of query result is unpredictable, and for memory saving purpose, the code look like this    

    query_settings = {'max_block_size': settings.CLICKHOUSE_MAX_BLOCK_SIZE}
    data_to_send = []
    rows_num = 0
    query_result = await client.execute_iter(query, settings=query_settings)
    async for row in query_result:
        rows_num += 1
        data_to_send.append(DataToSend(*row))
        if rows_num // settings.CLICKHOUSE_MAX_BLOCK_SIZE == 0:
            async with aiohttp.ClientSession(connector=conn) as session:
                await asyncio.gather(*[send_data(session, row) for row in data_to_send])
            data_to_send.clear()

    if data_to_send:
        async with aiohttp.ClientSession(connector=conn) as session:
            await asyncio.gather(*[send_data(session, row) async for row in data_to_send])
        data_to_send.clear()

But if I could get `IterQueryResult`, it would look like this:

    query_result = await client.execute_iter(query, settings=query_settings, proxy=False)
    async for rows in query_result:
        async with aiohttp.ClientSession(connector=conn) as session:
            await asyncio.gather(*[send_data(session, DataToSend(*row)) for row in rows])

**Comment by xzkostyan** [comment]
It seems that you need something like [aiostream.stream.chunks](https://aiostream.readthedocs.io/en/latest/operators.html#aiostream.stream.chunks) for chunking. Exposing internal `IterQueryResult` is not good idea.

**Comment by burrito-dev** [comment]
Thanks a lot! It was very useful
