### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by venkateshchittinidi** [mymarilyn/clickhouse-driver#150]
https://github.com/mymarilyn/clickhouse-driver/blob/3283aa8704ddcb0a39db7f71582a6b1ca003018f/clickhouse_driver/connection.py#L256

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/connection.py", line 256, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/connection.py", line 226, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/connection.py", line 202, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by xzkostyan** [comment]
It's not possible to reproduce the problem with provided data.

Could you provide more information? host, port, etc.

**Comment by IuliiaSaveleva** [comment]
I'm facing the problem connecting from python script to existing database. Of course it is impossible to provide connection information as it is confidential, but may be you have found the way to deal with that problem:
Failed to connect to ...
...
socket.gaierror: [Errno -2] Name or service not known
...
clickhouse_driver.dbapi.errors.OperationalError: Code: 210. Name or service not known (None:None)

I'm using the same host, port, user name and password as when I enter the database from TABIX

Please, help :)

**Comment by xzkostyan** [comment]
@IuliiaSaveleva AFAIK Tabix uses 8123 port.

Same issue: https://github.com/mymarilyn/clickhouse-driver/issues/84#issuecomment-482938969
