### ISSUE TITLE
dictionary substitution for strings (quote problem)

### ISSUE THREAD

**Issue by robsunch** [mymarilyn/clickhouse-driver#151]
**Description**
This is probably not a bug, but I don't know where is a good place to find an answer. Sorry for crowding the space here. I am also new to clickhouse and python, so please forgive my ignorance.

I want to loop over a list of table names. For example, 

`client.execute('SELECT count() FROM default.table_a')`
`client.execute('SELECT count() FROM default.table_b')`
`client.execute('SELECT count() FROM default.table_c')`

I tried the following dictionary substitution:
`for x in ['a','b','c']:
  client.execute('SELECT count() FROM default.table_%(table)s', {'table': x})
`
This doesn't work and returns an error:

> DB::Exception: Syntax error: failed at position 43: 'a'. Expected one of: SAMPLE, LIMIT, WHERE, INNER, AS, HAVING, INTO OUTFILE, GROUP BY, identifier, LEFT ARRAY JOIN, PREWHERE, JOIN, alias, ORDER BY, array join, SETTINGS, UNION ALL, ARRAY JOIN, FORMAT, Dot, WITH, FINAL, token, table, table function, subquery or list of joined tables. Stack trace:

I think the problem is that the dictionary substitution keeps the quotes. Is there a way to get rid of the quotes? It seems that all the examples in the documentation are trying to inject numbers rather than strings.

**Versions**

- Python 3.8.3
- clickhouse-driver 0.1.4

**Comment by xzkostyan** [comment]
> I think the problem is that the dictionary substitution keeps the quotes.

Yep, string parameters are always wrapped with quotes.

> Is there a way to get rid of the quotes?

* You can wrap whole `table_x` with quotes `client.execute('SELECT count() FROM default.%(table)s', {'table': 'table_' + x})`. `SELECT count() FROM default."table_a"` is valid query.
* Or if you getting parameters from trusted source (e.g. not from user input for example) you can use `client.execute('SELECT count() FROM default.table_{}.'format(x))` for making query.

**Comment by robsunch** [comment]
@xzkostyan Many thanks for the reply (and the great work on clickhouse-driver)! 

Before seeing your answer, I used the following solutions:
```
client.execute(f'SELECT count() FROM default.table_{x}')
client.execute('SELECT count() FROM default.table_' + x)
```

**Comment by brunlid** [comment]
@xzkostyan `client.execute('SELECT COUNT() FROM db_name."tbl_name"')` is valid as you say but `client.execute('SELECT COUNT() FROM db_name.%(tbl_name)s', {'tbl_name': 'tbl_name'})` throws Exception: Syntax error. Please advise. Thank you
