### ISSUE TITLE
Feature Request: add a non-pep method to cursor execute for specifying query_id

### ISSUE THREAD

**Issue by toddyocum** [mymarilyn/clickhouse-driver#152]
It would be nice if the dbapi version had a way to specify the query_id that should be used for the query, maybe something similar to the set_settings(), like set_query_id()

**Comment by xzkostyan** [comment]
Added to latest master: https://github.com/mymarilyn/clickhouse-driver/commit/1ef915b31b0daaf064795c8c021164221c5d6d4e
