### ISSUE TITLE
UnknownPacketFromServerError: Code: 100. Unknown packet 268435455 from server None:None

### ISSUE THREAD

**Issue by Jackyqs** [mymarilyn/clickhouse-driver#155]
**Describe the bug**
UnknownPacketFromServerError: Code: 100. Unknown packet 268435455 from server None:None
**To Reproduce**
Minimal piece of Python code that reproduces the problem.
<ipython-input-1-155bd51eb390> in SJTQ()
    166         rows = client.execute_iter("select * from ksdb.Insur_log where like(title,'"+ query_str +"')",settings=settings)
    167         print(datetime.datetime.now(),query_str)
--> 168         for row in rows:
    169             line = {}
    170             #模板提取

c:\python38\lib\site-packages\clickhouse_driver\client.py in iter_receive_result(self, with_column_types)
     92         gen = self.packet_generator()
     93 
---> 94         for rows in IterQueryResult(gen, with_column_types=with_column_types):
     95             for row in rows:
     96                 yield row

c:\python38\lib\site-packages\clickhouse_driver\result.py in next(self)
    120 
    121     def next(self):
--> 122         packet = next(self.packet_generator)
    123         block = getattr(packet, 'block', None)
    124         if block is None:

c:\python38\lib\site-packages\clickhouse_driver\client.py in packet_generator(self)
     99         while True:
    100             try:
--> 101                 packet = self.receive_packet()
    102                 if not packet:
    103                     break

c:\python38\lib\site-packages\clickhouse_driver\client.py in receive_packet(self)
    113 
    114     def receive_packet(self):
--> 115         packet = self.connection.receive_packet()
    116 
    117         if packet.type == ServerPacketTypes.EXCEPTION:

c:\python38\lib\site-packages\clickhouse_driver\connection.py in receive_packet(self)
    441         else:
    442             self.disconnect()
--> 443             raise errors.UnknownPacketFromServerError(
    444                 'Unknown packet {} from server {}'.format(
    445                     packet_type, self.get_description()

UnknownPacketFromServerError: Code: 100. Unknown packet 268435455 from server None:None
**Expected behavior**

**Versions**
- Version of package with the problem. 0.1.4
- Python version. 3.8

**Comment by xzkostyan** [comment]
It's not possible to reproduce the problem with provided data.

Could you provide more specific DDL for table creation?

**Comment by Jackyqs** [comment]
create table ksdb.Insur_log(
mobile String,
userid String,
logtime Date,
yyyymm String,
title String)
ENGINE = ReplacingMergeTree() PARTITION BY toYYYYMM(logtime) 
ORDER BY (mobile,userid,logtime,title)

**Comment by Jackyqs** [comment]
data count about 1.7 billion

**Comment by Jackyqs** [comment]
if no with settings option(settings = {'max_block_size': 100000}) there is no this error.
like this:
rows = client.execute_iter("select * from ksdb.Insur_log where like(title,'"+ query_str +"')")

**Comment by Jackyqs** [comment]
if no with settings option(settings = {'max_block_size': 100000})
client.execute_iter == client.execute
large memory footprint
