### ISSUE TITLE
Question: client compression

### ISSUE THREAD

**Issue by cemremengu** [mymarilyn/clickhouse-driver#162]
First of all thank you for your hard work. I am new to clickhouse and was just curious about the `compression` option inside the client.

`client = Client('localhost', compression=True)`

Is this for client compressing the data when sending to `clickhouse` or for enabling the compression on the database side? What exactly is the purpose?

**Comment by xzkostyan** [comment]
Hi.

It's a good question about ClickHouse internals. [This client option](https://clickhouse-driver.readthedocs.io/en/latest/api.html#connection) configures block compression algorithm used for network communication.

Server decompresses data block-by-block when you read the data from ClickHouse with `compression=False` and (re)compress it if you're using LZ4 for network communication and ZSTD in data storage. In other words server on `SELECT` queries:
* read data from disk;
* decompress it;
* [optionally compress data](https://github.com/ClickHouse/ClickHouse/blob/20.8/src/Client/Connection.cpp#L440) for sending over network.

I guess the server does the same things for data storing when you insert data into ClickHouse. Anyway, background merges will merge and store data with compression defined in ClickHouse server's config.

So, there can be different compressions for:
* data storage (ClickHouse server config);
* network communication (client setting).

Also, there is a English telegram chat about ClickHouse: https://t.me/clickhouse_en.

**Comment by cemremengu** [comment]
@xzkostyan thank you for the detailed answer and tips!

**Comment by netomenoci** [comment]
Thanks @xzkostyan!
1 -  Regarding Writing: Is there a way to compress data on the client side, ie, before writing it to the server? it seems to me that the insert_dataframe method does not compress it before sending (my table is compressed to zstd).

2 - Regarding Reading : Is there a way to avoid the decompression on the server side? For example, if I make a query SELECT * , there is no filter or aggregation happening, so I would imagine it should be theoretically possible to send the compressed data directly (that will be decompressed by the client)?
