### ISSUE TITLE
Add support for ssl connection with SNI

### ISSUE THREAD

**Issue by UnamedRus** [mymarilyn/clickhouse-driver#172]
**Describe the bug**
It looks like that driver doesn't support SNI, so it can't connect to clickhouse server behind proxy with SNI.

**To Reproduce**
https://docs.python.org/3/library/ssl.html

> Since Python 3.2 and 2.7.9, it is recommended to use the SSLContext.wrap_socket() of an SSLContext instance to wrap sockets as SSLSocket objects. The helper functions create_default_context() returns a new context with secure default settings. The old ssl.wrap_socket() function is deprecated since it is both inefficient and has no support for server name indication (SNI) and hostname matching.

https://github.com/mymarilyn/clickhouse-driver/blob/d76f38caf16abcb9259947cee0bb8f9d083f9e9d/clickhouse_driver/connection.py#L225

**Comment by xzkostyan** [comment]
Hi.

[Fix](https://github.com/mymarilyn/clickhouse-driver/commit/08b63abe266af9e858f63d752ec3419bae9bbea0) was merged into master branch.
