### ISSUE TITLE
Documentation refers to the not released yet version

### ISSUE THREAD

**Issue by vialorn** [mymarilyn/clickhouse-driver#174]
[It is stated](https://clickhouse-driver.readthedocs.io/en/latest/features.html#reading-into-numpy-arrays): Starting from version **0.1.6** package can return columns as NumPy arrays.
But the latest package version here on GitHub is just **0.1.5**.
I'm confused. Does documentation refer to a future release?

**Comment by xzkostyan** [comment]
Yes, latest documentation refers to unreleased 0.1.6. This version corresponds master branch now. You can install 0.1.6 [directly from github](https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github).
