### ISSUE TITLE
python connect clickhouse use http 8123

### ISSUE THREAD

**Issue by JosonQian** [mymarilyn/clickhouse-driver#176]
Firlst,my english is low,but i have a question about clickhouse_driver,I want to use nginx proxy clickhouse, now i facing SocketTimeoutError: Code: 209. None.
config is "client2 = Client(host=clickhouse_host_sq,port='8123',user=clickhouse_user,database=clickhouse_database, password=clickhouse_pwd)"
I want to use http proxy,so i how to did it?

**Comment by xzkostyan** [comment]
Hi.

This package uses nvative protocol with port 9000 for data communication. Server uses port 8123 for HTTP communication. 

Consider using another libraries or pure `requests` for working with http-proxies.

**Comment by JosonQian** [comment]
Do you have any other Python packages that can connect to the port 8123 of the Clickhouse，thanks！

**Comment by xzkostyan** [comment]
You can use [requests](https://requests.readthedocs.io/en/master/) package.

```python
import requests

requests.get('http://localhost:8123/....')
```
