### ISSUE TITLE
how to get the thread_id?

### ISSUE THREAD

**Issue by Fanduzi** [mymarilyn/clickhouse-driver#178]
Hi, How to get thread_id?
![image](https://user-images.githubusercontent.com/24428128/102595692-fea0b200-4152-11eb-9619-5d5f1dc95f0c.png)

**Comment by xzkostyan** [comment]
`select thread_ids from system.processes`

**Comment by Fanduzi** [comment]
> `select thread_ids from system.processes`
```
I mean like pymysql
cnx = pymysql.connect(**cfg)
thread_id = cnx.thread_id()
```
is there a way thad clickhouse_driver can do that?

**Comment by xzkostyan** [comment]
Thread id is not transmitted during communication between client and server. Therefore client doesn't know anything about threads.

**Comment by Fanduzi** [comment]
> Thread id is not transmitted during communication between client and server. Therefore client doesn't know anything about threads.

thank you
