### ISSUE TITLE
How to read Nullable(Float64) column with Numpy & columnar mode ?

### ISSUE THREAD

**Issue by vialorn** [mymarilyn/clickhouse-driver#181]
Hi,
Numpy can work with `None` / `nan` values within arrays.
Pandas `DataFrame.from_records` method also works well with Nullable columns.
Unfortunately, when I try to use `query_dataframe` with a query returning Nullable(Float64) columns, I got next exception:
```
UnknownTypeError('Unknown type Nullable(Float64)')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/numpy/service.py", line 76, in get_numpy_column_by_spec
    cls = column_by_type[spec]
KeyError: 'Nullable(Float64)'
```
I looked at the `columns/numpy/service.py` and there are commented lines
* in the import section  
  ```python
  # from .nullablecolumn import create_nullable_column
  ```
* in the `get_numpy_column_by_spec` method
  ```python
  # elif spec.startswith('Nullable'):`
  #     return create_nullable_column(spec, create_column_with_options)
  ```

The question is - is there a way to use Numpy & columnar mode with Nullable columns?

**Comment by vialorn** [comment]
Okay, there written "NumPy arrays are not used when reading nullable columns and columns of unsupported types." So it obviously isn't a bug. But is there a way to support nullable columns? I guess CH returns some nulls-map alongside column actual data and it is needed to rewrite null-marked cells with `numpy.nan` value.

**Comment by xzkostyan** [comment]
> But is there a way to support nullable columns?

Driver should fall back to generic reader. But, it seems that Nullable columns don't fall back from `numpy` reader to generic right now.

`numpy.nan` is acceptable for float columns. And what about Int/Date and other columns? How should pure `numpy` arrays handle `None` values? It seems that we should always return pandas DataFrame, not list of `numpy.array`s.

**Comment by vialorn** [comment]
Well, in my case, there are only non-nullable `UInt64` and `Nullable(Float64)` columns.
As far as I dig source code, `query_dataframe` reads a set on `numpy.array`s, and builds `DataFrame` from them.
It would be nice to have `Nullable(Float64)` supported.
I'm not a Python guru so far, but not a novice neither. May I help?

**Comment by hackaholic** [comment]
+1
Seeing the same issue for Nullable(T) while inserting using insert_dataframe
*** clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type Nullable(UInt32)

**Comment by hackaholic** [comment]
I can see here https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/columns/numpy/service.py
at line number 63, 64 is commented out?
Any reason for that?

**Comment by xzkostyan** [comment]
Nullable columns support for NumPy was merged into master.
