### ISSUE TITLE
How to add many conditions to requests?

### ISSUE THREAD

**Issue by demetranadya** [mymarilyn/clickhouse-driver#182]
Hello!

Do you know how to add many condition to request?

For example, I don't know keys from my dict and how huge dict.
But I need add that dict to condition WHERE.
Something like this.
res = " AND ".join([r'%s=\%\(%s\)s' % (i[0], i[1]) for i in get_dict.items()])
How to change to correct syntax?

**Comment by xzkostyan** [comment]
Hi.

Every parameter should have it's own placeholder for proper escaping.

You can enumerate your dict for example and add `WHERE %(param_1)s = %(param_2)s AND ...`. Or you can use own formatting at your own risk.
