### ISSUE TITLE
insert_dataframe inserts wrong values for large integers

### ISSUE THREAD

**Issue by hombit** [mymarilyn/clickhouse-driver#187]
**Describe the bug**
`insert_dataframe` inserts wrong large integer values. Probably it is caused by the current implementation which implicitly converts DataFrame values to floats via `transpose()` method and then these floats are casted to integers by ClickHouse itself. See `DataFrame.transpose` docs which say 
> Transposing a DataFrame with mixed dtypes will result in a homogeneous DataFrame with the `object` dtype.

Which means that if you transpose heterogeneous DataFrame, for example with one float column and one integer column, it will output float homogeneous DataFrame

**To Reproduce**
```python
client = Client('localhost', settings={'use_numpy': True})
client.execute('CREATE TABLE tmp (x UInt64, y Float64) Engine = MergeTree ORDER BY x')
client.insert_dataframe(
    'INSERT INTO tmp VALUES',
    pd.DataFrame(dict(
        x=np.array([607985949711794175, 607985949762125823], dtype=np.uint64),
        y=[1.0, 2.0]
    ))
)
print(client.execute('SELECT x FROM table', columnar=True))
```

```
[array([607985949711794176, 607985949762125824], dtype=uint64)]
```

**Expected behavior**
Values are inserted as is

**Versions**

- Version of package with the problem. 0.2.0
- Python version. 3.8.6
- Clickhouse version 20.12.4.1

**Comment by xzkostyan** [comment]
`transpose` option is completely removed from `insert_dataframe` method. Now dataframe should be inserted as is without any transformations. Boxing to objects was also speed ineffective.

This is fixed in latest master: https://github.com/mymarilyn/clickhouse-driver/commit/f1b56bb83fd585d39e786235e62f841501452ce2.
