### ISSUE TITLE
Decimal type insert incorrectly ( solved )

### ISSUE THREAD

**Issue by fengbinddr** [mymarilyn/clickhouse-driver#192]
**my environment:**
**code:**
`from clickhouse_driver import Client
client = Client(host='192.168.4.167', port='9000', user='default', password='123456', )
k = ''' INSERT INTO default.aaa VALUES '''
v_data = [(12, 1.66), (13, 1.77), (14, 1.15), (15, 1.78), (17, 1.59)]
client.execute(k, v_data, settings={'max_query_size': 2621440})`

**sql DDL:**
`CREATE TABLE default.aaa (
`id` Int32,
 `val` Decimal(18, 2)
) ENGINE = Memory;`

**result**
12	1.65
13	1.77
14	1.14
15	1.78
17	1.58

**I solved**
clickhouse_driver\columns\decimalcolumn.py
`No.58    items[i] = int(Decimal(item) * scale)  >>>   items[i] = int(Decimal(str(item)) * scale) `

**Comment by xzkostyan** [comment]
Thanks. Fixed in master: https://github.com/mymarilyn/clickhouse-driver/commit/0d607dfbefd9118df36313a6dd56dcd1dfad798f
