### ISSUE TITLE
Add support to release aarch64 wheels 

### ISSUE THREAD

**Issue by odidev** [mymarilyn/clickhouse-driver#195]
Problem
---------
On aarch64, pip install clickhouse-driver builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install clickhouse-driver should download the wheels from pypi

@xzkostyan , please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by xzkostyan** [comment]
Could you try wheels in archive?
[wheels.tar.gz](https://github.com/mymarilyn/clickhouse-driver/files/6093628/wheels.tar.gz)

**Comment by odidev** [comment]
@xzkostyan, thanks for your response. I tried installing the wheels provided by you on linux aarch64 machine and I am able to install it successfully. Please have a look:
_.env) [root@cc9f834ca180 ~]# uname -m
aarch64
(.env) [root@cc9f834ca180 ~]# pip install clickhouse_driver-0.2.0-cp36-cp36m-manylinux2014_aarch64.whl
Processing ./clickhouse_driver-0.2.0-cp36-cp36m-manylinux2014_aarch64.whl
Collecting tzlocal<3.0
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting pytz
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, tzlocal, clickhouse-driver
Successfully installed clickhouse-driver-0.2.0 pytz-2021.1 tzlocal-2.1
(.env) [root@cc9f834ca180 ~]#_

I also verified the artifacts, it looked to be containing aarch64 specific libraries. Please have a look:
_[root@cc9f834ca180 ~]# find clickhouse_driver -name "*.so"
clickhouse_driver/varint.cpython-36m-aarch64-linux-gnu.so
clickhouse_driver/bufferedwriter.cpython-36m-aarch64-linux-gnu.so
clickhouse_driver/bufferedreader.cpython-36m-aarch64-linux-gnu.so
[root@cc9f834ca180 ~]# file clickhouse_driver/bufferedwriter.cpython-36m-aarch64-linux-gnu.so
clickhouse_driver/bufferedwriter.cpython-36m-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=47f2cd4b4311e6617471ee7b27a593589bb955c2, not stripped
[root@cc9f834ca180 ~]# file clickhouse_driver/bufferedreader.cpython-36m-aarch64-linux-gnu.so
clickhouse_driver/bufferedreader.cpython-36m-aarch64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=17c5af173eb1d46ee01cb951802dfddfda68c10b, not stripped
[root@cc9f834ca180 ~]#_

**Comment by xzkostyan** [comment]
Do you need wheels for particular version before new release?

**Comment by odidev** [comment]
@xzkostyan, thanks for merging the related PR #197. _It will be good if you release aarch64 wheel at least for python3.6_. 
Will you be facing any issues in release aarch64 wheels for python versions >= 3.6 with the current release tag? If somehow, it can't be done, can you please let me know when the next release is scheduled?

**Comment by xzkostyan** [comment]
Wheels for 0.2.0 are published: https://pypi.org/project/clickhouse-driver/0.2.0/#files

**Comment by xzkostyan** [comment]
@odidev should we close issue?

**Comment by odidev** [comment]
@xzkostyan yes, this issue can be closed. Thanks for releasing the aarch64 wheels.
