### ISSUE TITLE
`INSERT ... VALUES` query parametrization

### ISSUE THREAD

**Issue by kuraga** [mymarilyn/clickhouse-driver#198]
Good day!

Is there a correct way to parameterized queries (to avoid SQL injections) in case of `INSERT ... VALUES` (and enumerating columns)?

Thanks!

**Comment by vialorn** [comment]
@kuraga , may You provide an example of SQL injection for ClickHouse?
As far as I know, ClickHouse supports neither multi-statement nor DML subqueries.
And in the case of `INSERT ... VALUES` [with `params`](https://clickhouse-driver.readthedocs.io/en/latest/api.html#clickhouse_driver.Client.execute), I see no way to injection.

**Comment by kuraga** [comment]
@vialorn , я имею ввиду вставку переменных в запрос в стиле printf: https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html, третий блок кода. Просто хочется понять, можно ли так с `INSERT INTO ... VALUES`. Ведь там мало того, что второй параметр под другое занят, еще и интересно, можно ли список колонок (заранее неизвестной длины) так вставлять.

**Comment by xzkostyan** [comment]
@kuraga `INSERT INTO ... VALUES` не рекомендуется использовать с [inline-подстановкой параметров](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#inserting-data), потому что сервер, кажется, не будет использовать потоковый парсер для разбора SQL-запроса. Но даже если отбросить этот факт и послать `INSERT INTO ... VALUES` с %s-параметрами, то они будут [заэксейплены](https://github.com/mymarilyn/clickhouse-driver/blob/772bfd735c92f2dd64f6fcdf743c5c6115abec44/clickhouse_driver/client.py#L430).

**Comment by kuraga** [comment]
@xzkostyan , спасибо! А list переменных ( например, список колонок) можно инлайнить?

**Comment by xzkostyan** [comment]
Можно пример? Я не до конца понял что именно хочется.

**Comment by kuraga** [comment]
А нет, список колонок вообще никто не экранирует, очевидно. Спасибо!
