### ISSUE TITLE
Set a query ID

### ISSUE THREAD

**Issue by elrik75** [mymarilyn/clickhouse-driver#2]
Clickhouse allows to set an ID on queries, you can see this IDs with a:
```
select query_id from system.processes;
```
this is useful when you want to cancel a query from an external process as explain here: https://stackoverflow.com/questions/40546983/how-to-kill-a-process-query-in-clickhouse

I propose that the `connection.send_query()` method accepts a string argument to name the query. It could be used in `client.process_*_query()` functions and `execute()` as an optional argument:

```
import uuid
c = client('server')
query_id = str(uuid.uuid4())
c.execute("select something", queryid=query_id)
```

**Comment by xzkostyan** [comment]
Hi!

Here is implementation: https://github.com/mymarilyn/clickhouse-driver/commit/e2916b65a5c8b7cf924d6529702d8ecfbc0a8b2e

This feature will be in next release.

**Comment by xzkostyan** [comment]
Feature included in https://github.com/mymarilyn/clickhouse-driver/releases/tag/0.0.5.
