### ISSUE TITLE
ServerException: Code: 241 - DB::Exception: Memory limit (total) exceeded

### ISSUE THREAD

**Issue by SE2AI** [mymarilyn/clickhouse-driver#200]
dear authors,

I tried to insert batch number of record (500 records/thread x 6 threads) into clickhouse table, and got the runtime error below:

> clickhouse_driver.errors.ServerException: Code: 241.
> DB::Exception: Memory limit (total) exceeded: would use 56.02 GiB (attempt to allocate chunk of 4219316 bytes), maximum: 56.02 GiB. Stack trace:

This error does not always appeared, it means the `insert` could somtimes be performed successfully, sometimes not. I can't figure out why it happened. 

Refering to some online QA, I tried to change clickhouse user.xml file, the <max_memory_usage> to 50G, but it didn't work.

What does the ` chunk of 4219316 bytes` mean? Could you please tell me the reason, and any suggestions to solve this problem? thanks a lot:)

**Comment by xzkostyan** [comment]
This is clickhouse-server error (`ServerException: Code: 241`) displayed on the client's side. Please refer clickhouse-server documentation.

Do you you use separate `Client` instance for single thread?

**Comment by SE2AI** [comment]
yes I use both separate client and only one client for 6 threads, and the problem appears in both situations.

**Comment by xzkostyan** [comment]
You should use instance per thread: https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#async-and-multithreading
And then diagnose the problem on the server side. It seems that there are other queries running and consuming memory

**Comment by SE2AI** [comment]
thanks, I have read the doc, but not notice that.
