### ISSUE TITLE
Server Exception switches database to default

### ISSUE THREAD

**Issue by atom96** [mymarilyn/clickhouse-driver#205]
**Describe the bug**
When you run query with `use dbname` statement and then query which raises expection, connection seems to be switched to `default` database

**To Reproduce**
```
import clickhouse_driver

client = clickhouse_driver.Client('localhost')
client.execute('create database repro')
client.execute('use repro')
client.execute('''
    CREATE TABLE test_table (
        num UInt32
    ) engine=MergeTree()
    order by num
''')

client.execute('select * from test_table')

try:
    client.execute('not a valid sql query')
except clickhouse_driver.errors.ServerException:
    pass


client.execute('select * from test_table')  # raises Table default.test_table doesn't exist

```

**Expected behavior**
Second select should not raise exception

**Versions**
Python 3.6.9
clickhouse-driver==0.2.0
ClickHouse server version 21.2.4

**Comment by xzkostyan** [comment]
SQL "use repro" is not parsed at client's side. It just tells server to emit next queries on db "repro". To keep default database construct client instance with desired db:  `client = clickhouse_driver.Client('localhost', database='repro')`

**Comment by xzkostyan** [comment]
But, it's interesting. May be it's no so trivial.

**Comment by atom96** [comment]
In usecase when you have to create database first do you recomend to create two instances of Client?

```
default_client = clickhouse_driver.Client('localhost')
default_client.execute('create database repro')
client = clickhouse_driver.Client('localhost', database='repro')
```

**Comment by vialorn** [comment]
As far as I know, when an exception arises, clickhouse_driver performs reconnect before the next command. And on the new connection, any connection-related command from the previous connection doesn't have any effect. So yes, instead of `use somedb` one should use `database=somedb` as `clickhouse_driver.Client` parameter. And yes, reconnect to newly created db.

**Comment by mateka** [comment]
Maybe `Client` (and `Connection`) classes could get `set_database` method?

**Comment by xzkostyan** [comment]
I've took a deeper look inside `clickhouse-client` behavour. It seems that client parses `USE xxx` statement and remembers current database after emitting `USE xxx` on server side.

I've added naive implementation for current database remembering. 

`set_database` method will duplicate the more natural `USE xxx`, IMHO.
