### ISSUE TITLE
Convert returned result of SELECT query from list of tuples to simple list IF there's one column in query

### ISSUE THREAD

**Issue by Heroidjsjs** [mymarilyn/clickhouse-driver#209]
Okay, I'll try to explain desired behaviour. For example, I need to retrieve values from certain table for **one** column only:
```python
test_list = client.execute("select a from test.requests")
```
Returned result is a list of tuples:
```python
[(a1,), (a2,), ... (an,)]
```
It's rather messy, isn't it? I expect to return a list of table column's values:
```python
[a1, a2, ... ,an]
```
Of course, I can write some shitty code in my project, but I'd like to see that behaviour in your library (if there's already a solution provided, please, tell me).

**Comment by xzkostyan** [comment]
What do you mean by "some shitty code"? And how outside code should handle arbitrary number of columns: one or two for example?

**Comment by Heroidjsjs** [comment]
> What do you mean by "some shitty code"?

I meant my own. :)

> And how outside code should handle arbitrary number of columns: one or two for example?

I didn't understand that question at all, but if by that you mean how library should handle, I was thinking about boolean value which will pass, i.e.:
```python
test_list = client.execute("select a from test.requests", one_column_only=True)
```
where param `one_column_only` returns results for SELECT queries like that, defaults to **_false_**. Correct me if I'd understood your question wrong.

**Comment by xzkostyan** [comment]
> I meant my own. :)

Yep, I meant the same. :) No offence.


Why do we need extra parameter for controlling this edge-case? You can use more unified and pythonic code for results processing; 

```python
for (x, ) in client.execute('SELECT number AS x FROM system.numbers LIMIT 5')
```

```python
for (x, y) in client.execute('SELECT number AS x, number AS y FROM system.numbers LIMIT 5')
```

**Comment by Heroidjsjs** [comment]
Well, for example in my case, I'd like to keep separate logic for database cases and for API response cases, and it's not kinda appropriate (or to be exact, readable) to see that, you know, business logic and all that staff. 
Yes, perhaps unified code IS okay for me, but it's not... for the others. By design, I'd like to keep all these actions separated. :)

**Comment by vialorn** [comment]
@Heroidjsjs , for this particular case, you may toggle [`columnar`](https://clickhouse-driver.readthedocs.io/en/latest/api.html#client) mode. This way, instead of a list of tuples, you get a list of list and the single one within will be your desired.
