### ISSUE TITLE
Nothing type

### ISSUE THREAD

**Issue by kszucs** [mymarilyn/clickhouse-driver#21]
Recent clickhouse has a new type `Nothing` which is currently unhandled by clickhouse-driver.

https://github.com/yandex/ClickHouse/blob/630d731ee35b55cfe2f3debfe92c1c21bbe3f50b/dbms/tests/queries/0_stateless/00420_null_in_scalar_subqueries.sql

Selecting `Null` raises:

```
/tmp/workspace/miniconda/envs/ibis_2.7/lib/python2.7/site-packages/clickhouse_driver/columns/nullablecolumn.py:5: in create_nullable_column
    nested = column_by_spec_getter(inner)
/tmp/workspace/miniconda/envs/ibis_2.7/lib/python2.7/site-packages/clickhouse_driver/columns/service.py:30: in create_column_with_options
    return get_column_by_spec(x, column_options)
/tmp/workspace/miniconda/envs/ibis_2.7/lib/python2.7/site-packages/clickhouse_driver/columns/service.py:51: in get_column_by_spec
    raise errors.UnknownTypeError('Unknown type {}'.format(e.args[0]))
E   UnknownTypeError: Code: 50. Unknown type Nothing
```

**Comment by xzkostyan** [comment]
I see. Driver should take into consideration server version.

You can downgrade server as temporary solution.

**Comment by kszucs** [comment]
@xzkostyan Would it resolve this compatibility issue if I explicitly set (or monkeypatch) `NullColumn.ch_type` to `Nullable(Nothing)`?

**Comment by xzkostyan** [comment]
No, unfortunately. If column starts with `Nullable` it passed to `create_nullable_column`. I'll try to investigate this issue at the weekend.

**Comment by xzkostyan** [comment]
Hi, @kszucs!

I've take a look at this issue. You can create (or monkeypatch) `Nothing` column in the following way:
```python
from .intcolumn import FormatColumn


class NothingColumn(FormatColumn):
    ch_type = 'Nothing'
    format = 'B'

    @property
    def size(self):
        return 1

    def after_read_item(self, buf):
        return None
```

It's almost identical with `NullColumn`, except `ch_type = 'Nothing'`. You should also add it to `column_by_type` (src/columns/service.py:24). See https://github.com/mymarilyn/clickhouse-driver/commit/25defba5fa93ea13d2ecc9bda19d5d71f47ae85c.

**Comment by xzkostyan** [comment]
Hi, @kszucs 

Version 0.0.10 is released. Should we close this issue?

**Comment by kszucs** [comment]
Sure, thanks!
