### ISSUE TITLE
Feature request: Support Map type

### ISSUE THREAD

**Issue by bonya** [mymarilyn/clickhouse-driver#212]
Hello,

clickhouse offers a new experimental data type [Map](https://clickhouse.tech/docs/en/sql-reference/data-types/map/). It would be very practical to be able to work with Map from the python driver.

**Versions**

- clickhouse-driver 0.2.0

**Comment by xzkostyan** [comment]
Map type support was merged into master: https://github.com/mymarilyn/clickhouse-driver/commit/b9a7410c4e100efa9858481d710400e6fa6b34e0

**Comment by bonya** [comment]
@xzkostyan Thanks a lot. I am already using implementation from your branch. Works as expected!
