### ISSUE TITLE
Memory Leak problem is severe, is there any plan to release bug fix?

### ISSUE THREAD

**Issue by FesonX** [mymarilyn/clickhouse-driver#216]
This problem is solved in March, but still not release :-(  #194

**Comment by xzkostyan** [comment]
I'll make release within a couple of weeks. You can install package [directly from github](https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github) before new release.

**Comment by xzkostyan** [comment]
Version 0.2.1 has been released.
