### ISSUE TITLE
'float' object has no attribute 'encode' when writing DataFrame in table with String column

### ISSUE THREAD

**Issue by avlasenkoev** [mymarilyn/clickhouse-driver#223]
**Describe the bug**
I have a string column in CH but not all values in DataFrame column are strings, it is detected as dtype=object. If I want to write my DataFrame to DB I can't do it and getting an error.
```
File "clickhouse_driver/bufferedwriter.pyx", line 54, in clickhouse_driver.bufferedwriter.BufferedWriter.write_strings
AttributeError: 'float' object has no attribute 'encode'
```

**To Reproduce**
client = Client(**credentials)
client.insert_dataframe("insert into tables values", df)

**Expected behavior**
Want to have the possibility to write any values to a string column

**Versions**
- Version of package with the problem 0.2.1
- Python version 3.7

**Comment by xzkostyan** [comment]
> I have a string column in CH but not all values in DataFrame column are strings

Why should library implicitly correct types?

**Comment by avlasenkoev** [comment]
@xzkostyanat a first sight should not
but if we want in the with data type String in ClickHouse save values like ("123d", "12") we can't do it...
And if the library doesn't do this, how to write to DB mixed data types which represent in Numpy as an object?

**Comment by xzkostyan** [comment]
You can explicitly cast to `str` for example.

**Comment by avlasenkoev** [comment]
you right, thanks, we can close this
