### ISSUE TITLE
Unknown type Point

### ISSUE THREAD

**Issue by sonfire86** [mymarilyn/clickhouse-driver#228]
```
client = Client('localhost', settings={'use_numpy': True})
client.insert_dataframe("INSERT INTO flurry.test_table VALUES", chunk)
```
Error 
```
in get_numpy_column_by_spec
    raise errors.UnknownTypeError('Unknown type {}'.format(e.args[0]))
clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type Point
```

**Versions**

- Version of package with the problem - 0.2.1.
- Python version - 3.7.8

**Comment by xzkostyan** [comment]
Hi.

Point type is not supported now. Feel free to add it: https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/columns/base.py#L139

**Comment by xzkostyan** [comment]
Geo types: Point, Ring, Polygon, MultiPolygon added in 0.2.4.
