### ISSUE TITLE
Insert Buffer?

### ISSUE THREAD

**Issue by inkrement** [mymarilyn/clickhouse-driver#23]
The documentation recommends to insert chunks of at least 1000 items at once. Is there an easy way to add some sort of buffer to gather inserts and thus enhance to performance? Of course, one could use a simple list and append to it/insert if it reaches a specific size, but things get more complicated when someone uses multiprocessing etc.

**Comment by kapilt** [comment]
for multiprocessing wouldn't each process have its own connection?

**Comment by inkrement** [comment]
@kapilt thanks, and good point! I also thought about it. I'll close this issue for now.
