### ISSUE TITLE
Feature request: Support OpenTelemetry

### ISSUE THREAD

**Issue by sc07kvm** [mymarilyn/clickhouse-driver#230]
Since ClickHouse [supports](https://clickhouse.tech/docs/en/operations/opentelemetry/) OpenTelemetry it would be cool to be able to transfer trace context in request similar to options
--opentelemetry-traceparent and --opentelemetry-tracestate in clickhouse-client

**Comment by xzkostyan** [comment]
Please explain a little bit more how do you see OpenTelemetry implementatioin in this package.

**Comment by sc07kvm** [comment]
I see OpenTelemetry implementatioin as options in settings of the clickhouse_driver.Client and clickhouse_driver.Client.execute[_iter|_with_progress]. These options will be passed to the server. Example:
```
>>> settings = {
    'opentelemetry_traceparent': '00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01', 
    'opentelemetry_tracestate': 'congo=t61rcWkgMzE'}
>>> client = Client('localhost', settings=settings)
```
Description of --opentelemetry-traceparent and --opentelemetry-tracestate can be found here:
```
clickhouse-client --help
...
  --opentelemetry-traceparent arg   OpenTelemetry traceparent header as described by W3C Trace Context recommendation
  --opentelemetry-tracestate arg    OpenTelemetry tracestate header as described by W3C Trace Context recommendation
...
```

**Comment by xzkostyan** [comment]
@sc07kvm I've added OpenTelemetry support to latest master. Looking forward to your feedback.
