### ISSUE TITLE
Feature Request: AggregateFunctions

### ISSUE THREAD

**Issue by ericmccarthy7** [mymarilyn/clickhouse-driver#233]
Hi,

I am looking for the ability to use [AggregateFunctions](https://clickhouse.tech/docs/en/sql-reference/data-types/aggregatefunction/) in queries.

I see you have a small note here: https://github.com/mymarilyn/clickhouse-driver/blob/7ac4bc8a235749b31299aba50838f8a60b6b505e/docs/types.rst#simpleaggregatefunctionf-t

> AggregateFunctions for AggregatingMergeTree Engine are not supported.

Since this is a blocker for my personal work... how can I help? Could you provide some information on why you had difficulty implementing it or any tips on how you would implement such a feature?

Thank you for the work you've done on this project, I use it daily! 👍

**Comment by xzkostyan** [comment]
Hi.

AFAIK, data in columns with AggregateFunctions types are returned in binary form. I didn't understand how binary data is formed the last time. I think particular aggregate function store data in it's accumulator and the method of data storing is defined in each function.

The second and the main problem is that we don't know exact size of accumulated data to read.

May be it's time for another iteration of digging into ClickHouse internals.

Why do you need to query directly aggregate functions instead of final aggregates?

**Comment by ericmccarthy7** [comment]
**To clarify I do just need the final aggregates.**

I'm writing a bunch of sqlalchemy code with https://github.com/xzkostyan/clickhouse-sqlalchemy as the dialect.

Worked my way backwards to get here. I know I could write the queries in raw sql such as:
```python
client.execute('SELECT id, sumMerge(val) FROM agg_table GROUP BY id')
```

But I was looking for a way to define the column types. Maybe I'm off track here but I thought this driver needs AggregateFunction column type, and then clickhouse-sqlalchemy can use it.

I started writing a test case for this:

```python
    def test_simple_sum_agg_function(self):
        columns = 'a AggregateFunction(sum, Int32)'

        data = [("arrayReduce('sumState', [1,2,3])", ), ("arrayReduce('sumState', [3,8])", )]
        with self.create_table(columns):
            self.client.execute(
                'INSERT INTO test (a) VALUES', data
            )

            query = 'SELECT sumMerge(a) FROM test'
            inserted = self.emit_cli(query)
            self.assertEqual(
                inserted, '17\n'
            )

            inserted = self.client.execute(query)
            self.assertEqual(inserted, data)
```

But of course the AggregateFunction needs to be implemented. If I'm off track please let me know.

**Comment by ericmccarthy7** [comment]
My apologies. Looks like I went too far down the rabbit-hole without actually looking around enough first.

Looks like I was able to solve this with generic sqlalchemy functions and just putting a `BINARY` type for the column. I was ready to dive deep... I'm not sure if this issue is still necessary then.

### For anyone who stumbles upon this:

sqlalchemy table (val is an AggregateFunction(sum, UInt32)):
```python
t = Table(
    "t",
    metadata,
    Column("id", types.UInt32),
    Column("val", BINARY),
    engine
)
```

code to get total sum
```python
clickhouse_connection.execute(
    select([func.sumMerge(t.c.val)])
).fetchone()
```

**Comment by xzkostyan** [comment]
It's really good investigation.

Hope you had a good time digging into SQLAlchemy and ClickHouse internals. :)
