### ISSUE TITLE
Automatic disconnection of native client

### ISSUE THREAD

**Issue by wlhjason** [mymarilyn/clickhouse-driver#237]
The DB API 2.0 `Connection` class implements the context manager protocol and [closes each cursor upon exit](https://github.com/mymarilyn/clickhouse-driver/blob/ddb4a6e1e7da74847bf6d8ef997ce29bc0fa147b/clickhouse_driver/dbapi/cursor.py#L80) (disconnects each underlying native client).

In contrast, the native `Client` class does not implement the context manager protocol and seems to expect users to call `client.disconnect()` when they are done.

Is there any particular reason for this design? If not, could I potentially open a PR to add `__enter__` and `__exit__` methods to the native `Client` (along with tests and docs)?

**Comment by xzkostyan** [comment]
Hi.

There is no particular reason. `__enter__` and `__exit__` methods will make `Client` usage more convenient. Please add tests for this feature.

**Comment by wlhjason** [comment]
@xzkostyan Just opened #238 to implement this.

**Comment by wlhjason** [comment]
@xzkostyan Thanks for merging and tidying this up!
