### ISSUE TITLE
TooLargeStringSize: Code: 131.

### ISSUE THREAD

**Issue by inkrement** [mymarilyn/clickhouse-driver#24]
I often get the error `TooLargeStringSize: Code: 131.` on inserting data into a table. How I can prevent it? I already tried to insert really small batches.

**Comment by xzkostyan** [comment]
Can you provide sample code and sql for reproducing this error?

**Comment by inkrement** [comment]
I am afraid that I am not able to reproduce this issue. Thus, I'll close it for now.
