### ISSUE TITLE
External data with empty data prematurely ends query connection

### ISSUE THREAD

**Issue by keeganw-nuna** [mymarilyn/clickhouse-driver#240]
**Describe the bug**
When an external table that contains no data in its object is provided with a ClickHouse query, the external data write is prematurely cut off, resulting in ClickHouse stating "\<table\> does not exist."

**To Reproduce**
```
client.execute(
    "SELECT * FROM an_external_table", 
    external_tables=[
        {
            "name": "an_external_table",
            "structure": [
                ("first_col", "String"),
                ("second_col", "String"),
            ],
            "data": []
        }
    ]
)
```
This command will result in CH throwing the error, however simply changing the `data` line to 
```
            "data": [['', '']]
```
results in the execution completing.

**Expected behavior**
An external table which has no data is handled similarly to an external table that has data. It is provided to ClickHouse, and does not result in a "\<table\> does not exist" error.

**Versions**

- Version of package with the problem. = 0.2.1
- Python version. = 3.8.9

**Guess at what is happening**
At [this point](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/connection.py#L614), an empty block (the external data with empty data field) is sent that is essentially the same exact thing that is sent to mark the end of data transfer (two lines later). This is what is prematurely ending the data execution. It seems like a potential solution would be somehow force including the table name, which is only used for [certain revisions](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/connection.py#L566).

**Comment by xzkostyan** [comment]
Fix was merged into master branch.
