### ISSUE TITLE
Performance bottleneck in read_varint

### ISSUE THREAD

**Issue by maciejblaz** [mymarilyn/clickhouse-driver#244]
**Describe the bug**
When running select queries from a table that consists mainly from 'varchar(50)' fields then the code becomes slow, even slower than dealing with the same data in PostgreSQL. 
I run a profiler and great majority of time is spent in:

Name: <clickhouse_driver.varint.read_varint>	
Call count: 30780	
Time: 1622ms (31.9%)
Own time: 1622ms (31.9%)

When I run the same queries using clickhouse CLI (instead of python code) then it works much faster.

**To Reproduce**
Simple SELECT queries with WHERE statements.

**Expected behavior**
Would be good to reduce the time to the same level that we have when using clickhouse cli.

**Versions**
clickhouse-driver: 0.2.1
python: 3.8.9

**Comment by xzkostyan** [comment]
> Would be good to reduce the time to the same level that we have when using clickhouse cli.

It's impossible. We are using not compiled language even with cythonized modules.

But it can be eventually optimized. Can you provide exact query example for optimization (with data)?

In "varchar"  aka String(N) columns reading `read_varint` code [is inlined](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/bufferedreader.pyx#L93) into column reading.

**Comment by maciejblaz** [comment]
That will not be easy, as I would have to obfuscate the data. Anyway - the table is rather simple, it has one column of type 'date' and 32 columns of type 'varchar(50)'. The query that I run is not complicated either, I usually query just subset of columns. Something like:
SELECT date, a as b, c as d, e as f, g as h FROM table_name WHERE i = '7_digit' AND file_name = 'provider_file_name' AND j = 'FOO' AND date BETWEEN '{since}' AND '{until}'
