### ISSUE TITLE
insert_dataframe +  empty value in LowCardinality = malformed block

### ISSUE THREAD

**Issue by filimonov** [mymarilyn/clickhouse-driver#249]
**Describe the bug**
clickhouse-driver can produce the malformed Native block during `insert_dataframe` with empty value in LowCardinality string type.

That malformed block get properly detected in ClickHouse 21.10 (after https://github.com/ClickHouse/ClickHouse/pull/27827 ) but on older ClickHouse version may lead to server crash.

**To Reproduce**
```py
#!/usr/bin/env python3

import pandas
import io
from clickhouse_driver import Client
    
client_tx = Client(host="localhost", database="default", user="default", password="", settings={'use_numpy': True})

client_tx.execute("DROP TABLE IF EXISTS test_lc_df")

client_tx.execute("""
CREATE TABLE IF NOT EXISTS test_lc_df
(
    id UInt64,
    val LowCardinality(String)
)
ENGINE = MergeTree
ORDER BY tuple();
""")

df = pandas.read_csv(io.BytesIO(b"id,val\n1,REMOTE\n2,\n"))
client_tx.insert_dataframe('INSERT INTO test_lc_df VALUES', df)

# df = pandas.read_csv(io.BytesIO(b"id,val\n2,\n"))
# client_tx.insert_dataframe('INSERT INTO test_lc_df VALUES', df)

client_tx.disconnect()
```

**Expected behavior**
Successful insert

**Versions**

- Version of package with the problem: 0.2.1
- Python version: Python 3.8.10

**Comment by xzkostyan** [comment]
Fix was merged into master branch.

**Comment by filimonov** [comment]
> Fix was merged into master branch.

Great! Maybe 0.2.2?

**Comment by xzkostyan** [comment]
Of course. But I want to get some feedback from users that use this package with numpy at first.

**Comment by xzkostyan** [comment]
Version 0.2.2 released.
