### ISSUE TITLE
Better support for writing bytes

### ISSUE THREAD

**Issue by lidalei** [mymarilyn/clickhouse-driver#25]
When writing a FixedString column, the data is first encoded using utf-8 to bytes in Python. This could cause a problem when the string cannot be encoded using utf-8. For instance, cipher text bytes generated by hmac sha256. I would suggest add type checking before encoding in https://github.com/mymarilyn/clickhouse-driver/blob/master/src/writer.py#L18 and https://github.com/mymarilyn/clickhouse-driver/blob/master/src/writer.py#L24. If the text is already bytes, just don't encode it. For example, `import hmac; hmac.new(b"done", msg=b"yes", digestmod="sha256").digest().decode('utf-8')` will throw an exception `'utf-8' codec can't decode byte 0xcb in position 3`.

**Comment by k4otix** [comment]
Agree, as another example this is also causing me to not be able to write a FixedString(16) to represent IPv6 address values for use with `IPv6NumToString` (I know there is the corresponding `IPv6StringToNum` function, but I have a specific use case in mind where I want to store the value directly). If I comment out #L24 in writer.py as @lidalei mentions, it works. Example:
```python
ip = ipaddress.ip_address(unicode('::FFFF:192.168.1.1'))
client.execute('CREATE TABLE test (ip FixedString(16)) ENGINE=Memory')
client.execute('INSERT INTO test FORMAT JSONEachRow', [{'ip': ip.packed}])
```

**Comment by lidalei** [comment]
@k4otix There is a potential problem in my pull request. If a fixed string (bytes) can be decoded, `read_binary_str_fixed_len` will decode it into a string. If it cannot be decoded, `read_binary_str_fixed_len ` will return bytes. This means the calling program has to do type assertion. More precisely, it has to check if the returned result is bytes or string. So this made the program a little implicit.

**Comment by xzkostyan** [comment]
Hi.

Version 0.0.11 is released. It contains your PR.
