### ISSUE TITLE
Map columns not supported

### ISSUE THREAD

**Issue by acmeguy** [mymarilyn/clickhouse-driver#254]
**Describe the bug**
columns that are defined using MAP(:type, :type) in clickhouse are not supported by the driver.

**To Reproduce**
Try inserting a map value into a a table that has a map column
observe the error "clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type Map(String, String)"

**Expected behavior**
A new record is created

**Versions**
- Python driver: 0.2.2
- Latest ClickHouse server 
- Python version 3.9

**Comment by acmeguy** [comment]
Fixed with:

**stringcolumn.py:21**
    def write_items(self, items, buf):
        if hasattr(items, 'tolist'):
            return buf.write_strings(items.tolist(), encoding=self.encoding)
        else:
            return buf.write_strings(items, encoding=self.encoding)

**service.py:**
from ..mapcolumn import create_map_column

elif spec.startswith('Map'):
    return create_map_column(spec, create_column_with_options)

**Comment by xzkostyan** [comment]
Map columns [should work](https://github.com/mymarilyn/clickhouse-driver/commit/b9a7410c4e100efa9858481d710400e6fa6b34e0) only with `use_numpy=False` now.

**Comment by acmeguy** [comment]
thank you. This small "patch" above makes them worh with numpy as well

**Comment by xzkostyan** [comment]
Fixed in 0.2.3.
