### ISSUE TITLE
No module named 'clickhouse_driver.varint'

### ISSUE THREAD

**Issue by FedericoCeratto** [mymarilyn/clickhouse-driver#271]
Hello and thank you for developing clickhouse-driver.

On version 0.2.2 and previous, tests are failing to run from the checked-out repository or the tarball due to the shared object not being imported: `ModuleNotFoundError: No module named 'clickhouse_driver.varint'`
It happens when running `pytest-3` and also with `python3 tests/testcase.py`

It happens with python 3.9.9 and previous.

**Comment by xzkostyan** [comment]
Hi.

I've recently [migrated](https://github.com/mymarilyn/clickhouse-driver/commit/e1ce0011d01a0f2b215783cffd4b962a06f73e88) from nose runner to pytest. Nose just won't run on 3.10. [Latest documentation](https://clickhouse-driver.readthedocs.io/en/latest/development.html) explains how to run tests with pytest;

```bash
python testsrequire.py && python setup.py develop
py.test -v
```

**Comment by FedericoCeratto** [comment]
Thanks. Clarification for other readers:

1) `tests/` contains **integration** tests that must be run against a local Clickhouse instance. There is no unit tests directory.
 
2) I was able to run most of the test using a dedicated virtualenv:
```
python3 -m venv venv
. ./venv/bin/activate
./venv/bin/python3 testsrequire.py
./venv/bin/python3 setup.py develop
./venv/bin/py.test -s
```
