### ISSUE TITLE
HTTP support: will it ever be considered?

### ISSUE THREAD

**Issue by pkit** [mymarilyn/clickhouse-driver#275]
Hi, I can start contributing HTTP support or fork this one to implement HTTP.
Which one do you choose?

**Comment by xzkostyan** [comment]
Hi.

I'd prefer to keep things separated:

1) TCP transport is more complicated than HTTP;
2) Separate HTTP driver development will be easier for contributors;
3) HTTP driver will have different requirements;
 
These points lead to [KISS](https://en.wikipedia.org/wiki/KISS_principle) principle. 

Feel free to fork the project if you really need it. But I'll recommend you to make HTTP driver from scratch or collaborate with authors of existing [HTTP drivers](https://clickhouse.com/docs/en/interfaces/third-party/client-libraries/) written in Python.
