### ISSUE TITLE
Dates are lower by 1

### ISSUE THREAD

**Issue by Thordin** [mymarilyn/clickhouse-driver#29]
date.fromtimestamp is supposed to take a local timestamp not a UTC one. I am in a timezone that is behind UTC, so all dates are 1 day behind.

```
>>> datetime.date.fromtimestamp(0)
datetime.date(1969, 12, 31)
```

To fix this you need to use datetime.datetime.utcfromtimestamp().date() instead.

https://github.com/mymarilyn/clickhouse-driver/blob/a3a26513d9533f389674c34c19ed7f8dd94b5289/src/columns/datecolumn.py#L18

`return datetime.datetime.utcfromtimestamp(value * self.offset).date()`

**Comment by xzkostyan** [comment]
Fixed: https://github.com/mymarilyn/clickhouse-driver/commit/dcfe6403ed62c4a03a975ff958ed90a9c3281a10.

This change will be in next release.

**Comment by Thordin** [comment]
That's great, did you take a look at another fix I proposed here?

https://github.com/mymarilyn/clickhouse-driver/issues/20

**Comment by xzkostyan** [comment]
Hi, @Thordin

Version 0.0.10 [is released](https://pypi.python.org/pypi/clickhouse-driver/0.0.10). Should we close this issue?
