### ISSUE TITLE
how to get list of dict result

### ISSUE THREAD

**Issue by lihuacai168** [mymarilyn/clickhouse-driver#290]
**Describe the bug**
now cursor execute reusult is list of tuple.
I wanna get the column name ,so the result type should be list of dict

**To Reproduce**
```python
from clickhouse_driver import connect
clickhouse_default_config = {
    'host': 'localhost',
    'port': 9000,
    'user': 'default',
    'password': '123456',
}
conn = connect(**clickhouse_default_config)
cursor = conn.cursor()
cursor.execute('select * from app_profile_tab limit 10;')
cursor.fetchall()
[(1, 'ID', '2', None, None)]
```

**Expected behavior**
app_profile table
```
create table profile_tab
(
    developer_id     Nullable(Int64),
    developer_type   Nullable(String),
    developer_region Nullable(String),
    status           Nullable(Int32),
    create_time      Nullable(DateTime) default now()
)
    engine = Memory;
```
Expected Rusult: `[{'developer_id': 1, 'developer_type': 'ID', 'developer_region': '2', 'status': None, 'create_time': ‘2022-02-14 12:20:54’}]`

**Versions**

- package version = "0.2.3"
- ClickHouse server version = “22.1.2.2”
- python = "3.8.12"

**Comment by xzkostyan** [comment]
There is no such feature right now.

**Comment by immerrr** [comment]
It can be done somewhat easily since `execute_iter(..., with_column_types=True)` method returns column names and types as the first item of the response:

```python
def execute_return_dicts(query, **kwargs):
    resp = client.execute_iter(query, with_column_types=True, **kwargs)
    column_names, column_types = zip(*next(resp))

    for row in resp:
        yield dict(zip(column_names, row))
```

**Comment by xzkostyan** [comment]
Dict and namedtuple cursors are added in 0.2.4: https://clickhouse-driver.readthedocs.io/en/latest/dbapi.html#extras
