### ISSUE TITLE
NumPy support is not implemented for Decimal(9, 2). Using generic column

### ISSUE THREAD

**Issue by flhang** [mymarilyn/clickhouse-driver#298]
Describe the bug
NumPy support is not implemented for Decimal(9, 2). Using generic column

version 0.2.0 is ok , but version 0.2.3 report the warning

Versions

Python driver: 0.2.3
Latest ClickHouse server
Python version 3.8.8

**Comment by stas-sl** [comment]
Same here, for more context, I set `'use_numpy': True` and use `client.insert_dataframe` with `float64` column. After this warning it throws exception:
```
Type mismatch in VALUES section. Repeat query with types_check=True for detailed info. Column x: required argument is not an integer
```

**Comment by sheldonrong** [comment]
@xzkostyan can this warning be suppressed using any configs?

**Comment by xzkostyan** [comment]
You can use built-in python's warning control: https://docs.python.org/3/library/warnings.html

**Comment by knl** [comment]
> You can use built-in python's warning control: https://docs.python.org/3/library/warnings.html

I tried:

```py
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    df = client.query_dataframe(...)
```

and my console is still spammed with these warnings.
