### ISSUE TITLE
Set query settings

### ISSUE THREAD

**Issue by elrik75** [mymarilyn/clickhouse-driver#3]
Clickhouse queries accept lots of settings, according to https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/Settings.h#L30

If a setting is set to a value different from the default one, then it should be sent to the server.
It could be done in `connection.send_query()` before `write_binary_str('', self.fout)  # end of query settings`

Example of use:
```
c = client('server')
settings = Settings()
settings.replace_running_query = True
c.execute('SELECT 1', settings, query_id=a_query_id)
```

**Comment by xzkostyan** [comment]
Hi!

This feature is ready https://github.com/mymarilyn/clickhouse-driver/commit/8e5f1690fafd01e098969ec59b8799b2374d398a and will be in upcoming release.

**Comment by xzkostyan** [comment]
Feature included in https://github.com/mymarilyn/clickhouse-driver/releases/tag/0.0.5.
