### ISSUE TITLE
Tests fails with clickhouse 22.3.3.44

### ISSUE THREAD

**Issue by antip00** [mymarilyn/clickhouse-driver#304]
clickhouse version: 22.3.3.44
Some tests on clickhouse-driver 0.2.1, 0.2.2 fails.
Tests on clickhouse-driver 0.2.3 are not run.

I attach patches in zip archive that helped me fix it.
[diffs.zip](https://github.com/mymarilyn/clickhouse-driver/files/8603093/diffs.zip)

**Comment by xzkostyan** [comment]
These changes are already persist in master branch. There is no need in nose runner anymore. Did you attach the right diffs?

**Comment by antip00** [comment]
When you try to run tests from master with pytest you get 
```
Ran 0 tests in 0.000s
OK
```

**Comment by xzkostyan** [comment]
We need extra context to reproduce the problem. GitHub actions are green: https://github.com/mymarilyn/clickhouse-driver/actions

Did you install requirements? https://clickhouse-driver.readthedocs.io/en/latest/development.html From which directory you run tests?

**Comment by antip00** [comment]
Thank you. Now it works. Sorry for late answer
