### ISSUE TITLE
Nanoseconds are not preserved on insert for DateTime64(8) columns

### ISSUE THREAD

**Issue by acmeguy** [mymarilyn/clickhouse-driver#307]
**Describe the bug**
Nanoseconds are not preserved on insert for DateTime64(8) columns
"2022-05-04 13:45:00.00000001" string value
or parsed "2022-05-04 13:45:00.00000001" string value (tried more than one)

**To Reproduce**
Try inserting a nanosecond value into clickhouse
nanoseconds are lost/random

**Expected behavior**
nanoseconds are preserved correctly in clickhouse

**Versions**
Latest of everything

**Comment by xzkostyan** [comment]
Please provide a minimal snippet for issue reproducing.

**Comment by acmeguy** [comment]
Just create a DateTime64(8) field and try populating it with a pandas dataframe containing 1 column of high-res datetimes.
After some poking, I'm wondering if this could be a Clickhouse issue.  (I will poke some more)

**Comment by xzkostyan** [comment]
Python [datetime](https://docs.python.org/3/library/datetime.html#datetime-objects) objects can store precision only in microseconds. This is pointed in the package [docs](https://clickhouse-driver.readthedocs.io/en/latest/types.html#datetime-timezone-datetime64-timezone).

NumPy insertion with nanoseconds precision is broken now.

**Comment by socketpair** [comment]
Please just allow to pass `float` in insert queries.
