### ISSUE TITLE
When using domain instead of IP address, the DNS resolve don't change.

### ISSUE THREAD

**Issue by jackpgao** [mymarilyn/clickhouse-driver#31]
I use domain instead of IP address, in order to do load balance and failover.

But when I change the domain mapping, the script still continuing connect to the origin IP address. 

For example, I use domain 'xxx.test.com' which mapping ip1, and ip2, and start the script, the data will write into ip1 and ip2 round-robin.

After the mapping of domain to ip2 and ip3, that means replace ip1 with ip3, the script still continues to  write to ip1.

**Comment by xzkostyan** [comment]
Hi.

When client is connected to some CH-server it should communicate with this server until disconnect. 

Can you provide example of communication?

**Comment by jackpgao** [comment]
@xzkostyan  


My situation: 

I use Python scripts do some ETL job, after each loop of data processing, writing the result into ClickHouse.

As I understand, the connection to ClickHouse is established each time.

After I change the DNS resolve, the new connection should connect to the new IP address, actually, it's not.

**Comment by jackpgao** [comment]
Wrong usage. 
Please Ignore.
