### ISSUE TITLE
execute_iter more row

### ISSUE THREAD

**Issue by MIracleyin** [mymarilyn/clickhouse-driver#311]
Hi, thanks for your work.
I have some use case problems in execute_iter
I want to execter_iter many rows in one iter process, but I can't find the example.
Could you give me some idea about that?

**Comment by xzkostyan** [comment]
It seems that you need `chunk` wrapper over `execute_iter`: https://stackoverflow.com/a/22045226

**Comment by MIracleyin** [comment]
> It seems that you need a `chunk` wrapper over `execute_iter`: https://stackoverflow.com/a/22045226

Thanks for your response. But clickhouse select row as much as faster?
Maybe I should try your idea, and test its effectiveness.
