### ISSUE TITLE
It seems that you need `chunk` wrapper over `execute_iter`: https://stackoverflow.com/a/22045226

### ISSUE THREAD

**Issue by MIracleyin** [mymarilyn/clickhouse-driver#314]
It seems that you need `chunk` wrapper over `execute_iter`: https://stackoverflow.com/a/22045226

_Originally posted by @xzkostyan in https://github.com/mymarilyn/clickhouse-driver/issues/311#issuecomment-1136126055_

**Comment by MIracleyin** [comment]
Hi, I think its features will be useful for many applications. Maybe add a parameter `chunk_size` for the `execte_iter` function?

**Comment by xzkostyan** [comment]
Yes. it makes sense.

**Comment by MIracleyin** [comment]
> 

Okay, I will try to implement it and pr.

**Comment by xzkostyan** [comment]
You can use `clickhouse_driver.util.helpers.chunks`.

**Comment by MIracleyin** [comment]
> 

thanks!!
