### ISSUE TITLE
Nested insertion still fails

### ISSUE THREAD

**Issue by techkuz** [mymarilyn/clickhouse-driver#316]
**Describe the bug**
Following the [documentation](https://clickhouse-driver.readthedocs.io/en/latest/types.html#nested-flatten-nested-0), I am still not being able to insert the data into nested columns via ch-driver (ch directly works)

The error is `ValueError: Expected 1 columns, got 3` 

If I remove `('b', 200), ('c', 300)` from the query, it fails with `zip argument #2 must support iteration`

**To Reproduce**
```
SET flatten_nested = 0;
CREATE TABLE test_nested (col Nested(name String, version UInt16)) Engine = Memory;
```

```
from clickhouse_driver import Client

client = Client(host='host', user='user', password='password')

client.execute(
    'INSERT INTO test_nested VALUES',
    [([('a', 100), ('b', 200), ('c', 300)]),]
)
```

**Expected behavior**
Data is inserted

**Versions**

- clickhouse-driver @ git+https://github.com/mymarilyn/clickhouse-driver.git@26a4f11c66d02ecd014296f78c66cc80d4b4b3ea
- clickhouse 21.8.4.51
- python 3.7.4

**Comment by xzkostyan** [comment]
There is a couple of typos in docs. Correct insert:

```python
client.execute(
          'INSERT INTO test_nested VALUES', [
          ([('a', 100), ('b', 200), ('c', 300)], )
])
```

**Comment by techkuz** [comment]
@xzkostyan 
```
import clickhouse_driver

conn = clickhouse_driver.connect(host=host, user=user, password=password)
cursor = conn.cursor()
query = 'INSERT INTO test_nested VALUES '
values = [
    ([None], )
]
```

Fails with 

> TypeError: zip argument #1 must support iteration
