### ISSUE TITLE
【insert_dataframe】Unsupported column type: <class 'numpy.ndarray'>. list or tuple is expected.

### ISSUE THREAD

**Issue by RonnieHu** [mymarilyn/clickhouse-driver#318]
when i tried to use the client.insert_dataframe(sql, dataframe), it jut crashed.
 
![image](https://user-images.githubusercontent.com/36696508/173023154-523a1c9a-6995-4732-95cd-559cef27f050.png)

![image](https://user-images.githubusercontent.com/36696508/173023234-fa9fb2fb-68bb-4ddf-93c1-884770a0480a.png)

**Comment by RonnieHu** [comment]
the pandas.dataframe has created, but it cannnot use the insert_dataframe, why?

**Comment by xzkostyan** [comment]
I'm unable to reproduce this issue with provided information. Please provide snippet that will cause this error with data and `CREATE TABLE` query.

**Comment by RonnieHu** [comment]
> I'm unable to reproduce this issue with provided information. Please provide snippet that will cause this error with data and `CREATE TABLE` query.

this is the table:
![image](https://user-images.githubusercontent.com/36696508/173477848-b8872ad0-a633-47cb-b6ed-1ab7157c9561.png)

this is the source code with 'insert_dataframe'
![image](https://user-images.githubusercontent.com/36696508/173477969-f5d1f792-ae96-474e-88e9-5013a2cadb87.png)

this is the output info:
![image](https://user-images.githubusercontent.com/36696508/173478037-92b9d3c0-b766-488f-80f1-dfed665a4f92.png)

Thank u for your concern :)

**Comment by RonnieHu** [comment]
> I'm unable to reproduce this issue with provided information. Please provide snippet that will cause this error with data and `CREATE TABLE` query.

I've solved this problem by setting `client = Client('localhost', settings={"use_numpy":True})`
thank you for your try to help me.
Would you like to improve the docs about insert_dataframe() with client settings? This would help others to solve the problem. : )
