### ISSUE TITLE
Version in project is 0.2.4, but 0.2.3 in tags, pypi and docs

### ISSUE THREAD

**Issue by timsmd** [mymarilyn/clickhouse-driver#319]
in [clickhouse-driver.__init__.py](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/__init__.py) the version is set to `(0, 2, 4)`, but in project tags, docs and pypi version is 0.2.3.

code from pypi doesn't have [dbapi/extras.py](https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/dbapi/extras.py) module, while current master branch does.

[pypi link](https://pypi.org/project/clickhouse-driver/)
[docs link](https://clickhouse-driver.readthedocs.io/en/latest/features.html#:~:text=(since%20version%200.2.4))

**Comment by xzkostyan** [comment]
Yes. What's the problem? This version is unreleased yet.
