### ISSUE TITLE
query_dataframe returns empty dataframe with shape (0, 0) instead of returning shape (0, number of columns)

### ISSUE THREAD

**Issue by nariman9119** [mymarilyn/clickhouse-driver#321]
**Describe the bug**
When the query returns 0 rows, function returns empty dataframe with the shape (0,0) without specifying any columns from query.

IMHO, in that case it should return the dataframe with shape (0, # of columns)

**To Reproduce**

```
example_dataframe = clickhouse_client.query_dataframe(some_query_that_returns_no_data)
example_dataframe.shape

(0, 0)
```
**Expected behavior**
```
example_dataframe = clickhouse_client.query_dataframe(some_query_that_returns_no_data)
example_dataframe.shape

(0, # of columns)
```

**Comment by xzkostyan** [comment]
Yes. It makes sense.
