### ISSUE TITLE
Inserting null fields - AttributeError: 'NoneType' object has no attribute 'encode' 

### ISSUE THREAD

**Issue by BrowenChen** [mymarilyn/clickhouse-driver#322]
**Describe the bug**
Have a dataframe loaded in a Spark job with NoneType fields in a few columns. Using clickhouse-driver to `    clickhouse_client.execute(f"INSERT INTO {dst_table_ref} VALUES", values)`, but job fails with `AttributeError: 'NoneType' object has no attribute 'encode' `

My workaround is to cast to string 'None' - `df.fillna("None")` before the insertion.

> Stack Trace:
> `Traceback (most recent call last):
>   File "/tmp/4310a8c9-c5c8-4cee-84e7-6c774c936909/replicate_bigquery_to_clickhouse.py", line 74, in <module>
>     sys.exit(main(**args.__dict__))
>   File "/tmp/4310a8c9-c5c8-4cee-84e7-6c774c936909/replicate_bigquery_to_clickhouse.py", line 52, in main
>     clickhouse_client.execute(f"INSERT INTO {dst_table_ref} VALUES", values)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/client.py", line 298, in execute
>     rv = self.process_insert_query(
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/client.py", line 518, in process_insert_query
>     rv = self.send_data(sample_block, data,
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/client.py", line 571, in send_data
>     self.connection.send_data(block)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 587, in send_data
>     self.block_out.write(block)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 38, in write
>     write_column(self.context, col_name, col_type, items,
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
>     column.write_data(items, buf)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 87, in write_data
>     self._write_data(items, buf)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 91, in _write_data
>     self.write_items(prepared, buf)
>   File "/opt/conda/default/lib/python3.8/site-packages/clickhouse_driver/columns/stringcolumn.py", line 18, in write_items
>     buf.write_strings(items, encoding=self.encoding)
>   File "clickhouse_driver/bufferedwriter.pyx", line 54, in clickhouse_driver.bufferedwriter.BufferedWriter.write_strings
> AttributeError: 'NoneType' object has no attribute 'encode'
> 22/07/15 21:21:21 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@3589e034{HTTP/1.1, (http/1.1)}{0.0.0.0:0}`

**To Reproduce**
1. Load a dataframe with NoneType columns. 
2. clickhouse_client.execute(f"INSERT INTO {dst_table_ref} VALUES", values)`

**Expected behavior**
Support NoneType

**Versions**
clickhouse-driver==0.2.4

**Comment by fhrzn** [comment]
Hello @BrowenChen , could you please share how did you solve this issue? Currently I am having similar approach and interested to hear your solution). Thanks in advance!

**Comment by zjw-zjw** [comment]
Hello @BrowenChen  , could you please share how did you solve this issue? Currently I am having similar approach and interested to hear your solution). Thanks in advance!
