### ISSUE TITLE
Why is so slow to get data by (sql select * from table) ?

### ISSUE THREAD

**Issue by AgileQuant** [mymarilyn/clickhouse-driver#324]
```
from clickhouse_driver import Client
import pandas as pd
import time
client = Client('localhost ', user='default',password="",database='option')
start = time.time()
data = client.execute('select * from sick')
df = pd.DataFrame(data)
print(len(df))
df
```

Hello ,I am using above code to read all data from a table . the whole data is 70K row . it will cost 38 seconds to read it while the 8123/play client only shows Elapsed: 0.018 sec, read 8.20 thousand rows, 3.12 MB.   

However, it is very slow to take 38seconds to read 70K row data .  the experience is so different from what homepage mentioned of read billions data only need 1 second. 

if anyone know solution, please comment .

**Comment by xzkostyan** [comment]
You can start investigation by selecting columns one by one and finding out which column / data type gives penalty.

**Comment by AgileQuant** [comment]
> 

I just tried.  The table have 39 columes .  Every time I select one colume of all data.  It add 1 second consuming. so the whole data cost almost 38 seconds while it only have 7K rows.

**Comment by xzkostyan** [comment]
What column data types has your table?

**Comment by AgileQuant** [comment]
the problem solved,  if i use server to read data . it only takes one second.
