### ISSUE TITLE
[Question] How to set query timeout parameter using pure Client?

### ISSUE THREAD

**Issue by tahayk** [mymarilyn/clickhouse-driver#330]
Hello everyone, 

I'm using `clickhouse-driver==0.2.4`; the pure Client way, and I couldn't figure out how to pass a timeout for the query execution: 

Example: 

```python
client = clickhouse_driver.Client(host=config("ch_host"),
                                                 database="default",
                                                 port=config("ch_port", cast=int),
                                                 settings={"connect_timeout":1, "receive_timeout":1, "send_timeout":1})

client.execute("SELECT * FROM numbers(1000000);")
```

but my queries are taking around 7s without failing.
is there a way to achieve this ? 

Thank you in advance.

**Comment by xzkostyan** [comment]
Available timeouts listed here: https://clickhouse-driver.readthedocs.io/en/latest/api.html#connection

**Comment by tahayk** [comment]
@xzkostyan thank you for the response;
but is it possible to use the pure Client? as documentation states, the [Client instance can take a `settings` argument](https://clickhouse-driver.readthedocs.io/en/latest/api.html#client) with these possible values: https://clickhouse.com/docs/en/operations/settings/settings/

**Comment by xzkostyan** [comment]
How can you specify it for `clickhouse-client`?

**Comment by tahayk** [comment]
@xzkostyan thank you for the hint, 
there is a `setting` called `max_execution_time`; unfortunately it is not documented in https://clickhouse.com/docs/en/operations/settings/settings/  but documented here: https://clickhouse.com/docs/en/operations/settings/query-complexity/#max-execution-time

so the final code looks like this:
```python
client = clickhouse_driver.Client(host=config("ch_host"),
                                                 database="default",
                                                 port=config("ch_port", cast=int),
                                                 settings={"max_execution_time":1})

client.execute("SELECT * FROM numbers(1000000);")
```
