### ISSUE TITLE
Feature Request: Support pandas StringArray and ArrowStringArray

### ISSUE THREAD

**Issue by Simon-Chenzw** [mymarilyn/clickhouse-driver#337]
pandas has three type to store string , `object` `string` `string[pyarrow]`

according to [user guide](https://pandas.pydata.org/pandas-docs/version/1.5/user_guide/text.html)
> We recommend using [StringDtype](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.StringDtype.html#pandas.StringDtype) to store text data.

[\[docs\] v1.5 arrays-string](https://pandas.pydata.org/pandas-docs/version/1.5/reference/arrays.html#api-arrays-string)

and in my use case, it use 2GiB with `object` and 400MiB with `string[pyarrow]`, saving memory a lot

but `insert_dataframe` does not support `string` nor `string[pyarrow]` (v0.2.4) 

Minimal, Reproducible Example
```sql
create table test (
    text String
) ENGINE = MergeTree()
ORDER BY (text)
```

```
import pandas as pd
from clickhouse_driver import Client

client = Client(
    host="localhost",
    settings={"use_numpy": True},
)
client.insert_dataframe(
    "INSERT INTO test VALUES",
    dataframe=pd.DataFrame(
        ["test"],
        columns=["text"],
        dtype="string[pyarrow]",
    ),
)
```

it would be great if we support `string` `string[pyarrow]`

Thank you!

**Comment by Simon-Chenzw** [comment]
It looks like this PR #317 is able to support both arrays, any update?

**Comment by xzkostyan** [comment]
@Simon-Chenzw I'll merge that PR when tests appear.
