### ISSUE TITLE
enhancement - ability to omit values when using JSONEachRow

### ISSUE THREAD

**Issue by k4otix** [mymarilyn/clickhouse-driver#34]
clickhouse-driver==0.0.10
ClickHouse server version 1.1.54362

Clickhouse JSONEachRow format supports omitting values when inserting records; it would be great if clickhouse-driver would also support this behavior - http://clickhouse-docs.readthedocs.io/en/latest/formats/jsoneachrow.html

>  It is also possible to omit values in which case the default value of the column is inserted.

However, clickhouse-driver instead throws an exception:

```python
record = {'x': 1}
client.execute('DROP TABLE IF EXISTS test')
client.execute('CREATE TABLE test (x Int32, y Int32) ENGINE=Memory')
client.execute('INSERT INTO test FORMAT JSONEachRow', [record])
print(client.execute('SELECT * FROM test'))
```
```
Traceback (most recent call last):
  File "test.py", line 89, in <module>
    client.execute('INSERT INTO test FORMAT JSONEachRow', [record])
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 169, in execute
    types_check=types_check
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 239, in process_insert_query
    self.send_data(sample_block, data, types_check=types_check)
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 261, in send_data
    types_check=types_check)
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/block.py", line 51, in __init__
    self.dicts_to_rows(data)
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/block.py", line 70, in dicts_to_rows
    self.data[i] = [row[name] for name in column_names]
KeyError: u'y'
```

Working example using **clickhouse-client**:
```
$ clickhouse-client -n --query='DROP TABLE IF EXISTS test; CREATE TABLE test (x Int32, y Int32) ENGINE=Memory; INSERT INTO test FORMAT JSONEachRow' <<< '{"x": 1}'
$ clickhouse-client -E --query='SELECT * FROM test'
Row 1:
──────
x: 1
y: 0
```
I was able to get past the `KeyError` in the Traceback above by changing https://github.com/mymarilyn/clickhouse-driver/blob/56395db5a933ee54d9ae8cdebd021f94870899a6/src/block.py#L70 to:
```python
self.data[i] = [row[name] for name in column_names if name in row]
```
I get to the point of sending the data to the server but get the following error, which I unfortunately don't have the time to dig into right now to come up with a possible PR/solution:
```
  File "/anaconda3/envs/myenv/lib/python2.7/site-packages/clickhouse_driver/streams/native.py", line 37, in write
    raise ValueError('Different rows length')
ValueError: Different rows length
```
This would be a great feature so that JSON objects don't always have to be fully specified in the client code!

**Comment by xzkostyan** [comment]
Hi, @k4otix.

`clickhouse-client` works with Native format, not JSON*. But the data for insertion should be specified as list of tuples or list of dicts. All tuples/dicts must be homogeneous by length/keys. It's the only way data can be sent over Native protocol. 

You also can pass generator object as data with insert query. That's the way you can do all required preparations on list of dicts.
