### ISSUE TITLE
Support python 3.11?

### ISSUE THREAD

**Issue by wenbinf** [mymarilyn/clickhouse-driver#341]
**Describe the bug**
Can't install clickhouse-driver with python 3.11

**To Reproduce**
pip3.11 install clickhouse-driver

**Expected behavior**
Seeing such errors:
```
      building 'clickhouse_driver.bufferedreader' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/clickhouse_driver
      x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/mnt/python-ve/ck/include -I/usr/include/python3.11 -c clickhouse_driver/bufferedreader.c -o build/temp.linux-x86_64-cpython-311/clickhouse_driver/bufferedreader.o
      clickhouse_driver/bufferedreader.c:209:12: fatal error: longintrepr.h: No such file or directory
        209 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**Versions**

- clickhouse-driver 0.24
- Python 3.11

**Comment by xzkostyan** [comment]
I'll push wheels as soon as they will be available in cibuildwheel. How it produces wheels only for 3.11rc2.

**Comment by xzkostyan** [comment]
Wheels for version 0.2.4 and 3.11 are available on pypi.

**Comment by xzkostyan** [comment]
@tonyabracadabra what do you mean?

**Comment by asottile-sentry** [comment]
if you could make a new release with newly cythonized `.c` files in the source dist that'll help this build cleanly on python3.11 macos arm64 -- right now they fail due to:

```
      gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/asottile/opt/pythons/cp311-cp311/include/python3.11 -c clickhouse_driver/bufferedreader.c -o build/temp.macosx-12.5-arm64-3.11/clickhouse_driver/bufferedreader.o
      clickhouse_driver/bufferedreader.c:209:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
```

a workaround is to preinstall `cython` such that they'll get freshly generated

**Comment by xzkostyan** [comment]
Python 3.11 is fully supported now. `clickhouse-cityhash` also has been patched: https://github.com/xzkostyan/clickhouse-cityhash/commit/112fa22f2ff0bcfeed827dbebacc5e50828f24a9

Wheels for both packages are placed on pypi.

**Comment by asottile-sentry** [comment]
@xzkostyan can you make a new release (0.2.5 or such?) with the updated cythonized files (that way it builds from source cleanly on M1)

**Comment by Tseyang** [comment]
Is there an expected timeline for 0.2.5 being released with 3.11 support?

**Comment by xzkostyan** [comment]
I'll push new version in this weekend.

**Comment by xzkostyan** [comment]
Version 0.2.5 released.
