### ISSUE TITLE
With connection, after connect means the connection is always available except disconnect with close() method?

### ISSUE THREAD

**Issue by flyly0755** [mymarilyn/clickhouse-driver#343]
Check with doc, Clickhouse-driver does not yet implement a connection pool.
In my project, i want to use long connection, means everytime to query data from clickhouse, use the same connection.
So i don't need to create connection every time before query data for better perfermence.

I want to check whether after connect with code as follows:
```python
from clickhouse_driver import connect
uri = f"clickhouse://{user}:{password}@{database_server}"
conn = connect(uri)
```
There is some heartbeat mechanism between clickhouse server and python client, will keep the conn always useable except some server end exception(for example server doesn't response client ping request within a certain period of time and more than a certain ping times).
And i can always use this connection to query data?

Then how about cursor, i can always use the same cursor if i don't manually close it with cursor.close() method?
```python
cursor = conn.cursor()
```
or the cursor maybe out of date, so need using  conn.cursor() method again to get a new cursor for the new query?

**Comment by xzkostyan** [comment]
Hi.

> There is some heartbeat mechanism between clickhouse server and python client, will keep the conn always useable except some server end exception(for example server doesn't response client ping request within a certain period of time and more than a certain ping times).

There is heartbeat mechanism (ping packets) only during particular query. There is no heartbeat mechanism between queries.

> And i can always use this connection to query data?

If connection fails the failed connection closes and the new one opens.

> Then how about cursor, i can always use the same cursor if i don't manually close it with cursor.close() method?

Internally each cursor uses it's own physical connection to server.
