### ISSUE TITLE
Support installing clickhouse-driver[numpy] via conda

### ISSUE THREAD

**Issue by zbs** [mymarilyn/clickhouse-driver#345]
Currently, conda-forge only contains clickhouse-driver, but it would be nice to install `clickhouse-driver[numpy]` from conda. If one desires this, they need to install via pip, which is undesirable.

**Comment by xzkostyan** [comment]
Hi.

I'm not familiar with conda-forge. Feel free to submit PR.

**Comment by zbs** [comment]
It's not a source code change. Conda is an alternative package manger to pip. It looks like the base `clickhouse-driver` was already uploaded ([link](https://anaconda.org/conda-forge/clickhouse-driver)). I cannot upload `clickhouse-driver[numpy]` as I am not the project maintainer.

**Comment by xzkostyan** [comment]
If it's conda-related issue you can post it here https://github.com/conda-forge/clickhouse-driver-feedstock/issues.

`clickhouse-driver[numpy]` is not different package. This is instruction for pip to install extra dependencies.
