### ISSUE TITLE
Column type JSON not supported

### ISSUE THREAD

**Issue by rejochandran** [mymarilyn/clickhouse-driver#346]
ClickHouse introduced JSON fields in data can be directly stored as [JSON](https://clickhouse.com/docs/en/sql-reference/data-types/json/)

 However, when we try to load the field using clickhouse-driver, it fails with error
`clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type Object('json')`

This is probable as support for `JSON` columns has not been introduced yet. ref [`create_column_with_options`](https://github.com/mymarilyn/clickhouse-driver/blob/26a4f11c66d02ecd014296f78c66cc80d4b4b3ea/clickhouse_driver/columns/service.py#L77)

**To Reproduce**
1. Create table with a column type JSON
```
CREATE TABLE myTable
(
    myJSONField JSON
)
ENGINE = Memory
```
2. Try inserting a JSON object
```
client.execute(
        "INSERT INTO myTable (myJSONField) VALUES",
        [{"myJSONField": '"foo":"bar"'}],
    )
```

**Expected behavior**
clickhouse-drive to detect JSON column type and write the data to the field

**Versions**

- clickhouse-driver 0.2.4
- ClickHouse server 22.6.1.1985
- Python 3.9.13

Will try to create a PR for the new type.
Please let me know if there is a workaround to resolve this

**Comment by xzkostyan** [comment]
Hi.

There is already a request for this feature: #300.
