### ISSUE TITLE
Would it be possible to update the PyPi source tarball following the re-cythonization?

### ISSUE THREAD

**Issue by aris-aiven** [mymarilyn/clickhouse-driver#349]
Hi,

As per the title, since the C extension has been re-cythonize it would be great if the updated source code were on PyPi.

AFAICT the `0.2.4` wheels have been updated to reflect the re-cythonization but not the related tarball.

Thanks for your time and for all the energy you're putting into this project!

**Comment by xzkostyan** [comment]
Hi.

Yes. I'll push new version in this weekend.

**Comment by xzkostyan** [comment]
Version 0.2.5 released.

**Comment by aris-aiven** [comment]
Awesome. Thanks a bunch @xzkostyan
