### ISSUE TITLE
Console log spam for `NumPy support is not implemented for`

### ISSUE THREAD

**Issue by dongyuzheng** [mymarilyn/clickhouse-driver#353]
`NumPy support is not implemented for` is too noisy.

I suggest changing it from WARNING to INFO

![image](https://user-images.githubusercontent.com/6127032/211929280-96bc860b-0908-4bc0-a10a-bd6cc36a711a.png)

**Comment by xzkostyan** [comment]
Hi.

You can configure logging level for particular logger.
