### ISSUE TITLE
avoid unnecessary timezone conversion when use_numpy=True

### ISSUE THREAD

**Issue by edwinwzhe** [mymarilyn/clickhouse-driver#354]
Hi guys

Thanks for the excellent work. We are prototyping with ClickHouse and it is pretty amazing!
When I was benchmarking. I noticed a potential improvement for reading when `use_numpy=True`. 
I will create a PR if it is a sensible change in your view.

Basically, the issue is that `NumpyDateTimeColumnBase.apply_timezones_after_read` always cast the numpy array to pandas DateTimeIndex, convert timezone and then back to numpy array. This operation is not cheap and it is not always necessary. In our use case, we use UTC everywhere, it will be a nice speedup if we could avoid unnecessary tz conversion. 

```python
def apply_timezones_after_read(self, dt):
    # should probably ensure self.local_timezone and self.timezone are of the same type for consistency
    timezone = self.timezone if self.timezone else get_timezone(self.local_timezone)

    if self.offset_naive and getattr(timezone, 'zone') != 'UTC':
        # tz convert makes a difference to the returned datetime only when timezone isnt UTC when offset_naive is True
        ts = pd.to_datetime(dt, utc=True).tz_convert(timezone)
        ts = ts.tz_localize(None)

        return ts.to_numpy(self.datetime_dtype)
    else:
        return dt
    
```

**Comment by xzkostyan** [comment]
Hi.

Feel free to make PR.

**Comment by edwinwzhe** [comment]
thanks for merging the PR @xzkostyan  I am looking forward to contribute to the project. 
thanks again for the great work!
