### ISSUE TITLE
Support time objects as query params

### ISSUE THREAD

**Issue by ghazi-git** [mymarilyn/clickhouse-driver#359]
Despite the lack of a time datatype in clickhouse, queries like
```sql
select *
from table
where formatDateTime(datetime_col, '%T') between '09:00:00' and '16:59:59'
```
or 
```sql
select *
from table
where formatDateTime(datetime_col, '%T') > '12:00:00'
```
seem to be working fine, so why not support passing time objects as query params to [`Client.execute`](https://github.com/mymarilyn/clickhouse-driver/blob/e1bd8bde6ee280fc8393ec326fbd5ad55e38717e/clickhouse_driver/client.py#L299)?

To implement that, it looks like updating [`escape_param`](https://github.com/mymarilyn/clickhouse-driver/blob/e1bd8bde6ee280fc8393ec326fbd5ad55e38717e/clickhouse_driver/util/escape.py#L31) to account for time objects should do the trick. Still, I wanted to check if there are any arguments against doing this.

**Comment by xzkostyan** [comment]
Hi.

There are no arguments against this feature. It was simply forgotten.

**Comment by ghazi-git** [comment]
got it, I'll submit a PR this weekend then
