### ISSUE TITLE
Iterator support

### ISSUE THREAD

**Issue by bertop89** [mymarilyn/clickhouse-driver#36]
Is there any way that the return of a SELECT query would be a row iterator instead of loading the whole query result into memory. Thank you!

**Comment by artinnok** [comment]
@xzkostyan hi!

i also need this feature - where i can read about contribution howto?

**Comment by xzkostyan** [comment]
@artinnok hi!

There is no contribution howto right now. You can create PR, follow current code style. Tests are required on any new feature. Feel free to ask any particular questions.  

The good point to dig into is `src.client.Client.store_query_result`. You should write something `iter_query_result` and `yield` row by row. Streaming should be incompatible with `columnar=True` option. May be it should be also incompatible with progress information at first.

The architecture of this client is similar with ClickHouse source code: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Client/Connection.cpp

**Comment by xzkostyan** [comment]
Hi!

Version [0.0.14](https://github.com/mymarilyn/clickhouse-driver/compare/0.0.13...0.0.14) with this feature was released.
