### ISSUE TITLE
EOFError: Unexpected EOF while reading bytes when using airflow operator

### ISSUE THREAD

**Issue by SehdiNassim** [mymarilyn/clickhouse-driver#367]
I'm using an airflow operator that uses **clickhouse-driver** to run execute queries and sometimes I get the EOFError: Unexpected EOF while reading bytes error. Knowing that i didn't change any piece of code or configuration in the clickhouse infrastructure. What would cause this error to be raised ?
PS: This exception is raised on queries that are usually executed successfully.

**Versions**

- clickhouse-driver 0.2.5
- ClickHouse server 23.1.3.5
- Python 3.7.12

Link to airflow operator: [https://github.com/bryzgaloff/airflow-clickhouse-plugin](https://github.com/bryzgaloff/airflow-clickhouse-plugin)

**Comment by xzkostyan** [comment]
On low level: this can happen when there is not enough data available for reading from socket.

On high level: I do not know what query emits this error.

Maybe this can be a network issue.
