### ISSUE TITLE
socket_timeout parameters

### ISSUE THREAD

**Issue by sam-leonid** [mymarilyn/clickhouse-driver#368]
Can I pass socket_timeout parameter in clickhouse-driver?
Or is there any analog?

Thank you!

**Comment by xzkostyan** [comment]
Hi.

You can pass 3 different timeouts for connection: https://clickhouse-driver.readthedocs.io/en/latest/api.html#clickhouse_driver.connection.Connection. See parameters description.

Example:

```python
Client.from_url('clickhouse://host?connect_timeout=1.2')
```
