### ISSUE TITLE
Tuple objects

### ISSUE THREAD

**Issue by pavel-zverkov** [mymarilyn/clickhouse-driver#372]
**Describe the bug**
clickhouse-driver cannot fulfill the request with `tuple` function

**To Reproduce**
For reproduce a table with one or two column is suitable for you.

Queries examples
`client.execute('SELECT tuple(column_1) FROM table')`
`client.execute('SELECT tuple(column_1, column_2) FROM table')`
`client.execute('SELECT (column_1,) FROM table')`
`client.execute('SELECT (column_1, column_2) FROM table')`

**Versions**

- clickhouse-driver == 0.2.5.
- ClickHouse server version > 22.6.8.35
- Python > 3.9

**Comment by xzkostyan** [comment]
What exception do you have?

```python
In [1]: import clickhouse_driver  
   ...:   
   ...: print(clickhouse_driver.__version__) 
   ...: client = clickhouse_driver.Client.from_url('clickhouse://localhost') 
   ...:  
   ...: print(client.execute('SELECT version()')) 
   ...: print(client.execute('SELECT tuple(number) FROM system.numbers limit 5')) 
   ...: print(client.execute('SELECT tuple(number, number) FROM system.numbers limit 5')) 
   ...:                                                                                                                                                                                       
0.2.5
[('23.3.1.2823',)]
[((0,),), ((1,),), ((2,),), ((3,),), ((4,),)]
[((0, 0),), ((1, 1),), ((2, 2),), ((3, 3),), ((4, 4),)]
```

**Comment by pavel-zverkov** [comment]
Some clarifications

the columns in query must have type 'LowCardinality(string) and table Engine - MergeTree

for one column I have infinite time for script execution
for two column - `tuple index out of range`

**Comment by xzkostyan** [comment]
Please provide snippet (CREATE TABLE, INSERT, SELECT) that throws this error.

**Comment by pavel-zverkov** [comment]
import clickhouse_driver

print(clickhouse_driver.__version__)
client = clickhouse_driver.Client.from_url('clickhouse://localhost')
print(client.execute('SELECT version()'))

# create table
create_query = '''CREATE TABLE IF NOT EXISTS test_low_cardinality_tuple 
                    (
                        `column_1` LowCardinality(String),
                        `column_2` LowCardinality(String),
                    )
                    ENGINE = MergeTree
                    ORDER BY column_1
                '''
client.execute(create_query)

# insert data
insert_query = 'INSERT INTO test_low_cardinality_tuple (column_1, column_2) VALUES'
VALUES = [('1', '2'), ('3', '4')]
client.execute(insert_query, VALUES)

# bad queries
test_query_1 = 'SELECT tuple(column_1) FROM test_low_cardinality_tuple'
test_query_2 = 'SELECT tuple(column_1, column_2) FROM test_low_cardinality_tuple'

# drop query
drop_query = 'DROP TABLE IF EXISTS test_low_cardinality_tuple'

# testing
try:
    print(client.execute(test_query_1))
    client.execute(drop_query)
except Exception as e:
    print(str(e))
    client.execute(drop_query)`
`
