### ISSUE TITLE
TLS certification validation not enforced

### ISSUE THREAD

**Issue by adamleko** [mymarilyn/clickhouse-driver#378]
**Describe the bug**
When creating a client with the `verify` option set to `True`, the SSL context is not configured to actually verify the server's remote certificate.

The create client context's purpose is set to `ssl.Purpose.SERVER_AUTH` and the `CERT_REQUIRED` option is correctly set, but [per the docs validation does not happen unless the check_hostnames flag is set](https://docs.python.org/3/library/ssl.html#ssl.CERT_REQUIRED):

> This mode is not sufficient to verify a certificate in client mode as it does not match hostnames. check_hostname must be enabled as well to verify the authenticity of a cert.

The [check_hostname](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname) docs say that this defaults to false unless you use one of the newer `PROTOCOL_TLS_{CLIENT/SERVER}` variants:

> The PROTOCOL_TLS_CLIENT protocol enables hostname checking by default. With other protocols, hostname checking must be enabled explicitly.

Those new options are only present in Python 3.10+ so it's probably not a good idea to switch from using `PROTOCOL_TLS`. Instead the `check_hostname` should be set to `True`.

Oddly enough, it appears that the `check_hostname` setting not only controls hostname verification, but _all_ certificate validation, at least with the versions of Python I tested against.

**To Reproduce**
Connect to a ClickHouse server using a self-signed TLS certificate with a client having the `secure` and `verify` options set to `True`. The connection succeeds and no certificate validation is attempted.

**Expected behavior**
The connect call should fail with an `CERTIFICATE_VERIFY_FAILED` exception.

**Versions**

- Python 3.8.13
- clickhouse-driver 0.2.6

**Comment by adamleko** [comment]
Any chance a new release can be cut with this fix sometime soon?

**Comment by xzkostyan** [comment]
You can install directly from github without waiting for new release: https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github

**Comment by xzkostyan** [comment]
You can install directly from github without waiting for new release: https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github
