### ISSUE TITLE
Trailing spaces break get_inner_columns_with_types

### ISSUE THREAD

**Issue by bryzgaloff** [mymarilyn/clickhouse-driver#385]
# Example of a wrong behaviour

`get_inner_columns_with_types` function (from `clickhouse_driver.columns.util` module) returns a wrong value when input `spec` argument has a trailing space character. For example:
* `get_inner_columns_with_types('test String')` (no trailing space) returns `[('test', 'String')]` which is correct.
* but `get_inner_columns_with_types('test String ')` (with a trailing space) returns `[('test String', '')]` (no type is detected) which is incorrect.

Real life example for trailing whitespace characters:
```python
ch_client.execute(
    external_tables=[{
        'name': 'ext',
        'structure': [('nested_field', '''Nested(
            test String
        )''')],  # here trailing whitespaces appear
        …
```

# Possible solution

Maybe a simple `spec.rstrip()` should help. At least it helps when calling `get_inner_columns_with_types('test String '.rstrip())` :)

As a part of a fix, I would also recommend replace `elif x == ' ':` with `elif x.isspace():`:

https://github.com/mymarilyn/clickhouse-driver/blob/ce712b5bc7a7900e844c7c8f99a1e3426aa326f7/clickhouse_driver/columns/util.py#L57

# Versions

`clickhouse_driver` version is 0.2.6

**Comment by xzkostyan** [comment]
Version 0.2.9 with this fix released.
