### ISSUE TITLE
Meta/Column names from query

### ISSUE THREAD

**Issue by digitalist** [mymarilyn/clickhouse-driver#39]
Meta/Column names...  how do I get them?

**Comment by xzkostyan** [comment]
You can execute following query `DESCRIBE TABLE mytable ` for example.

**Comment by digitalist** [comment]
Oh, I was too tired  to ask a complete question it seems.

What if I need to get column info from a select query?

Thanks

**Comment by xzkostyan** [comment]
Just use `with_column_types` flag. See tests for example: https://github.com/mymarilyn/clickhouse-driver/blob/70a68bd2ff1243f7224c6a19eb82ee80c67a7eca/tests/test_blocks.py#L55

**Comment by digitalist** [comment]
Thanks! 
I wonder though, there should be enormous overhead when dealing with large datasets? (Both in CPU and memory)

Wouldn't it be better to store meta about columns in a distinct object and set it only once (since column types/names do not change)

**Comment by digitalist** [comment]
ah, sorry, I see, it was a long dataset and I didn't notice column info.
 it's all ok.
Thank you!
