### ISSUE TITLE
mac m2 error

### ISSUE THREAD

**Issue by wangxinyu666666** [mymarilyn/clickhouse-driver#390]
an error like below on my mac
File "/lib/python3.10/site-packages/clickhouse_driver/block.py", line 2, in <module>
    from .reader import read_varint, read_binary_uint8, read_binary_int32
  File /lib/python3.10/site-packages/clickhouse_driver/reader.py", line 3, in <module>
    from .varint import read_varint
ImportError: dlopen(/lib/python3.10/site-packages/clickhouse_driver/varint.cpython-310-darwin.so, 0x0002): tried: '/lib/python3.10/site-packages/clickhouse_driver/varint.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by xzkostyan** [comment]
Try arm64 wheels for 0.2.6 from pypi.
