### ISSUE TITLE
Dynamic query with params substitution

### ISSUE THREAD

**Issue by zli06160** [mymarilyn/clickhouse-driver#393]
**clickhouse-driver==0.2.6** 

What I want is to write the query dynamically (different _where_ clauses):

> `./template_name.sql`
> ```sql 
> INSERT INTO TALBE_NAME 
> SELECT
> COL1, COL2, COL3
> FROM SOURCE_TALBE
> %(WHERE_CLAUSE)s            <= or (in airflow) {{ WHERE_CLAUSE }}
> ```

> `./script.py`
> ```python
> from clickhouse_driver import Client
> WHERE_CLAUSE = " " if blablabla else "WHERE COL1 IS NOT NULL"
> client.execute('template_name.sql', {"WHERE_CLAUSE": WHERE_CLAUSE})
> ```

- I found no similar test case in https://github.com/mymarilyn/clickhouse-driver/blob/master/tests/test_substitution.py
- I found no such substitution allowed in https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/util/escape.py

**clickhouse-driver** rendered `WHERE_CLAUSE` as a string `" "` (or `"WHERE COL1 IS NOT NULL"`), rather than ` ` (or `WHERE COL1 IS NOT NULL`), so it does not work.

Is there another way to have the two different final queries with only one `.sql` template? Can anyone confirm my example as a **bad practice**? 

Thanks!

**Comment by xzkostyan** [comment]
Hi.

How should we split substitution stings into tokens and distinct SQL-expression keywords from parameters in you case? Only parameters escaping are supported. You should construct correct expression by yourself.

**Comment by zli06160** [comment]
@xzkostyan Thanks! 👍  

I just want to use the _native_ method(s) of popular packages, if possible, in order to make my projects cleaner and easier to understand.  

I will close this git issue.
