### ISSUE TITLE
Support python 3.12 or whatever

### ISSUE THREAD

**Issue by costa** [mymarilyn/clickhouse-driver#394]
**Describe the bug**
Could not build wheels... or whatever

**To Reproduce**
`$ docker run --rm python:3.12 pip install clickhouse-driver[lz4]` fails

**Expected behavior**
`$ docker run --rm python:3.11 pip install clickhouse-driver[lz4]` works

**Versions**
latest

**Comment by wenbinf** [comment]
@xzkostyan thanks for the great work of this clickhouse driver package! 

plan to support python 3.12 in near future? or any pointer that we can fork & (quickly) modify code base on our end to support python 3.12?

Thanks!

**Comment by xzkostyan** [comment]
Hi. I've released wheels for 3.12 for version 0.2.6.

**Comment by wenbinf** [comment]
> Hi. I've released wheels for 3.12 for version 0.2.6.

@xzkostyan Awesome! It worked!
