### ISSUE TITLE
Code:50. Unknown type Bool

### ISSUE THREAD

**Issue by anikey7531** [mymarilyn/clickhouse-driver#399]
Hi.
I get an error when trying to insert a value of type bool
`
client = Client(ip,password=pass,settings={"use_numpy":False})
df=pd.DataFrame({ "b1":[True,False] })

df.to_dict('records') 

client.execute(f'INSERT INTO tmp.t1 (b1) VALUES', df.to_dict('records') )

`

`90     return cls(**column_options)
     92 except KeyError as e:
---> 93     raise errors.UnknownTypeError('Unknown type {}'.format(e.args[0]))

UnknownTypeError: Code: 50. Unknown type Bool`

if i use method insert_dataframe get error too

- Version of package with the problem.
- ClickHouse server version. 23.3.1.2823
- Python version. 3.10

**Comment by xzkostyan** [comment]
Current version 0.2.7 doesn't have this problem. Bool support was added in 0.2.3 https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md#023---2022-02-07 and in 0.2.5 for numpy.
