### ISSUE TITLE
Set settings.limits

### ISSUE THREAD

**Issue by elrik75** [mymarilyn/clickhouse-driver#4]
Hi, thanks fro the previous patches about settings !
Now, according to 
  https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/Settings.h
  https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/Limits.h
Clickhouse also allows to set some limits like 'max_memory_usage' or 'max_execution_time' which can be very useful.

**Comment by xzkostyan** [comment]
Hi!

I've missed that limits can be specified for query too. I'll add limits applying.

**Comment by xzkostyan** [comment]
Hi!

This feature is ready https://github.com/mymarilyn/clickhouse-driver/commit/42f1f2dd8ed13428449624c3cf7af91632b3bff8 and will be in future release.

**Comment by xzkostyan** [comment]
Hi!

0.0.6 version with this feature [is released](https://pypi.python.org/pypi?:action=display&name=clickhouse-driver&version=0.0.6).
