### ISSUE TITLE
Using both client-side and server-side binding prevents using server-side binding

### ISSUE THREAD

**Issue by panthony** [mymarilyn/clickhouse-driver#410]
**Describe the bug**

Most of the SQL queries I have are dynamically generated, some parts of the query with user-provided values.

Unfortunately because of the usage of Interpolation in Python it forces me to escape every occurrences of '%' which I cannot do (or it would be way to cumbersome to every try safely).

And I can't rely on the server-side binding to work around this issue because the query will *always* go through the python formatting.

**To Reproduce**

```python
client = Client(host='localhost')

# or even empty params for that matter
client.execute(
  "select 'Number %' as category from system.numbers WHERE number < 5 LIMIT {max:Int32}",
   params={
      'max': 10
    }
)
```

**Expected behavior**

I should be able to choose to rely on server-side binding only to avoid the escaping problem that Interpolating brings.

**Versions**

- Version of package with the problem: 0.2.6
- ClickHouse server version: 23.12.2.59
- Python version: 3.8.16

**Comment by xzkostyan** [comment]
You can install latest master and use only server-side parameters:

```python
from clickhouse_driver import Client

c = Client('localhost', settings={'server_side_params': True})

c.execute(
  "select 'Number %' as category from system.numbers WHERE number < 5 LIMIT {max:Int32}",
   params={
      'max': 10
    }
)
```
