### ISSUE TITLE
use_client_time_zone doesn't return offset-aware datetime object

### ISSUE THREAD

**Issue by KineticCookie** [mymarilyn/clickhouse-driver#412]
**Describe the bug**
Not sure if it's intended, or a bug.  
Using `use_client_time_zone` setting doesn't return offset-aware datetime objects.

**To Reproduce**
Minimal piece of Python code that reproduces the problem.
```python
from clickhouse_driver import Client
import datetime
import pytz

client = Client(host='localhost', port='9000', compression='lz4', settings={'use_client_time_zone': True})
dt, tz = client.execute("SELECT now(), timezone()")[0]
```
returns

```
dt == datetime.datetime(2024, 1, 22, 14, 48, 56)
```

**Expected behavior**
I would expect it to contain tzinfo.

Example:
```python
dt, tz = client.execute("SELECT now(), timezone()")[0]

dt == pytz.timezone(tz).localize(dt) # ideally these would be the same

# (datetime.datetime(2024, 1, 22, 14, 48, 56),   # <- current dt object
# datetime.datetime(2024, 1, 22, 14, 48, 56, tzinfo=<UTC>)) # <- expectation
```
**Versions**

- Version of package with the problem: 0.2.5
- ClickHouse server version.  22.8.15.23
- Python version. 3.11.6

**Comment by xzkostyan** [comment]
Hello.

Column has timezone only if it has type `DateTime(tz)` on server side.

**Comment by KineticCookie** [comment]
Hi @xzkostyan 
Thanks for the reply!
I understand that, but also kinda confused 😄 

I need offset-aware `datetime` and currently I get them via:
1. checking current server timezone via `SELECT timezone()`
2. using the time zone in my queries `SELECT toDateTime(dt, TIMEZONE)`

Which feels... unnecessarily complicated?

I found the flag `use_client_time_zone` that can setup timezones automatically, I that would be ideal for my use case.
However it still produces offset-naive datetimes:
https://github.com/mymarilyn/clickhouse-driver/blob/24e8b3592e29948294d3b7feaae6734154a225cc/clickhouse_driver/columns/datetimecolumn.py#L194-L197

Do you think that setting `offset-naive=False` there would be a good idea?
Or am I missing the point of that flag?

**Comment by xzkostyan** [comment]
If DateTime on server side has is timezone-aware (DateTime(T)) it should map into offfset-aware python datetime. The same thing takes place in psycopg2 for example.

`use_client_time_zone` setting has the same semantics with `clickhouse-client`

```python
$ clickhouse-client --help | grep use_client_time_zone
  --use_client_time_zone arg                                                           Use client timezone for interpreting DateTime string values, instead of adopting server timezone.
```
