### ISSUE TITLE
execute_iter loads all rows in RAM

### ISSUE THREAD

**Issue by shereneshka** [mymarilyn/clickhouse-driver#413]
**Describe the bug**
I'm using `execute_iter` to load large piece of data from db (>20M rows). I thought that due to `streaming` mode all chunks will be loaded sequentially, but instead of this, they are loaded simultaneously in RAM. That's why my web app is sometimes killed because of high memory consumption. 

**To Reproduce**
I've checked it with memory profiler, like this:
```
@profile
def exec_query():
    print('before execution', (datetime.now() - start).total_seconds())
    for i in client.execute_iter(query, settings={'max_block_size': 1000}):
        print('in progress', (datetime.now() - start).total_seconds())
```
And found out that memory consumption is growing until loop starts (all growth in `execute_iter` operation). It means that cursor is client-side, not server-side? 
<img width="825" alt="image" src="https://github.com/mymarilyn/clickhouse-driver/assets/32486985/6ae00a79-8f2a-4104-abef-38f20a907d81">
<img width="343" alt="image" src="https://github.com/mymarilyn/clickhouse-driver/assets/32486985/58b0495d-d859-49d4-a866-2f7742ac1c94">

**Versions**

- Version of package with the problem: 0.2.5
- ClickHouse server version: 23.8.4.69
- Python version: 3.9.6

**Comment by xzkostyan** [comment]
Hi.

Cursor is client-side. Currently protocol doesn't offer server-side cursors. The advantage of client-side cursor  is in datatypes parsing. Data is parsed block by block.

**Comment by shereneshka** [comment]
@xzkostyan thanks!
