### ISSUE TITLE
Unexpected packet message

### ISSUE THREAD

**Issue by rupamar** [mymarilyn/clickhouse-driver#419]
**Describe the bug**
Get an  exception whille connecting.

**To Reproduce**
Minimal piece of Python code that reproduces the problem.
client = Client(
            host=self.db_config.host,
            user=self.db_config.user,
            database=self.db_config.db,
            port=8123
            # settings={'use_numpy': True}
        )
client.execute('SHOW DATABASES')

**Expected behavior**
List of databases

**Versions**
ClickHouse server version:  23.9.1.1854
clickhouse-driver:0.2.7
Python: 3.10.8

**Comment by xzkostyan** [comment]
Use 9000 port. 8123 port used for http communication.
