### ISSUE TITLE
Extended support of IPv4 and IPv6 column types

### ISSUE THREAD

**Issue by Matt-Texier** [mymarilyn/clickhouse-driver#43]
Hi,

I am afraid to come with a form of specific request here. I opened this issue last week on Yandex/clickhouse repository: https://github.com/yandex/ClickHouse/issues/2605. It was about issues with support of specific column and types to store IPv4 and IPv6 data.

I didn't get any sort of positive answer from them... at least short term.

I was wondering if it could make sense to develop a form of additional types in your code such that column named IPv4_... or IPv6_... benefits from a specific behaviour. the idea would be to apply conversion function in you code and introduce those column as type INET (similar to postGRESQL) : https://www.postgresql.org/docs/9.1/static/datatype-net-types.html.

By having this feature, This type could be handled by upper layers like your SQLAlchemy driver and related UI and Frontend.

Does it sounds like something doable / acceptable ?

Thanks Matthieu.

**Comment by xzkostyan** [comment]
Hello!

This is a point to discuss, but in SQLAlchemy wrapper. Types coercing can be done via sqlalchemy's pre-post processors. What functions do you need for these types? Or you just need types coercion?

Please note, that without ClickHouse server support functions will be with very limited.

**Comment by Matt-Texier** [comment]
Hi thanks for you reply,

Here is a more detailed description of the need:

# Today's support of IPv4 and IPv6 storage in clickhouse:
## storage
Clickhouse allows to store IPv4 in a UINT32 field and IPv6 into a fixed string of 16 bytes. When you upload meta data in superset (frontend UI using SQLAlchemy), it comes as type UINT32 and type string. IPv4 is not human readable and IPv6 is even worth as it comes with none UTF-8 string so it gets just broken.

## conversion
In order to solve this issue, clickhouse propose conversion function: http://clickhouse-docs.readthedocs.io/en/latest/functions/ip_address_functions.html
This is better than nothing but as there is not specific types, it is hard to know when to apply those conversion and also where to apply it to avoid breaking this specific none UTF-8 string which is in fact a binary format of an IPv6.

# How to fixe it
What would be ideal is to emulate what is done in postGRESQL. They do have specific types for IPv4 and IPv6 that they call type INET. Behind the scene, the apply the same kind of conversion function. From string to binary, they detect if the ip address is an IPv4 or an IPv6 depending if the find '.' or ':' bytes in the string. In the other direction, they just rely on data type (4 or 16 bytes long) to apply the conversion from binary to human readable string. 

# Where we are today
We did spend some cycles to investigate where this could be done. Clickhouse guys don't see any mater of urgency to support it and see this as more mid long term feature... In our use case (IP telemetry), we do need it. 
Making a workaround the UI is very ugly as it makes something specific to a backend in a UI which is suppose to be generic ... As such the best place is probably in your driver or in your SQLAlchemy driver. We are not super familiar with those framework but we do need it and are ready to work on it ... if you could give us some help on code to looks at, we can try to do it and propose you a PR ?  

Hope it makes things clearer,
Kind regards,
Matthieu.

**Comment by Matt-Texier** [comment]
Some investigation are done by clickhouse development team to add new types, I'll let you know once done

**Comment by xzkostyan** [comment]
Good news! Can you post some links to issues/PRs in CH repo?

**Comment by xzkostyan** [comment]
@Matt-Texier good news. IPv4 and IPv6 types were implemented in ClickHouse and in driver: https://github.com/mymarilyn/clickhouse-driver/pull/73

**Comment by Matt-Texier** [comment]
@xzkostyan Thanks for the update. It has been a join effort between Altinity implementing its support based on SQL domains (https://github.com/yandex/ClickHouse/pull/3669) in clickhouse and @AchilleAsh giving me some precious help on projects we are working on together and yourself 👍 !
It will be of great help for networking use cases ...
