### ISSUE TITLE
Error when setting tcp_keepalive

### ISSUE THREAD

**Issue by sean-kates** [mymarilyn/clickhouse-driver#432]
**Describe the bug**
When setting the tcp_keepalive parameter to a tuple of floats, we get this error:

`TypeError: a bytes-like object is required, not 'float'`

**To Reproduce**
Setting tpc_keepalive to this:
```
return clickhouse_driver.Client(
      user=user,
      password=password,
      host=host,
      port=port,
      secure=secure,
      send_receive_timeout=3000000,
      connect_timeout=10,
      tcp_keepalive=(60.5, 5.1, 2),
      settings_is_important=True
}
```

**Expected behavior**
Documentation states that tcp_keepalive should be a tuple of floats, but it won't accept them.
https://clickhouse-driver.readthedocs.io/en/latest/features.html#tcp-keepalive

**Versions**

clickhouse_driver=0.2.7
ClickHouse server version=24.1.2.10900
Python version=3.9.12

**Comment by xzkostyan** [comment]
Hi. It seems all three parameters are integer https://linux.die.net/man/7/tcp
