### ISSUE TITLE
UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server host:port (expected Hello or Exception, got Unknown packet)

### ISSUE THREAD

**Issue by proevgenii** [mymarilyn/clickhouse-driver#436]
**Describe the bug**
I got an error while trying to run query:
```
UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server host:port (expected Hello or Exception, got Unknown packet)
```
**To Reproduce**
I use http poxy
```
from clickhouse_driver import Client
client_default = Client(host, user = login, password = password, port=port)
client_default.query_dataframe("SHOW DATABASES")
```

**Expected behavior**
Documentation says that it is possible to use http protocol:

> ClickHouse server provides two protocols for communication:
> HTTP protocol (port 8123 by default);
> Native (TCP) protocol (port 9000 by default).

**Versions**
clickhouse_driver==0.2.7

**Comment by xzkostyan** [comment]
Hi.

This note is about ClickHouse server, not python clickhouse-driver. HTTP protocol is not supported in this driver.
