### ISSUE TITLE
Extract Clickhouse URL parsing into a separate function

### ISSUE THREAD

**Issue by selevit** [mymarilyn/clickhouse-driver#438]
Hi, and thanks for this amazing library.

Currently, `Client` has a `from_url` static method that creates a client from a URL like `clickhouse://user:pass@host/db`. 

Would be great to provide an API for url parsing, so it's possible to use it with third-party tools, having the same format that `clickhouse_driver` accepts.

**Comment by xzkostyan** [comment]
Hi.

Can you provide example of your case?

**Comment by xzkostyan** [comment]
Version 0.2.9 with this change released.
