### ISSUE TITLE
test for clickhouse-driver versions 0.2.7 and 0.2.8 fails on clickhouse 23.4

### ISSUE THREAD

**Issue by antip00** [mymarilyn/clickhouse-driver#442]
0.2.7 log: 
[test.log](https://github.com/user-attachments/files/16128907/test.log)
0.2.8 log:
[test.log](https://github.com/user-attachments/files/16128919/test.log)

seems that max_threads can't be more than 3072 in latest ClickHouse versions:
![image](https://github.com/mymarilyn/clickhouse-driver/assets/44409195/34d74ac3-3d7b-42b7-ae04-63069538ad61)
![image](https://github.com/mymarilyn/clickhouse-driver/assets/44409195/4d269ff9-8bbe-4d85-be29-58acaecabe80)

**Comment by xzkostyan** [comment]
Yes. It was fixed in master https://github.com/mymarilyn/clickhouse-driver/commit/233d09a41f59375c2c1a577d94ff28d03d1fcfdd

**Comment by antip00** [comment]
[test.log](https://github.com/user-attachments/files/16143514/test.log)
I have only this fail in master.

**Comment by xzkostyan** [comment]
Yes.

There is some certs magic for this test in docker: https://github.com/mymarilyn/clickhouse-driver/pull/421. This single test will fail no host without this magic.
