### ISSUE TITLE
Request: Client configuration file support

### ISSUE THREAD

**Issue by b-l-a-c-k-b-e-a-r-d** [mymarilyn/clickhouse-driver#46]
Request the the driver be able to load settings from a client configuration file similar to the `clickhouse-client`.  e.g.

`~/.clickhouse-client/config.xml`
```
<config>
    <user>default</user>
    <password>my_password</password>
</config>
```

This will remove the need to store credentials in code.

**Comment by xzkostyan** [comment]
You can easily write ini-wrapper for example: http://www.postgresqltutorial.com/postgresql-python/connect. XML wrapper will be a little more complicated. You can get config from any file format your project have.

Also I think it's bad idea to share the same config with different tool.
