### ISSUE TITLE
Insert hang with Clickhouse 24.11

### ISSUE THREAD

**Issue by PierreF** [mymarilyn/clickhouse-driver#464]
**Describe the bug**

When trying to insert data with Clickhouse version 24.11, the insert hang and never complete.

**To Reproduce**

Start Clickhouse 24.11 as described in documentation
```
$ docker run --rm -e "TZ=Europe/Moscow" -p 127.0.0.1:9000:9000 -p 127.0.0.1:9440:9440 --name test-clickhouse-server clickhouse/clickhouse-server:24.11
```

Follow step from README:
```
>>> from clickhouse_driver import Client
>>> client = Client('localhost')
>>> client.execute('SHOW TABLES')
[('test',)]
>>> client.execute('CREATE TABLE test (x Int32) ENGINE = Memory')
[]
>>> client.execute('INSERT INTO test (x) VALUES', [{'x': 100}])
[no response, it block]
```

**Expected behavior**

Insert work and don't hang.

**Versions**

- Version of clickhouse-driver tested:
  - `clickhouse-driver==0.2.9`
  - and latest commit on branch master: `-e git+ssh://git@github.com/mymarilyn/clickhouse-driver.git@8a4e7c5b99b532df2b015651d893a6f36288a22c#egg=clickhouse_driver` 
- ClickHouse server version: 24.11.1.2557
- Python version: 3.13.0

**Extra information**

The exact same steps works without hang if Docker image used is clickhouse/clickhouse-server:24.10

When I ctrl+c the insert, I got the following traceback (running on commit 8a4e7c5):
```
^CTraceback (most recent call last):
  File "<python-input-6>", line 1, in <module>
    client.execute('INSERT INTO test (x) VALUES', [{'x': 100}])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pierref/dev/clickhouse-driver/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
        query, params, external_tables=external_tables,
        query_id=query_id, types_check=types_check,
        columnar=columnar
    )
  File "/Users/pierref/dev/clickhouse-driver/clickhouse_driver/client.py", line 607, in process_insert_query
    rv = self.send_data(sample_block, data,
                        types_check=types_check, columnar=columnar)
  File "/Users/pierref/dev/clickhouse-driver/clickhouse_driver/client.py", line 665, in send_data
    self.receive_profile_events()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/pierref/dev/clickhouse-driver/clickhouse_driver/client.py", line 734, in receive_profile_events
    packet = self.connection.receive_packet()
  File "/Users/pierref/dev/clickhouse-driver/clickhouse_driver/connection.py", line 588, in receive_packet
    packet.type = packet_type = read_varint(self.fin)
                                ~~~~~~~~~~~^^^^^^^^^^
  File "clickhouse_driver/varint.pyx", line 62, in clickhouse_driver.varint.read_varint
    i = read_one()
  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
    self.read_into_buffer()
  File "clickhouse_driver/bufferedreader.pyx", line 237, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
    self.current_buffer_size = self.sock.recv_into(self.buffer)
KeyboardInterrupt
```

When enabling logging at debug level, I got the following logs when doing the insert:
```
DEBUG:clickhouse_driver.connection:Connecting. Database: . User: default
DEBUG:clickhouse_driver.connection:Connecting to localhost:9000
DEBUG:clickhouse_driver.connection:Connected to ClickHouse server version 24.11.1, revision: 54473
DEBUG:clickhouse_driver.connection:Query: INSERT INTO test (x) VALUES
DEBUG:clickhouse_driver.connection:Block "" send time: 0.000020
DEBUG:clickhouse_driver.streams.native:Writing column x
DEBUG:clickhouse_driver.connection:Block "" send time: 0.000183
```

I didn't see anything relevant in Clickhouse server log.

**Comment by icoric4** [comment]
Same problem, looks like no data is being passed to the CH server? were you able to solve it?

**Comment by AlekseyKanaev** [comment]
I have the same issue, maybe it makes sense to report it in main Clickhouse repo?

**Comment by sirfz** [comment]
Indeed, inserting a single row (e.g. `client.execute('INSERT INTO test (x) VALUES (%(x)s)', {'x': 100})` works but batch insert hangs. Works fine with clickhouse-connect though.

**Comment by AmirKhsrv** [comment]
I have the same issue. inserting hangs, but it works fine with clickhouse-connect. I've tried several versions of Clickhouse too and nothing changed.

**Comment by dkhrisanov** [comment]
Looks like it's a confirmed bug on the server side: https://github.com/ClickHouse/ClickHouse/issues/72798.

**Comment by AmirKhsrv** [comment]
@dkhrisanov 
Do you know of any version that does not have this issue? 
They said ```v24.11.1.1049``` is ok but I cannot find it in releases page.

**Comment by Shimada666** [comment]
I have same problem

**Comment by dkhrisanov** [comment]
Clickhouse released a new version today, which includes the fix for above mentioned problem.

**Comment by PierreF** [comment]
I confirm that I no longer have this issue with the latest clickhouse-server (24.12.1.1614). No change in Python code or Python dependencies, just changing the clickhouse-server version.

**Comment by ddorian** [comment]
This isn't fixed for `async insert` for me on (24.12.1.1614).

This works: 
```python
client.execute('INSERT INTO test (x) SETTINGS async_insert=1, wait_for_async_insert=1  VALUES (%(x)s)', {'x': 100})
```
This breaks:
```python
client.execute(
    "INSERT INTO test (x) SETTINGS async_insert=1, wait_for_async_insert=1  VALUES ", [{"x": 100}]
)
```

Worked on 24.10.x. clickhouse-driver==0.2.7

**Comment by AlekseyKanaev** [comment]
The issue is still present for me (24.12.1.1614)

**Comment by ddorian** [comment]
They fixed it in https://github.com/ClickHouse/ClickHouse/issues/72798#issuecomment-2563828178
