### ISSUE TITLE
Links related issues

### ISSUE THREAD

**Issue by nh1571** [mymarilyn/clickhouse-driver#49]
Do you need to explicitly close the connection using clickhouse_driver?

**Comment by xzkostyan** [comment]
Hi.

Connection with the server is established on the first query execution. Every successful query uses the same connection.

Connection is closed after query execution if any error/exception occurs. The next query initializes new connection.

So the is one connection is keept per each working `Client` instance. You can manually free resources by calling `.disconnect()`.
