### ISSUE TITLE
DBAPI Support

### ISSUE THREAD

**Issue by DeanThompson** [mymarilyn/clickhouse-driver#50]
Thanks for the hard working on this great project.

Does this driver already implement the [DBAPI](https://www.python.org/dev/peps/pep-0249/)? If not, do we have a plan?

**Comment by xzkostyan** [comment]
Hi,

Yes, PEP 249 support is in my plans. It's right after Tuple type support. But I don't have any estimations on this feature. May be by the end of the year. Or may be earlier.

This will really simplify many things.

All features that don't fit this PEP will be kept, but placed in `extras` module like psycopg2 do.

**Comment by xzkostyan** [comment]
@DeanThompson, good news. I've implemented DB API support. The latest version is unreleased yet, but you can try it from latest master. Documentation is available [here](https://clickhouse-driver.readthedocs.io/en/latest/dbapi.html).

Looking forward your feedback.
