### ISSUE TITLE
column/string value may be None NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by linuxgood1230** [mymarilyn/clickhouse-driver#51]
column/string value may be None 

  def try_encode(self, value):
        if not isinstance(value, bytes):
            return value.encode('utf-8')
        return value

**Comment by xzkostyan** [comment]
There is `None` check before actual column write:
```python
    # clickhouse_driver/columns/base.py:173
    def write_item(self, x, buf, check_item_type):
        if self.nullable and x is None:
            self._write_null(buf)
```

Also there is test for nullable strings: `tests.columns.test_string.StringTestCase.test_nullable`
