### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'execute_iter'

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#52]
Hi,

looks like there is no execute_iter method in version '0.0.10'.

from clickhouse_driver import Client

client = Client(host='localhost', port=2102, database='shard01')

settings = {'max_block_size': 100000}

rows_gen = client.execute_iter('select * from query.TCC_S1', settings=settings)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-1a29fcf8bbb2> in <module>()
      2 client = Client(host='localhost', port=2102, database='shard01')
      3 settings = {'max_block_size': 100000}
----> 4 rows_gen = client.execute_iter('select * from query.TCC_S1', settings=settings)

AttributeError: 'Client' object has no attribute 'execute_iter'

**Comment by xzkostyan** [comment]
Hi!

Yes, it's true. According to changelog https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md this feature was introduced in 0.0.14 release.

**Comment by xzkostyan** [comment]
Just *upgrade* version using pip.
