### ISSUE TITLE
Add Decimal type support

### ISSUE THREAD

**Issue by kszucs** [mymarilyn/clickhouse-driver#53]
Recent clickhouse have an experimental decimal type: https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-181213-2018-09-10

**Comment by xzkostyan** [comment]
Hi, @kszucs!

This support will re ready soon. [Branch with decimal type](https://github.com/mymarilyn/clickhouse-driver/commits/feature-decimal-type).

**Comment by kszucs** [comment]
Awesome, thanks @xzkostyan!
I'm updating the conda-forge recipes as well.
