### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#54]
Hi,

I can execute:

client.execute('SELECT * FROM test3')

or

client.execute('SELECT a, b, c FROM test3')

and I will get list of tuples (one tuple for each row), but I don't have column names.

Is it somehow possible to get all columns names (named tuple, or something) with the data itself, in order to simplify further data manipulation?

For example, after getting result set from client.execute('SELECT * FROM test3'), I have to manually find out all column names and than provide that information to the pandas dataframe.

Regards.

**Comment by xzkostyan** [comment]
Hi!

Sure, you can get names. See https://github.com/mymarilyn/clickhouse-driver/issues/39.

**Comment by ghuname** [comment]
Excellent. This library is better that I thought. Thanks and best regards.
