### ISSUE TITLE
Accessing rows_before_limit property through API

### ISSUE THREAD

**Issue by vanzi** [mymarilyn/clickhouse-driver#55]
The `BlockStreamProfileInfo.rows_before_limit` property is useful to get the rows count for pagination without running an extra query, but there does not seem to be any way to access it through the API (i.e. the client silently ignores the `PROFILE_INFO` packet).

As a workaround I hacked together a small change in `Client.receive_packet` where it saves the last `packet.profile_info` in the Client instance and we can use it like this:

    client = Client()
    rows = client.execute('SELECT ...')
    total_count = client.profile_info.rows_before_limit

So it's not pretty, but it seems to work fine. Anyway, I think it would make sense to have it in the main API without additional hacks, but I'm not sure what's the best place to put it in... Do you have any thoughts on that? Or perhaps are there any additional caveats that might have caused leaving this out of the API scope?

**Comment by xzkostyan** [comment]
Hi, @vanzi!

I think `Client` instance can store some data from the last query in the following way:

```python
client = Client(...)
rows = client.execute('SELECT ...')
total_count = client.last_query.profile_info.rows_before_limit
```
`last_query` should be property that updated after each query was run. When no queries were run it should be `None`. If any error occurs on query run this property should be reset to `None` 

Will you make PR?
