### ISSUE TITLE
How to Insert Date/DateTime from python list or tuple object?

### ISSUE THREAD

**Issue by Livenux** [mymarilyn/clickhouse-driver#58]
I have a list data type data like this:
``` python
[['2018-10-10', 600]]
``` 
table schema：
``` sql
create table example(
 TestDate Date,
 TestValue Int32
) engigne=TinyLog
```
When I use cllickhouse-driver insert data to table, a data type error has occurred:
``` 
Code: 53. Type mismatch in VALUES section. Expected Date got <class 'str'>: 2018-10-10 for column "TestDate".
```
How to slove it？Thanks

**Comment by xzkostyan** [comment]
Hi. You should insert `datetime.date` instance as date, not `str` instance.

**Comment by Livenux** [comment]
> Hi. You should insert `datetime.date` instance as date, not `str` instance.

Thanks, I solved it.Use a conversion function , convert the date string to date type of the list .
