### ISSUE TITLE
Conda forge feedstock

### ISSUE THREAD

**Issue by kszucs** [mymarilyn/clickhouse-driver#6]
Hi! 

I'm working on clickhouse backend for [ibis](https://github.com/ibis-project/ibis).
Ibis is installable from both pip and conda. I'd like to use clickhouse-driver, but currently `clickhouse-driver` and `clickhouse-cityhash` don't have conda packages.

I've already created the recipes, but [conda forge](https://conda-forge.org/) packages require maintainers. Would You please create the feedstocks?

Here are the recipes: https://github.com/kszucs/clickhouse-conda

**Comment by kszucs** [comment]
Resolved, thanks!

**Comment by xzkostyan** [comment]
Great job! Thank you!

**Comment by kszucs** [comment]
I thank You :) 
If You are interested we'll integrate clickhouse-driver with ibis in https://gitential.com
