### ISSUE TITLE
SELECT INTO OUTFILE

### ISSUE THREAD

**Issue by kasparrov** [mymarilyn/clickhouse-driver#60]
current version of driver ignore select into outfile? 
there are no difference between queries
`select * from log LIMIT 10000 INTO OUTFILE '/var/tmp/test123.csv' FORMAT TabSeparated`
and
`select * from log LIMIT 10000`

clickhouse-driver version 0.0.16

**Comment by xzkostyan** [comment]
Hi!

This driver reads data from ClickHouse as list of tuples. It writes to ClickHouse in the same way. There are a lot of possible formats as input/output. But the driver isn't focused on this feature. `FORMAT` clause is simply ignored. Psycopg2 for example cannot save directly to file too. It's not the task of driver.

You can write result processor that stores received data into file, json, xml and even pickle. Data preprocessing before insert can be written in the same way.
