### ISSUE TITLE
Feature 'format JSON' needed

### ISSUE THREAD

**Issue by jackpgao** [mymarilyn/clickhouse-driver#66]
Can you provide  'format JSON' as the clickhouse-client does?

**Comment by maiabdelqader** [comment]
This is important to provide. Any updates on this?

**Comment by xzkostyan** [comment]
I do not have any plans about implementing another formats.  

You can use pure `requests` to work with JSON format or you can write result [wrapper](https://clickhouse-driver.readthedocs.io/en/latest/misc.html#inserting-data-from-csv-file).
