### ISSUE TITLE
Unable to Insert data to tables

### ISSUE THREAD

**Issue by Lakshmisowmya** [mymarilyn/clickhouse-driver#70]
I am trying to automate the database access using python script script.py

from clickhouse_driver import Client
import json
import sys

def ch():

    client = Client('localhost')
    query = sys.argv[1]
    cmdp = client.execute(query)
    jsonoutput= json.dumps(cmdp)
    print(jsonoutput)
ch()

DATA Insertion in below format is not working 
>python script.py  'INSERT INTO arrays_test  VALUES [["Hello", [1, 2]], ["World", [3, 4, 5]], ["Goodbye", []], ["Hellotest", [1, 2]], ["Worldtest", [3, 4, 5]], ["Goodbyetest", []]]'

 Other queries as below are working
> python script.py "show tables" - works
>python script.py "select * from table" - works
>python script.py "CREATE TABLE test (s String, arr Array(UInt8)) ENGINE = Memory" - works
 
 Any help on this?

**Comment by xzkostyan** [comment]
See docs: https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#inserting-data
