### ISSUE TITLE
Type bytes as parameter in select-query

### ISSUE THREAD

**Issue by heyciao** [mymarilyn/clickhouse-driver#71]
Hi

I totally don't understand how I'm supposed to handle parameters of type "bytes" in a select query (but works perfectly when executing an "insert into XXX values...", maybe because in such cases I pass a "list" of "bytes"?).

Example (I tried to simplify it as much as possible):
This works fine...

`listtuplesResult = self.dbHandle.execute("select %(parm1)s",{"parm1":'hello there'}, settings={'strings_as_bytes': True})`

...and I get back a nice "bytes"-variable containing the same characters, but as soon as I make the string become "bytes" like this (I just add "b" before the string "hello there")...

`listtuplesResult = self.dbHandle.execute("select %(parm1)s",{"parm1":b'hello there'}, settings={'strings_as_bytes': True})`

...the code crashes returning the following error:
```
SQL "select %(parm1)s" failed with the following error:Code: 62.
DB::Exception: Syntax error: failed at position 9: 'hello there'. Expected one of: GROUP BY, ORDER BY, AS, PREWHERE, AND, OR, UNION ALL, IS, BETWEEN, NOT LIKE, LIKE, GLOBAL IN, IN, GLOBAL NOT IN, NOT IN, Comma, Dot, Arrow, QuestionMark, token, FROM, WITH, WHERE, SETTINGS, INTO OUTFILE, FORMAT, identifier, alias, HAVING, LIMIT. Stack trace:
```

Am I doing something very basic very wrong?
I reaaally have to perform a "select" using bytes (not strings, because the bytes that I'm using are random and I cannot encode them to e.g. any valid UTF-8 string).
I did look at the source code but I'm not a hacker and ultimately I got stuck in "util/escape.py" as I don't find there an "elif" that takes care about the binary types... . 
Thanks a lot

**Comment by xzkostyan** [comment]
Hm, let's start from `clickhouse-client`. Can this utility execute your query?

`SELECT %(parm1)s` query is sent to server as string, with every parameter placed to it's placeholder like `SELECT 'test'`.

What happen if string contains "unprintable" like '\n' or '\t' symbols? Can `clickhouse-client` execute this query properly?

And yes, you're right, it seems that `bytes` are not escaped properly now. Thanks.

**Comment by xzkostyan** [comment]
I've checked, bytes are escaped too:

```python
In [1]: from clickhouse_driver import Client

In [2]: client = Client('localhost')

In [3]: client.substitute_params('select %(parm1)s', {'parm1': b'hello there'})
Out[3]: "select b'hello there'"
```

**Comment by heyciao** [comment]
Thank you (I can confirm that your test using "substitute_params" works fine as well for me)
Summarized, that means that for some reason "substitute_params" can handle the parameter of type "binary", but "execute" cannot, right?

Just an info for anybody else that is affected as well by this problem:
as workaround I now create in python a hex string of the binary variable and in the SQL I hardcode everything and wrap the hex with "unhex":
`sSQL += "unhex('" + str(binascii.hexlify(<MY_HEX_STRING>))[2:][:-1] + "')"`

Cheers

**Comment by xzkostyan** [comment]
> Summarized, that means that for some reason "substitute_params" can handle the parameter of type "binary", but "execute" cannot, right?

Yep, that's it. `SELECT` query must be passed as string to ClickHouse server with parameters placed into their placeholders.

Can you emit your source query from `clickhouse-client`?

**Comment by heyciao** [comment]
> Can you emit your source query from clickhouse-client?

Sorry, I'm not sure what you mean?
My testcase is just this:
```
from clickhouse_driver import Client
client = Client('quad',database="internet16_clk",user=<myuser>,password=<mypwd>,settings={"strings_as_bytes": False})
client.execute("select %(parm1)s",{"parm1":'hello there'}, settings={'strings_as_bytes': True})
client.execute("select %(parm1)s",{"parm1":b'hello there'}, settings={'strings_as_bytes': True})
```
The first "execute" works, the second one fails.

**Comment by xzkostyan** [comment]
Sorry, maybe I was not so clear.

The original question was: can you execute substiuted query `SELECT '%some_unprintable_string%'` in `clickhouse-client` console utility?

If it's possible then bytes not string should be send to ClickHouse server.
