### ISSUE TITLE
how to do do dynamic DDL?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [mymarilyn/clickhouse-driver#78]
The following code fails. My intention is to use something this in a loop using a list of table names.

What is the right way to do this?

```
r1 = client.execute('DROP TABLE IF EXISTS %(table)s', {'table': 'iris'})
```
The error is:

```
DB::Exception: Syntax error: failed at position 26: 'iris'. Expected identifier.
```

**Comment by xzkostyan** [comment]
Hi.

Well it seems that driver do string escaping. And emits `DROP TABLE IF EXISTS "iris"` statement. You can use pure statement without parameters right now.

**Comment by smartinsightsfromdata** [comment]
Let me explain with a bit more code my use case:

```
result = client.execute('show tables')              # get all tables of a particular database
res = [item[0] for item in result]                  # unpack the tuples
f result:                                           # make sure the result is not zero
    for r in res:
        params = {'x': r}
        print(params)
        r1 = client.execute('DROP TABLE IF EXISTS %(x)s', params)
        print(r1)
```
But the above code doesn't work (not surprising, as the symple `client.execute('DROP TABLE IF EXISTS %(table)s', {'table': 'iris'})` doesn't work.

This is just an example.  I may want to drop all table starting as customer_ for example etc.

Is the above possible, or planned for the future?

**Comment by xzkostyan** [comment]
You should use `r1 = client.execute('DROP TABLE IF EXISTS {}'.format(r))`.

This error happen now because

```python
r1 = client.execute('DROP TABLE IF EXISTS %(x)s', params)
```

Produces following SQL:

```sql
DROP TABLE IF EXISTS 'test'
```

Query parser simply doesn't expect single quote.

The same error in psycopg2:

```python
import psycopg2
conn = psycopg2.connect("dbname='test' user='user' host='localhost' password='password'")
cur = conn.cursor()
cur.execute('DROP TABLE %(x)s', {'x': 'test'})  
conn.commit()
conn.close()

ProgrammingError                          Traceback (most recent call last)
<ipython-input-10-a7672e82e530> in <module>()
      2 conn = psycopg2.connect("dbname='marilyn_test' user='marilyn' host='localhost' password='marilyn'")
      3 cur = conn.cursor()
----> 4 cur.execute('DROP TABLE %(x)s', {'x': 'test'})
      5 conn.commit()
      6 conn.close()

ProgrammingError: syntax error at or near "'test'"
LINE 1: DROP TABLE 'test'
```

This exception emits by postgresql server not by psycopg2 library.
