### ISSUE TITLE
Last query’s profile info 

### ISSUE THREAD

**Issue by healiseu** [mymarilyn/clickhouse-driver#82]
Hi, is there an easy way to read 
* The number of rows in the result set, 
* the time passed, 
* and the average speed of query processing

that [ClickHouse command-line client][2] displays at the end of processing a query ?

```txt
For example:
21 rows in set. Elapsed: 2.172 sec. Processed 2.78 million rows, 33.33 MB (1.28 million rows/s., 15.34 MB/s.)
```
I have tried reading [query profile info][2] but I could only get
* rows, i.e. number of rows in the result set
* bytes of the result set ?

I am missing 3 more measurements
1. elapsed time
2. read_rows
3. read_bytes

#### Question:
How would you execute `client.last_query.profile_info` to get these three ?

BTW1: I can process the system.query_log but this is a cumbersome approach
BTW2: This could be a nice feature to have, i.e. adding an option to display profile info from `Client.execute()`

[1]: https://clickhouse-driver.readthedocs.io/en/latest/features.html#reading-query-profile-info
[2]: https://clickhouse.yandex/docs/en/interfaces/cli/

**Comment by xzkostyan** [comment]
Hi.

For receiving total rows you can now [execute query with progress info](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#selecting-data-with-progress-statistics) as workanound.

It's good point to add `read_rows`, `read_bytes` and `elapsed time` as well into `last_query`.

**Comment by xzkostyan** [comment]
This feature is in master now. You can install it [directly from github](https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github).

Changes are [reflected in docs](https://clickhouse-driver.readthedocs.io/en/latest/features.html#query-execution-statistics).

**Comment by healiseu** [comment]
@xzkostyan this is great, thanks for adding this feature. It's very useful and I am going to use it.

**Comment by healiseu** [comment]
Notice: As I write, the feature is in master but it has not been released yet, therefore I tried
`pip uninstall clickhouse-driver`
`Successfully uninstalled clickhouse-driver-0.0.19`

and I used the following command to install the development version
`pip install git+https://github.com/mymarilyn/clickhouse-driver@master#egg=clickhouse-driver`

And this is what I got from your master version:

```python
from clickhouse_driver import Client
ch = Client(host='localhost', database='TriaDB', port=9000, user='athan', password='triadb')

q = '''
SELECT uint, count(uint)
FROM 
( 
  SELECT (rand() % 7000) + 1 AS uint
  FROM numbers(100000000) 
) 
GROUP BY uint
ORDER BY uint ASC
LIMIT 10
'''
ch.execute(q)

Out[2]: 
[(1, 14182),
 (2, 14438),
 (3, 14284),
 (4, 14288),
 (5, 14262),
 (6, 14401),
 (7, 14271),
 (8, 14079),
 (9, 14115),
 (10, 14108)]

qinfo = [ ch.last_query.progress.rows, 
              ch.last_query.progress.bytes, 
              ch.last_query.progress.total_rows,
              ch.last_query.elapsed ]  

print(f'read_rows:{qinfo[0]}, \nbytes:{qinfo[1]}, \ntotal_rows:{qinfo[2]}, \nelapsed_time:{qinfo[3]}')

read_rows:4063232, 
bytes:32505856, 
total_rows:0, 
elapsed_time:1.6895544528961182
```
Now if you compare this with the output from clickhouse-client
```sql
SELECT uint, count(uint)
FROM 
(
    SELECT (rand() % 7000) + 1 AS uint
    FROM numbers(100000000) 
) 
GROUP BY uint
ORDER BY uint ASC
LIMIT 10

┌─uint─┬─count(uint)─┐
│    1 │       14212 │
│    2 │       14283 │
│    3 │       14100 │
│    4 │       14035 │
│    5 │       14257 │
│    6 │       14189 │
│    7 │       14275 │
│    8 │       14039 │
│    9 │       14299 │
│   10 │       14254 │
└──────┴─────────────┘

10 rows in set. Elapsed: 1.571 sec. Processed 100.01 million rows, 800.06 MB
```
---
**For this example the only reasonable measurement is the elapsed time 1.571 vs 1.689** 
---

Now If I try your example
```sql
SELECT max(number)
FROM numbers(1000000) 

┌─max(number)─┐
│      999999 │
└─────────────┘

1 rows in set. Elapsed: 0.015 sec. Processed 1.05 million rows, 8.39 MB
```
But with clickhouse-driver I get
```python

ch.execute('SELECT max(number) FROM numbers(1000000)')
Out: [(999999,)]

qinfo = [ ch.last_query.progress.rows, 
              ch.last_query.progress.bytes, 
              ch.last_query.progress.total_rows,
              ch.last_query.elapsed ]  

print(f'read_rows:{qinfo[0]}, \nbytes:{qinfo[1]}, \ntotal_rows:{qinfo[2]}, \nelapsed_time:{qinfo[3]}')

read_rows:1048576, 
bytes:8388608, 
total_rows:1000000, 
elapsed_time:0.009245634078979492
```
It looks like read_rows corresponds to processed rows measurement in clickhouse-client. The number of bytes and elapsed time seems right, although I would expect the second to be longer for the python client.

**Comment by xzkostyan** [comment]
Thanks for feedback.

Yes, `read_rows` is specified rows that was read by ClickHouse server. May be is better to rename it to `processed_rows`.

**Comment by healiseu** [comment]
OK then I assume your bytes is the size of processed rows and total_rows is rows returned in the result set, is that right ? But in the first nested query, there is a big difference of progress info with that returned from clickhouse-client why ?

**Comment by xzkostyan** [comment]
Sorry for long response.
There was a [bug](https://github.com/mymarilyn/clickhouse-driver/commit/3cc8c719072a1c6e55f63d94d6a2018d79120128) in progress calculation. Progress from each packet should be accumulated.

```python
In [1]: from clickhouse_driver import Client
   ...: c = Client('localhost')
   ...: c.execute('SELECT x FROM (SELECT number AS x FROM numbers(100000000)) ORDER BY x ASC LIMIT 10')
   ...: p = c.last_query.progress
   ...: print(f'read_rows:{p.rows}, \nbytes:{p.bytes}, \ntotal_rows:{p.total_rows}, \nelapsed_time:{c.last_query.elapsed}')
   ...: 
read_rows:100007936, 
bytes:800063488, 
total_rows:100000000, 
elapsed_time:0.18621039390563965
```

There numbers are similar with `clickhouse-client`'s:

```
SELECT 
    uint, 
    count(uint)
FROM 
(
    SELECT (rand() % 7000) + 1 AS uint
    FROM numbers(100000000) 
) 
GROUP BY uint
ORDER BY uint ASC
LIMIT 10

┌─uint─┬─count(uint)─┐
│    1 │       14218 │
│    2 │       14012 │
│    3 │       14239 │
│    4 │       14032 │
│    5 │       14299 │
│    6 │       14199 │
│    7 │       14253 │
│    8 │       14346 │
│    9 │       14375 │
│   10 │       14187 │
└──────┴─────────────┘

10 rows in set. Elapsed: 1.211 sec. Processed 100.01 million rows, 800.06 MB (82.56 million rows/s., 660.45 MB/s.) 
```

**Comment by healiseu** [comment]
I have just found time to test it.

```python
ch.execute(q)
print(f'\nrows in set:{ch.last_query.profile_info.rows}',
      f'\nelapsed time:{ch.last_query.elapsed}',
      f'\nprocessed rows:{ch.last_query.progress.rows}',
      f'\nbytes:{ch.last_query.progress.bytes}',
      f'\ntotal_rows:{ch.last_query.progress.total_rows}')
```
and my output is

```text
rows in set:10 
elapsed time:1.6352882385253906 
processed rows:100007936 
bytes:800063488 
total_rows:100000000
```
another example

```python
ch.execute(q)
print(f'\nrows in set:{ch.last_query.profile_info.rows}',
      f'\nelapsed time:{ch.last_query.elapsed}',
      f'\nprocessed rows:{ch.last_query.progress.rows}',
      f'\nbytes:{ch.last_query.progress.bytes}',
      f'\ntotal_rows:{ch.last_query.progress.total_rows}')
```

and the output is

```text
rows in set:1 
elapsed time:0.011972427368164062 
processed rows:1048576 
bytes:8388608 
total_rows:1000000
```

@xzkostyan that really helps,

Can you explain briefly how Clickhouse calculates that number of processed rows and how it comes to be larger than the `total_rows` in these two queries ?

**Comment by xzkostyan** [comment]
Hi.

I'm not familiar with whole ClickHouse architecture but I think it's simple granularity alignment.

There is processing unit in ClickHouse that called 'block'. Block contains [particular](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Core/Settings.h#L48) [number](https://github.com/yandex/ClickHouse/blob/461c4919d3dc6a76424976697df5ba40ab8a0882/dbms/src/Core/Defines.h#L21) of rows. So, whole block is considered as "read".

**Comment by healiseu** [comment]
I have also tested last query info with the following MergeTree tables
```sql
DESCRIBE TABLE FloatOnSSD_SRC

┌─name──┬─type────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐
│ pk2   │ UInt8   │              │                    │         │                  │
│ pk1   │ UInt32  │              │                    │         │                  │
│ id    │ UInt64  │              │                    │         │                  │
│ value │ Float64 │              │                    │         │                  │
└───────┴─────────┴──────────────┴────────────────────┴─────────┴──────────────────┘

DESCRIBE TABLE FloatNDXOnSSD_8192

┌─name─┬─type──────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐
│ val  │ Float64       │              │                    │         │                  │
│ id   │ UInt64        │              │                    │         │                  │
│ pk   │ Array(UInt32) │              │                    │         │                  │
└──────┴───────────────┴──────────────┴────────────────────┴─────────┴──────────────────┘
```
Both tables contain 50M rows but the second one is ordered by val therefore if we ran the following query on the source table
```python
cql.execute('SELECT * from FloatOnSSD_SRC where value between 200000 and 300000')

print(f'\nrows in set:{cql.last_query.profile_info.rows}',
      f'\nelapsed time:{cql.last_query.elapsed}',
      f'\nprocessed rows:{cql.last_query.progress.rows}',
      f'\nbytes:{cql.last_query.progress.bytes}',
      f'\ntotal_rows:{cql.last_query.progress.total_rows}')
```
the output we get is
```txt
rows in set:37 
elapsed time:0.3818497657775879 
processed rows:50000000 
bytes:400000481 
total_rows:50000128
```
and if we ran the same query on the indexed table
```python
cql.execute('SELECT * from FloatNDXOnSSD_8192 where val between 200000 and 300000')
print(f'\nrows in set:{cql.last_query.profile_info.rows}',
      f'\nelapsed time:{cql.last_query.elapsed}',
      f'\nprocessed rows:{cql.last_query.progress.rows}',
      f'\nbytes:{cql.last_query.progress.bytes}',
      f'\ntotal_rows:{cql.last_query.progress.total_rows}')
```
the output we get is 

```txt
rows in set:37 
elapsed time:0.004071474075317383 
processed rows:4224 
bytes:135168 
total_rows:8192
```
I compared the output with that of clickhouse-client and it seems to be correct. I cannot verify the `total_rows` and I cannot understand how it differs from the processed rows (see also my question above).

**Comment by healiseu** [comment]
I have also found the following corner case:
```sql
EXISTS TABLE XYZ

┌─result─┐
│      1 │
└────────┘

DROP TABLE XYZ
Ok.
0 rows in set. Elapsed: 0.011 sec.
```
Executing the same query with clickhouse-driver
```python
ch.execute('DROP TABLE XYZ')
[]
```
But if you try
```python
ch.last_query.profile_info.rows

AttributeError: 'NoneType' object has no attribute 'rows'
```

**Comment by xzkostyan** [comment]
@healiseu thanks, corner cases with DDL and INSERTs are fixed in master right now.

I thing the explanation of you case with presorted by `val` table is quite simple. ClickHouse has `index_granularity` setting of *MergeTree tables. From ClickHouse [docs](https://clickhouse.yandex/docs/en/single/):

```
For each data part, ClickHouse creates an index file that contains the primary key value for each index row ("mark"). Index row numbers are defined as n * index_granularity. The maximum value n is equal to the integer part of dividing the total number of rows by the index_granularity. For each column, the "marks" are also written for the same index rows as the primary key. These "marks" allow you to find the data directly in the columns.
```

So the second query use just only one index mark (8192 rows).
Rows info from the first query tells us about fact that the whole table (50M rows) was actually read for query processing.

I can't summarize these facts because sometimes `total rows` are less than `processed rows`. For example in case of data-generators like `numbers(1000000)`.

But I think the main idea is:
* total rows -- rows (aligned to blocks or marks for read performance) read from disk by server for query processing.
* processed rows -- subset of total rows from that was read from blocks

[Progress.cpp](https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/Progress.cpp) is a good start point for digging into ClickHouse sources.

**Comment by xzkostyan** [comment]
@healiseu version 0.1.0 with fix DDL is uploaded on pypi.

Should we close this issue?

**Comment by healiseu** [comment]
@xzkostyan thank you for the info and the update, I have not found time to test the new version but I trust it will work, so I am closing the issue.
