### ISSUE TITLE
Insert with direct values in SQL hungs

### ISSUE THREAD

**Issue by mbasunov** [mymarilyn/clickhouse-driver#83]
Hello,
`
client = Client('localhost')
client.execute('CREATE TABLE test (x Int32) ENGINE = Memory')
client.execute('insert into test values (1)')
`
Insert query hungs.
But this workaround works:
`
client.execute('insert into test select 1')
`

Thanks.

**Comment by mbasunov** [comment]
PS 0.0.18

**Comment by xzkostyan** [comment]
Hi.

Yep, for inserting values you need to pass `data` argument for execute call: https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#inserting-data

This driver does not parse VALUES from query. See brief explanation in docs.
