### ISSUE TITLE
LowCardinality data type support

### ISSUE THREAD

**Issue by blubard** [mymarilyn/clickhouse-driver#88]
The issue #80 still prevails in 0.0.19 though it is closed.
`
clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type LowCardinality(String)
`
It is fixed in the master branch tough. When will the next versions be tagged?

**Comment by xzkostyan** [comment]
Hi.

New release will be published in the end of week.

**Comment by xzkostyan** [comment]
Version [0.0.20](https://pypi.org/project/clickhouse-driver/0.0.20/) is published.
