### ISSUE TITLE
Insert and fields with default value

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#90]
Hi,

if I create table as:

CREATE TABLE run_diff ( Customer String, Start_DateTime DateTime,  output_PortStatus String,  Start_Date Date DEFAULT toDate(Start_DateTime),  inserted_on DateTime DEFAULT now()) ENGINE = MergeTree() PARTITION BY Start_Date ORDER BY Start_Date SETTINGS index_granularity = 8192

and dataframe as:

nr_of_rows = 10

rd = pd.DataFrame({
    'Customer' : [random.choice(['A', 'B', 'C', 'D']) for cnt in range(nr_of_rows)],
    'Start_DateTime' : [prev_24h - datetime.timedelta(hours=2) + datetime.timedelta(hours=cnt) for cnt in range(nr_of_rows)], 
    'Status' : [random.choice(['WORKING', 'NOT_WORKING']) for cnt in range(nr_of_rows)],
})

If I try to insert dataframe to table with:

client.execute('"insert into run_diff values"', rd.values.tolist())

I get an error: ValueError: Expected 5 columns, got 3

If I add date (for Start_Date) and datetime (for inserted_on) columns into dataframe, insert is executed with no errors.
Why clickhouse_dirver expect values to be provided for columns with default values/functions?
Is this a bug or feature?

Regards.

**Comment by xzkostyan** [comment]
Hi, if you omit columns clause in query driver insert all the columns according to protocol. Server returns whole set of columns without default indicator.

You should specify columns:

```
client.execute('"insert into run_diff (Customer, Start_DateTime, Status) values"', rd.values.tolist())
```

**Comment by ghuname** [comment]
Thanks for an explanation.
