### ISSUE TITLE
How to handle nan values?

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#91]
Hi,

if I create a table:

CREATE TABLE group_issues_test (
	issue_name String
	,issue_title String
	,modified_date DATETIME DEFAULT now()
    ,Sign Int8 DEFAULT CAST(1, 'Int8')
	) 
    ENGINE = CollapsingMergeTree (Sign) 
    ORDER BY issue_name SETTINGS index_granularity = 8192

and than dataframe as:

df = pd.DataFrame([
    ['issue_name_1', 'issue_title_1', 1],  
    [None, 'issue_title_1', 1],  
    ['issue_name_1', np.nan, 1],  
    ['issue_name_1', 'issue_title_1', np.nan]])

![image](https://user-images.githubusercontent.com/15207713/58487252-8edd6780-8167-11e9-91ad-f423042a35b0.png)

when I try to insert with:
client.execute("""insert into group_issues_test (issue_name, issue_title, Sign) values""", df.values.tolist())

I get:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-a3a097b7e364> in <module>
----> 1 client.execute("""insert into group_issues_test (issue_name, issue_title, Sign) values""", df.values.tolist())

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in execute(self, query, params, with_column_types, external_tables, query_id, settings, types_check, columnar)
    200                 return self.process_insert_query(
    201                     query, params, external_tables=external_tables,
--> 202                     query_id=query_id, types_check=types_check
    203                 )
    204             else:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in process_insert_query(self, query_without_data, data, external_tables, query_id, types_check)
    349         sample_block = self.receive_sample_block()
    350         if sample_block:
--> 351             self.send_data(sample_block, data, types_check=types_check)
    352             packet = self.connection.receive_packet()
    353             if packet.exception:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in send_data(self, sample_block, data, types_check)
    373             block = Block(sample_block.columns_with_types, chunk,
    374                           types_check=types_check)
--> 375             self.connection.send_data(block)
    376 
    377         # Empty block means end of data.

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\connection.py in send_data(self, block, table_name)
    474             write_binary_str(table_name, self.fout)
    475 
--> 476         self.block_out.write(block)
    477         self.block_out.reset()
    478         logger.debug('Block send time: %f', time() - start)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\streams\native.py in write(self, block)
     39 
     40                 write_column(self.context, col_name, col_type, items,
---> 41                              self.fout, types_check=block.types_check)
     42 
     43         self.finalize()

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\service.py in write_column(context, column_name, column_spec, items, buf, types_check)
     82 
     83     try:
---> 84         column.write_data(items, buf)
     85 
     86     except column_exceptions.ColumnTypeMismatchException as e:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\base.py in write_data(self, items, buf)
     77             self._write_nulls_map(items, buf)
     78 
---> 79         self._write_data(items, buf)
     80 
     81     def _write_data(self, items, buf):

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\base.py in _write_data(self, items, buf)
     81     def _write_data(self, items, buf):
     82         prepared = self.prepare_items(items)
---> 83         self.write_items(prepared, buf)
     84 
     85     def write_items(self, items, buf):

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\stringcolumn.py in write_items(self, items, buf)
     25         for value in items:
     26             if not isinstance(value, bytes):
---> 27                 value = utf_8_encode(value)[0]
     28 
     29             write_varint(len(value), buf)

TypeError: utf_8_encode() argument 1 must be str, not None

`

How to handle this type of error?
Should I replace all string columns with None/np.nan with empty string (''), or...?

**Comment by xzkostyan** [comment]
Hi. First of all you should declate your column as `issue_title Nullable(String)`. It is not possible to insert null values into column without `Nullable()` modifier.

**Comment by ghuname** [comment]
Hi. If I can't have Nullable columns, what is suggested approach?


Also I have made the following experiment with Nullable column:

client.execute("""
drop table group_issues_test
""")

client.execute("""
CREATE TABLE group_issues_test (
	issue_name String
	,issue_title Nullable(String)
	,modified_date DATETIME DEFAULT now()
    ,Sign Int8 DEFAULT CAST(1, 'Int8')
	) 
    ENGINE = CollapsingMergeTree (Sign) 
    ORDER BY issue_name SETTINGS index_granularity = 8192
""")

df = pd.DataFrame([
    ['issue_name_1', 'issue_title_1'],  
    ['Issue_name_2', 'issue_title_2'],  
    ['issue_name_3', np.nan],  
    ['issue_name_4', 'issue_title_1']]
    , columns = ['name', 'title'])
df

![image](https://user-images.githubusercontent.com/15207713/58619889-193bdd80-82c6-11e9-817c-8d16c3dd750a.png)

df.dtypes

name     object
title    object
dtype: object

client.execute("""insert into group_issues_test (issue_name, issue_title) values""", df.values.tolist())

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-93-cbbb1e876a04> in <module>
----> 1 client.execute("""insert into group_issues_test (issue_name, issue_title) values""", df.values.tolist())

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in execute(self, query, params, with_column_types, external_tables, query_id, settings, types_check, columnar)
    200                 return self.process_insert_query(
    201                     query, params, external_tables=external_tables,
--> 202                     query_id=query_id, types_check=types_check
    203                 )
    204             else:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in process_insert_query(self, query_without_data, data, external_tables, query_id, types_check)
    349         sample_block = self.receive_sample_block()
    350         if sample_block:
--> 351             self.send_data(sample_block, data, types_check=types_check)
    352             packet = self.connection.receive_packet()
    353             if packet.exception:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\client.py in send_data(self, sample_block, data, types_check)
    373             block = Block(sample_block.columns_with_types, chunk,
    374                           types_check=types_check)
--> 375             self.connection.send_data(block)
    376 
    377         # Empty block means end of data.

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\connection.py in send_data(self, block, table_name)
    474             write_binary_str(table_name, self.fout)
    475 
--> 476         self.block_out.write(block)
    477         self.block_out.reset()
    478         logger.debug('Block send time: %f', time() - start)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\streams\native.py in write(self, block)
     39 
     40                 write_column(self.context, col_name, col_type, items,
---> 41                              self.fout, types_check=block.types_check)
     42 
     43         self.finalize()

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\service.py in write_column(context, column_name, column_spec, items, buf, types_check)
     82 
     83     try:
---> 84         column.write_data(items, buf)
     85 
     86     except column_exceptions.ColumnTypeMismatchException as e:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\base.py in write_data(self, items, buf)
     77             self._write_nulls_map(items, buf)
     78 
---> 79         self._write_data(items, buf)
     80 
     81     def _write_data(self, items, buf):

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\base.py in _write_data(self, items, buf)
     81     def _write_data(self, items, buf):
     82         prepared = self.prepare_items(items)
---> 83         self.write_items(prepared, buf)
     84 
     85     def write_items(self, items, buf):

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\clickhouse_driver\columns\stringcolumn.py in write_items(self, items, buf)
     25         for value in items:
     26             if not isinstance(value, bytes):
---> 27                 value = utf_8_encode(value)[0]
     28 
     29             write_varint(len(value), buf)

TypeError: utf_8_encode() argument 1 must be str, not float

As you can see, I got an error even with Nullable column.

Regards.

**Comment by ghuname** [comment]
Can you please explain why I am getting an error even with Nullable column as I have provided the example above?

**Comment by xzkostyan** [comment]
Every Nullable value is represented as `None`. You should use `None` instead of `np.nan`.

```python
In [4]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost')
   ...: client.execute('drop table if exists group_issues_test')
   ...: 
   ...: client.execute("""
   ...:     CREATE TABLE group_issues_test (
   ...:         issue_name String,
   ...:         issue_title Nullable(String),
   ...:         modified_date DATETIME DEFAULT now(),
   ...:         Sign Int8 DEFAULT CAST(1, 'Int8')
   ...:     )
   ...:     ENGINE = CollapsingMergeTree (Sign)
   ...:     ORDER BY issue_name SETTINGS index_granularity = 8192
   ...: """)
   ...: 
   ...: rows = [
   ...:     ['issue_name_1', 'issue_title_1'],
   ...:     ['Issue_name_2', 'issue_title_2'],
   ...:     ['issue_name_3', None],
   ...:     ['issue_name_4', 'issue_title_1']
   ...: ]
   ...: 
   ...: 
   ...: client.execute('insert into group_issues_test (issue_name, issue_title) values', rows)
   ...: 

In [5]: client.execute('select * from group_issues_test')
Out[5]: 
[('Issue_name_2',
  'issue_title_2',
  datetime.datetime(2019, 6, 2, 21, 27, 19),
  1),
 ('issue_name_1',
  'issue_title_1',
  datetime.datetime(2019, 6, 2, 21, 27, 19),
  1),
 ('issue_name_3', None, datetime.datetime(2019, 6, 2, 21, 27, 19), 1),
 ('issue_name_4',
  'issue_title_1',
  datetime.datetime(2019, 6, 2, 21, 27, 19),
  1)]
```

**Comment by ghuname** [comment]
Yes, you are right. None works, while np.nan doesn't.
So before inserting data I should check whether column is nullable or not. 
If nullable, I should replace all np.nan's with None, and than insert.
If not nullable, I should prevent inserting until dataframe doesn't contain any na values.

Thanks for clarifying.
Best regards.

**Comment by techkuz** [comment]
thanks @xzkostyan
