### ISSUE TITLE
How temporary tables work with clickhouse_driver?

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/clickhouse-driver#92]
Hi,

I have created a temporary table with:
client.execute('create temporary table temp_table as select * from database.table')

After this command I can select from the table, and everything works well.

When I am using dbeaver over http protocol for doing the same there is a session_timeout parameter in driver that determines how long will temporary table live before it is automatically deleted.

As we are not using http protocol, so we don't have http sessions, how long temporary table lives?
Do we have an option to set this time?

Regards.

**Comment by xzkostyan** [comment]
Hi.

There is a [section](https://clickhouse.yandex/docs/en/single/#temporary-tables) about temporary tables in official docs.

> Temporary tables disappear when the session ends, including if the connection is lost.

This is applied to native protocol.

**Comment by ghuname** [comment]
Hi,
before I asked the question here I have read the clickhouse documentation you have mentioned.

What bothers me..., when we use native protocol, we don't have HTML sessions.
Now, after you reply, I can conclude that temporary table will exist until connection is lost (I wasn't sure before, thanks).

For example, if I restart jupyter notebook, connection is lost, so restarting jupyter notebook is an event of deleting the temporary table.

Thanks for an explanation.

Regards.

**Comment by xzkostyan** [comment]
Hi,

Yep, that's it. Temporary table will exist until connection is lost.
