### ISSUE TITLE
Build error when installing with lz4 compression on OSX 10.4

### ISSUE THREAD

**Issue by darraghenright** [mymarilyn/clickhouse-driver#93]
HI there.

The issue occurs when running `pip install clickhouse-driver[lz4]` on OSX 10.14.5

This is actually an build error with dependency [`clickhouse-cityhash`](https://pypi.org/project/clickhouse-cityhash/) but since that repo does not have issues enabled, and the issue is breaking installation of this repo on my machine I thought I should report here—in case there's a known reason/fix or if anyone else encounters the issue.

The main error:

```
Building wheel for clickhouse-cityhash (setup.py) ... error
```

is followed by a slew of C compilation errors including repeated instances of:

```
src/city.cc:396:5: error: use of undeclared identifier '_mm_crc32_u64'
```

[Full trace on Pastebin](https://pastebin.com/LzUEcXRW). It's rather long so I figured it's better to link—let me know if you want this pasted

It eventually dies after hitting its `-ferror-limit`. I've tried with various flags to disable the error limit, as well as using `gcc` and `g++` instead of `c`, without success.

Looking at `_mm_crc32_u64`, this appears to be very low level, to do with SSE4 instruction sets. I am totally out of my depth with this so any insight is appreciated!

**Comment by xzkostyan** [comment]
Hi.

I'm not quite familiar with Mac OSX. Does your system support SSE 4.2? What is the output of this command?
```bash
grep -q sse4_2 /proc/cpuinfo && echo "SSE 4.2 supported" || echo "SSE 4.2 not supported"
```

**Comment by darraghenright** [comment]
Hi @xzkostyan 

Thanks a million for your response. I was wondering this myself and had a look.`/proc/cpuinfo` does not exist on OSX but if I run the following command:

```
sysctl -a | grep cpu.features
```

It returns the following output, which appears to confirm that SSE4.2 is available:

> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 **SSE4.2** x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

However I am not sure why it is not working if it's available.

**Comment by darraghenright** [comment]
Okay, this is resolved!

Thanks to Peter Cordes on StackOverflow for making some very valuable observations. I'll leave my findings here in case it helps anyone else.

## Issue

In a nutshell, the failing command generated by `pip install` included both `-arch i386` and `-arch x86_64` flags. Apparently, under normal circumstances (x86 clang) the presence of `-arch i386` does not make a difference and 64-bit code will be generated in any case.

However, Apple's clang appears to be a little different...

It appears to generate 32-bit code, which means that `_mm_crc32_u32` is the widest CRC available, which explains why `_mm_crc32_u64` is not defined.

## Solution

It's therefore necessary to use something other than Apple's clang. Most OSX users should be familiar with `brew`. It's possible to install another version of `gcc` if it's not installed already.

You can check if it's installed with:

```
brew list | grep gcc
```

And if not, you can install it with:

```
brew install gcc
```

In my case it was, available in my `$PATH` as `gcc-8`. `brew` usually installs binaries into `/usr/local/bin` if your `$PATH` is not set up. The following worked for me:

```
CC=gcc-8 pip install clickhouse-driver[lz4]
```

Hope this helps someone! Thanks @xzkostyan for weighing in and to everyone who created this library 😎
