### ISSUE TITLE
DateTimeColumn has no timezone

### ISSUE THREAD

**Issue by robert-cody** [mymarilyn/clickhouse-driver#98]
clickhouse_driver/columns/datetimecolumn.py:
```
def after_read_item(self, value):
    dt = datetime.fromtimestamp(value, self.timezone)
    return dt.replace(tzinfo=None)
```

After parsing tzinfo is removed which seems like an incorrect behaviour and has unpredictable side-effects.

**Comment by th0th** [comment]
Is there a specific reason for setting `tzinfo` as `None` there @xzkostyan? If not, I can create a pull request that returns `dt` without replacing `tzinfo`.

**Comment by xzkostyan** [comment]
Nope. There is no reason. Sure, you can create PR.

**Comment by xzkostyan** [comment]
@robert-cody fix is published in master.

**Comment by xzkostyan** [comment]
@robert-cody does fix work as expected?

**Comment by robert-cody** [comment]
Looks good.
