### ISSUE TITLE
can't install clickhouse-cityhash on Windows

### ISSUE THREAD

**Issue by anaskras** [mymarilyn/clickhouse-driver#99]
Building wheels for collected packages: clickhouse-cityhash
  Building wheel for clickhouse-cityhash (setup.py): started
  Building wheel for clickhouse-cityhash (setup.py): finished with status 'error'
  Running setup.py clean for clickhouse-cityhash
Failed to build clickhouse-cityhash
Installing collected packages: clickhouse-cityhash
  Running setup.py install for clickhouse-cityhash: started
    Running setup.py install for clickhouse-cityhash: finished with status 'error'

**Comment by xzkostyan** [comment]
Hi. Do you have compiler installed on your OS? Is this all information that was provided by pip?

It's impossible to determine the reason of failure without additional information.

**Comment by anaskras** [comment]
`pip install clickhouse-driver[lz4,zstd]

Requirement already satisfied: clickhouse-driver[lz4,zstd] in c:\users\USER_NAME\.conda\envs\eq-fault\lib\site-packages (0.0.20)
Requirement already satisfied: pytz in c:\users\USER_NAME\.conda\envs\eq-fault\lib\site-packages (from clickhouse-driver[lz4,zstd]) (2019.1)
Requirement already satisfied: lz4; extra == "lz4" in c:\users\USER_NAME\.conda\envs\eq-fault\lib\site-packages (from clickhouse-driver[lz4,zstd]) (2.1.10)
Collecting clickhouse-cityhash>=1.0.2.1; extra == "lz4" (from clickhouse-driver[lz4,zstd])
  Using cached https://files.pythonhosted.org/packages/71/c6/c89fbccd39186833a6867275a3679d28b1a1d374c28f34b2af2a6a2a3732/clickhouse-cityhash-1.0.2.2.tar.gz
Collecting zstd; extra == "zstd" (from clickhouse-driver[lz4,zstd])
  Using cached https://files.pythonhosted.org/packages/22/37/6a7ba746ebddbd6cd06de84367515d6bc239acd94fb3e0b1c85788176ca2/zstd-1.4.1.0.tar.gz
Building wheels for collected packages: clickhouse-cityhash, zstd
  Building wheel for clickhouse-cityhash (setup.py) ... error
  ERROR: Complete output from command 'C:\Users\USER_NAME\.conda\envs\eq-fault\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER_NAME\\AppData\\Local\\Temp\\pip-install-ljnulwkf\\clickhouse-cityhash\\setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER_NAME\AppData\Local\Temp\pip-wheel-hcpnszl7' --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\clickhouse_cityhash
  copying clickhouse_cityhash\__init__.py -> build\lib.win-amd64-3.6\clickhouse_cityhash
  running build_ext
  building 'clickhouse_cityhash.cityhash' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\USER_NAME\.conda\envs\eq-fault\include -IC:\Users\USER_NAME\.conda\envs\eq-f
ault\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\includ
e\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\
10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/city.cc /Fobuild\temp.win-amd64-3.6\Release\src/city.obj -O3 -msse4.2 -Wno-unused-value -Wno-unused-function
  cl: Є®¬ ¤ п бва®Є  error D8021: Ґ¤®ЇгбвЁ¬л© зЁб«®ў®©  аЈг¬Ґв "/Wno-unused-value"
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ERROR: Failed building wheel for clickhouse-cityhash
  Running setup.py clean for clickhouse-cityhash
  Building wheel for zstd (setup.py) ... done
  Stored in directory: C:\Users\USER_NAME\AppData\Local\pip\Cache\wheels\66\3f\ee\ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
Successfully built zstd
Failed to build clickhouse-cityhash
Installing collected packages: clickhouse-cityhash, zstd
  Running setup.py install for clickhouse-cityhash ... error
    ERROR: Complete output from command 'C:\Users\USER_NAME\.conda\envs\eq-fault\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER_NAME\\AppData\\Local\\Temp\\pip-install-ljnulwkf\\clickhouse-cityhash\\setup.py'"'"';f=getattr(t
okenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER_NAME\AppData\Local\Temp\pip-record-rnlcvhsk\install-record.txt' --single-version-ex
ternally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\clickhouse_cityhash
    copying clickhouse_cityhash\__init__.py -> build\lib.win-amd64-3.6\clickhouse_cityhash
    running build_ext
    building 'clickhouse_cityhash.cityhash' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -IC:\Users\USER_NAME\.conda\envs\eq-fault\include -IC:\Users\USER_NAME\.conda\envs\eq
-fault\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\incl
ude\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/city.cc /Fobuild\temp.win-amd64-3.6\Release\src/city.obj -O3 -msse4.2 -Wno-unused-value -Wno-unused-function
    cl: Є®¬ ¤ п бва®Є  error D8021: Ґ¤®ЇгбвЁ¬л© зЁб«®ў®©  аЈг¬Ґв "/Wno-unused-value"
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

ERROR: Command "'C:\Users\USER_NAME\.conda\envs\eq-fault\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\USER_NAME\\AppData\\Local\\Temp\\pip-install-ljnulwkf\\clickhouse-cityhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
 open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER_NAME\AppData\Local\Temp\pip-record-rnlcvhsk\install-record.txt' --single-version-externally-managed --compi
le" failed with error code 1 in C:\Users\USER_NAME\AppData\Local\Temp\pip-install-ljnulwkf\clickhouse-cityhash\
`

**Comment by xzkostyan** [comment]
I'll try to build wheels for windows in a couple of weeks.

**Comment by xzkostyan** [comment]
Try to install `clickhouse-cityhash` from following wheels:
* https://www.dropbox.com/s/8vw2xv7w18suh1j/clickhouse_cityhash-1.0.2.1-cp36-cp36m-win_amd64.whl
* https://www.dropbox.com/s/oqfdi22ej1w7qng/clickhouse_cityhash-1.0.2.1-cp36-cp36m-win32.whl

I'll publish new release of that package on pypi soon.

**Comment by ghuname** [comment]
pip3 install clickhouse_cityhash-1.0.2.1-cp36-cp36m-win_amd64.whl
ERROR: clickhouse_cityhash-1.0.2.1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

pip3 install clickhouse_cityhash-1.0.2.1-cp36-cp36m-win32.whl
ERROR: clickhouse_cityhash-1.0.2.1-cp36-cp36m-win32.whl is not a supported wheel on this platform.

I still don't know how to install cityhash on windows 10?

**Comment by xzkostyan** [comment]
@ghuname Each version of python requires specific package for it. Those wheels were compiled for python 3.6.

Here are wheels for python 3.7:
* https://www.dropbox.com/s/qjj5r6wug67hect/clickhouse_cityhash-1.0.2.1-cp37-cp37m-win_amd64.whl
* https://www.dropbox.com/s/ffad1iczy85lywm/clickhouse_cityhash-1.0.2.1-cp37-cp37m-win32.whl

They should work for you.

A have some troubles with cityhash building for x86 Linux and Mac OS X. When I solve them all wheels will be published on pypi.

**Comment by xzkostyan** [comment]
Hi.

clickhouse-cityhash version 1.0.2.3 is published on pypi. You can install it via `pip install -U clickhouse-cityhash`.

@ghuname @anaskras can you check it?

**Comment by ghuname** [comment]
> pip install -U clickhouse-cityhash

It works. Thanks

**Comment by anaskras** [comment]
> `pip install -U clickhouse-cityhash`
Hi! Yes, it also works for me now. Thanks!
